### ISSUE TITLE
Web App cannot connect on external network

### ISSUE THREAD

**Issue by sylvester-x** [containers/podman#10281]
Currently, I had using podman to run a web app container. I also added the pory to the firewall. But external network cannot connect to the IP.

The image is working in docker and run in docker can connect to the web app

code to run container
$: podman run --name shell -dt --pod new:pod-shell shell:0.0.2

podman version:
Version:      2.2.1
API Version:  2
Go Version:   go1.14.7
Built:        Tue Feb  9 05:19:06 2021
OS/Arch:      linux/amd64

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Hyper-V hosting REHEL8

**Comment by mheon** [comment]
Can you provide info on the pod? Did this work previously but break
recently?

**Comment by sylvester-x** [comment]
$: podman pod inspect pod-shell
{
     "Id": "98717cd9afbe2549596ef5b08105b13a7eff68dbf3012c9d6035430b43a28060",
     "Name": "pod-shell",
     "Created": "2021-05-09T02:45:02.790514939+08:00",
     "CreateCommand": [
          "podman",
          "run",
          "--name",
          "shell",
          "-dt",
          "--pod",
          "new:pod-shell",
          "-p",
          "7001:80",
          "--net",
          "default",
          "shell:0.0.2"
     ],
     "State": "Running",
     "Hostname": "pod-shell",
     "CreateCgroup": true,
     "CgroupParent": "machine.slice",
     "CgroupPath": "machine.slice/machine-libpod_pod_98717cd9afbe2549596ef5b08105b13a7eff68dbf3012c9d6035430b43a28060.slice",
     "CreateInfra": true,
     "InfraContainerID": "eb4b12711faa46a3b148ac03282871eb04f8c35079783af51d3f0b14cccc079d",
     "InfraConfig": {
          "PortBindings": {
               "80/tcp": [
     {
          "HostIp": "",
          "HostPort": "7001"
     }
]
          },
          "HostNetwork": false,
          "StaticIP": "",
          "StaticMAC": "",
          "NoManageResolvConf": false,
          "DNSServer": null,
          "DNSSearch": null,
          "DNSOption": null,
          "NoManageHosts": false,
          "HostAdd": null,
          "Networks": null,
          "NetworkOptions": null
     },
     "SharedNamespaces": [
          "uts",
          "ipc",
          "net"
     ],
     "NumContainers": 2,
     "Containers": [
          {
               "Id": "87cdc4fc7fb2c6ab55e40d8311f799fe6e00f898455c90d85f219f7867545129",
               "Name": "shell",
               "State": "running"
          },
          {
               "Id": "eb4b12711faa46a3b148ac03282871eb04f8c35079783af51d3f0b14cccc079d",
               "Name": "98717cd9afbe-infra",
               "State": "running"
          }
     ]
}

previously also no working

**Comment by mheon** [comment]
Are you running Podman as root or rootless?

**Comment by sylvester-x** [comment]
yes
![image](https://user-images.githubusercontent.com/45072247/117691433-76e53e00-b1ee-11eb-82de-97db9311874b.png)

I also tried port forwarding to create the container. But still cannot connect 
$: podman run --name shell -dt --pod new:pod-shell -p 7001:80 shell:0.0.2

**Comment by mheon** [comment]
For clarity, the `-p` line on a container in a pod does nothing - the port must be forwarded to the pod, not to individual containers within the pod. That said, I see that it's included in your inspect of the pod, so it should be working.

@mccv1r0 Any ideas here? The Podman side of things seems correct.

**Comment by sylvester-x** [comment]
Yes. I can use curl to the ip:port.

$: nc -n -v 127.0.0.1 7001
![image](https://user-images.githubusercontent.com/45072247/117742556-9c4a6a00-b237-11eb-92c7-8c612e37e57f.png)

$: iptables -L
![image](https://user-images.githubusercontent.com/45072247/117742824-2561a100-b238-11eb-93b5-5d2eec50057b.png)


![image](https://user-images.githubusercontent.com/45072247/117746834-a40e0c80-b23f-11eb-835d-2542cebafd6c.png)

**Comment by sylvester-x** [comment]
Hi, zhangguanzhang
i tried your solution but still cannot connect

**Comment by mccv1r0** [comment]
> Yes. I can use curl to the ip:port.

This is not a podman issue.

The default policy for the FORWARD chain needs to be ACCEPT, or some firewalld equivalent.

Linux is not allowing packets to arrive on one interface and be sent on another.
