### ISSUE TITLE
podman-exec tty resize: stty: standard input

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#10710]
Fallout from #10683 (tty resize). The test even flaked in that very same PR:
```
# # podman exec -it mystty stty size
# stty: standard input

# #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
# #|     FAIL: stty under podman exec reads the correct dimensions
# #| expected: '41 62'
# #|   actual: 'stty: standard input
'
# #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

## sys: podman detects correct tty size
* ubuntu-2104 : sys podman ubuntu-2104 root host
  * PR #10683
    * [06-16 11:55](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6429990330826752/html/sys-podman-ubuntu-2104-root-host.log.html)

...and it just [triggered in a new PR](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5626898622447616/html/sys-podman-ubuntu-2104-root-host.log.html), also ubuntu-2104.

**Comment by edsantiago** [comment]
Yikes - the #10688 flake was a triple:
* [06-17 12:26](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6350591485018112/html/sys-podman-ubuntu-2104-root-host.log.html)
* [06-17 11:20](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5626898622447616/html/sys-podman-ubuntu-2104-root-host.log.html)
* [06-17 07:46](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6446074882686976/html/sys-podman-ubuntu-2104-root-host.log.html)

**Comment by Luap99** [comment]
@edsantiago Are you able to reproduce locally?

**Comment by edsantiago** [comment]
I have not been able to reproduce, because I'm plagued by #10701 on my laptop.

**Comment by mheon** [comment]
I'm struggling to see how this could happen - the resize is now happening in a way that can't race.

**Comment by edsantiago** [comment]
I just reproduced on f34, podman-3.2.1-1.fc34 rootless. Passed on retry.

**Comment by edsantiago** [comment]
Reproduced on same f34 system as above, this time in podman-remote rootless. Does the warning message help?
```
   $ podman-remote run -it --name mystty quay.io/libpod/testimage:20210427 stty size
   stty: standard input
   time="2021-06-17T16:38:39-04:00" level=warning msg="failed to resize TTY: can only resize created or running containers: container state improper"
   #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
   #|     FAIL: stty under podman reads the correct dimensions
   #| expected: '55 28'
'  #|   actual: 'stty: standard input
   #|         > 'time="2021-06-17T16:38:39-04:00" level=warning msg="failed to resize TTY: can only resize created or running containers: container state improper"'
   #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by mheon** [comment]
OK, so the resize is happening too soon, presumably? That at least makes sense.

**Comment by edsantiago** [comment]
Recommendation: try `wait_for_ready`.

**Comment by rhatdan** [comment]
@Luap99 PTAL

**Comment by Luap99** [comment]
> Reproduced on same f34 system as above, this time in podman-remote rootless. Does the warning message help?
> 
> ```
>    $ podman-remote run -it --name mystty quay.io/libpod/testimage:20210427 stty size
>    stty: standard input
>    time="2021-06-17T16:38:39-04:00" level=warning msg="failed to resize TTY: can only resize created or running containers: container state improper"
>    #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
>    #|     FAIL: stty under podman reads the correct dimensions
>    #| expected: '55 28'
> '  #|   actual: 'stty: standard input
>    #|         > 'time="2021-06-17T16:38:39-04:00" level=warning msg="failed to resize TTY: can only resize created or running containers: container state improper"'
>    #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ```

Well you managed to reproduced this issue with `podman-remote run` so this is not the same problem as `podman exec`.

@mheon I believe the race is between podman and conmon. The resize call will simply write to a named pipe and after that podman will write to another pipe to signal conmon that it should start the process.  I can imagine a case where conmon reads the start pipe before the resize pipe.

Conmon never signals podman if the resize even worked.

**Comment by mheon** [comment]
Could we also be looking at an internal latency in Conmon, where the process is not immediately ready after the start pipe is read?

Regardless, this sounds like a reasonable conclusion. I don't see an easy way around it, though - Conmon doesn't tell us that the start signal was received, either, so there's no easy way to syncronize

**Comment by vrothberg** [comment]
Any progress on that?  It's a quite consistent and stubborn flake in the main branch at the moment.

**Comment by vrothberg** [comment]
I opened https://github.com/containers/podman/pull/10758 to disable the flaky tests. We need to make sure to reenable the tests once the underlying issue is fixed (I made sure to drop a comment).

I usually feel strongly about disabling tests but the flakes are just too frequent.

**Comment by rhatdan** [comment]
@edsantiago @vrothberg Any update on this issue?

**Comment by edsantiago** [comment]
The multiarch testing group is [still seeing this](https://gitlab.com/cki-project/kernel-tests/-/issues/683#note_657928149). Podman 3.2.3 on s390x; I don't know if it's Fedora or RHEL. If I read the log correctly, August 19.

**Comment by vrothberg** [comment]
Let's wait for the results on v3.3.0.  We increased the sizes of signal buffers "in hope" to resolve such issues which made it into v3.3.0.

**Comment by rhatdan** [comment]
Well it is a month later, so I am going to assume this is fixed.  Reopen if it happens again.

**Comment by edsantiago** [comment]
The last instance of this in Cirrus CI was June 23. I agree, issue is fixed. (The multiarch folks may still see it, because they test RHEL)

**Comment by Luap99** [comment]
It is not fixed, the test is disabled due the flake. https://github.com/containers/podman/pull/10758

**Comment by edsantiago** [comment]
Uh, I just saw this right now, f35, manual testing rootless:
```
 ✗ podman detects correct tty size
   (from function `is' in file /usr/share/podman/test/system/helpers.bash, line 491,
    in test file /usr/share/podman/test/system/450-interactive.bats, line 60)
     `is "$output" "$rows $cols" "stty under podman run reads the correct dimensions"' failed
   $ podman rm --all --force
   $ podman ps --all --external --format {{.ID}} {{.Names}}
   $ podman images --all --format {{.Repository}}:{{.Tag}} {{.ID}}
   quay.io/libpod/testimage:20210610 9f9ec7f2fdef
   $ podman run -it --name mystty quay.io/libpod/testimage:20210610 stty size
   stty: standard input
   #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
   #|     FAIL: stty under podman run reads the correct dimensions
   #| expected: '71 36'
'  #|   actual: 'stty: standard input
   #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   # [teardown]
   $ podman pod rm --all --force
   $ podman rm --all --force
   3173e7cebc3d34af49d521f76ddf4fd8d03066276b8395c5e992ae73c1ba2642
```
Note that this is in the non-disabled part of the test -- a simple `podman run`. (What was disabled was `podman exec`).

**Comment by edsantiago** [comment]
I just saw this on gating tests for podman-3:3.4.3-1.fc35, rootless:
```
 ✗ podman detects correct tty size
   (from function `is' in file /usr/share/podman/test/system/helpers.bash, line 491,
    in test file /usr/share/podman/test/system/450-interactive.bats, line 60)
     `is "$output" "$rows $cols" "stty under podman run reads the correct dimensions"' failed
   $ podman rm --all --force
   $ podman ps --all --external --format {{.ID}} {{.Names}}
   $ podman images --all --format {{.Repository}}:{{.Tag}} {{.ID}}
   quay.io/libpod/testimage:20210610 9f9ec7f2fdef
   $ podman run -it --name mystty quay.io/libpod/testimage:20210610 stty size
   stty: standard input
   #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
   #|     FAIL: stty under podman run reads the correct dimensions
   #| expected: '21 58'
'  #|   actual: 'stty: standard input
   #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by edsantiago** [comment]
root, too. And I just realized, this is `podman run`, not `exec`. The `exec` test is commented out, completely disabled. We now have `podman run` flaking on this, and it's like over 50%:
```console
# while :;do podman run -it --rm quay.io/libpod/testimage:20210610 stty size;done
stty: standard input
stty: standard input
60 160
stty: standard input
stty: standard input
60 160
60 160
stty: standard input
stty: standard input
stty: standard input
60 160
stty: standard input
stty: standard input
stty: standard input
stty: standard input
stty: standard input
stty: standard input
stty: standard input
60 160
stty: standard input
stty: standard input
60 160
^C
```

**Comment by rhatdan** [comment]
This is happening to you on podman not podman-remote.  I do not get any reproducers.

**Comment by edsantiago** [comment]
I've got a 1minutetip VM right now that's reproducing it super-easily. Ping me for access.

The "remote" connection (in comments above) was me grasping at straws. I don't know if this merits a new issue. My gut tells me no, that the common factor is "stty is broken", not whether it's via exec or remote.

**Comment by Luap99** [comment]
My [comment](https://github.com/containers/podman/issues/10710#issuecomment-863981334) is still valid.

**Comment by edsantiago** [comment]
Flaked in [the very PR that was going to reintroduce the test](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5756524143312896/html/sys-remote-fedora-35-rootless-host.log.html#t--00293). Problem still exists, even if I can't reproduce it on my laptop or a Rawhide VM.

**Comment by Luap99** [comment]
I guess this can be fixed with conmon-rs in the future.

**Comment by edsantiago** [comment]
After a long absence, this is back. [rawhide rootless](https://api.cirrus-ci.com/v1/artifact/task/4673935556476928/html/sys-podman-rawhide-rootless-host-sqlite.log.html#t--00416):
```
not ok 416 podman detects correct tty size
...
$ podman run -it --name mystty quay.io/libpod/testimage:20221018 stty size
stty: standard input

#/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
#|     FAIL: stty under podman run reads the correct dimensions
#| expected: '31 32
'
#|   actual: 'stty: standard input
'
#\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by Luap99** [comment]
Yeah at this point I don't think this is ever going to be fixed, we would need a bidirectional channel to get a success response back from conmon and only then start the container. I guess conmon-rs is your best hope here.
