### ISSUE TITLE
podman build --file with absolute path fails with "no such file or directory" on Mac

### ISSUE THREAD

**Issue by k-wall** [containers/podman#12612]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Running a `podman build` command password a --file parameter as an absolute path fails on a the Mac.  The equivalent command  has doesn't fail on Linux.

**Steps to reproduce the issue:**

1.  Create a Dockerfile
```
cat > /tmp/Dockerfile << EOF
FROM alpine
EOF
```
2.  podman build -f /tmp/Docker .

**Describe the results you received:**

```
Error: stat /var/tmp/libpod_builder708169672/build/private/tmp/Dockerfile: no such file or directory
```

**Describe the results you expected:**

```
podman build -f /tmp/Dockerfile .
STEP 1/1: FROM alpine
COMMIT
--> c059bfaa849
c059bfaa849c4d8e4aecaeb3a10c2d9b3d85f5165c66ad3a4d937758128c4d18
```

**Additional information you deem important (e.g. issue happens only occasionally):**

I tried recreating the podman machine, same result.

**Output of `podman version`:**

```
podman version
Client:
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.17.3
Built:        Wed Dec  8 18:41:11 2021
OS/Arch:      darwin/amd64

Server:
Version:      3.4.2
API Version:  3.4.2
Go Version:   go1.16.8
Built:        Fri Nov 12 20:25:37 2021
OS/Arch:      linux/amd64

```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.30-2.fc35.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.30, commit: '
  cpus: 1
  distribution:
    distribution: fedora
    variant: coreos
    version: "35"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.15.6-200.fc35.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 104640512
  memTotal: 2061389824
  ociRuntime:
    name: crun
    package: crun-1.3-1.fc35.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.3
      commit: 8e5757a4e68590326dafe8a8b1b4a584b10a1370
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc35.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 6h 37m 55.3s (Approximately 0.25 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /var/home/core/.config/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 1
    stopped: 1
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/core/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 180
  runRoot: /run/user/1000/containers
  volumePath: /var/home/core/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.2
  Built: 1636748737
  BuiltTime: Fri Nov 12 20:25:37 2021
  GitCommit: ""
  GoVersion: go1.16.8
  OsArch: linux/amd64
  Version: 3.4.2
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
brew list --versions | grep podman
podman 3.4.4
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Mac OS X Big Sur 11.6.1

**Comment by rhatdan** [comment]
This is working fine in the main branch.
@flouthoc Did you (or Perhaps me) fix this recently?

**Comment by flouthoc** [comment]
@rhatdan You fixed it here https://github.com/containers/podman/pull/10550 and there was another follow up PR for symlinks which i remember. @k-wall Please try it with latest version. Also there a version diff between your `podman` client and `podman` server.

**Comment by mheon** [comment]
I'm going to go ahead and close, since this is fixed upstream.

**Comment by ConorSheehan1** [comment]
Any news on when this will be release?
Still seeing the same issue in latest release [v3.4.4](https://github.com/containers/podman/releases/tag/v3.4.4)

**Comment by mheon** [comment]
The fix for this has been in since 3.3.0, so this may be a new bug - can you open a fresh issue?

**Comment by ConorSheehan1** [comment]
@mheon was a slightly different issue, my bad. logged here https://github.com/containers/podman/issues/12841
