### ISSUE TITLE
podman restart container, no more stdout logs 

### ISSUE THREAD

**Issue by Taymindis** [containers/podman#12776]
podman restart container no more stdout logs

/kind bug

Description

## Steps to reproduce the issue:
```
podman run --name zookeeper-1 -d docker.io/zookeeper
podman logs -f --tail 10 -- working find and still tailing
podman restart zookeeper-1
podman logs -f --tail 10  --- keep exiting, no more tailing


```

```
podman --version
podman version 3.4.2

```

### Why do i think it's a bug,
i have tried `docker` do the same steps, working fine and no issue

**Comment by rhatdan** [comment]
Could you try this against main branch or podman 3.4

I tried your example here and I see logs?

**Comment by Taymindis** [comment]
my server version is 

` ubuntu 20.04 `

I can't find any latest version thatn 3.4.2.

And I could see there is a code merged on 3.4.3 to fixed this [issue](https://github.com/containers/podman/issues/12263)

But i can't find a way to upgrade it unless I build from scratch 

ref:

https://podman.io/getting-started/installation

**Comment by Taymindis** [comment]
@rhatdan 

Any way I can get the 3.4.4 binary or Will it be releasing soon on ubuntu? I saw that version still remain 3.4.2.

**Comment by vrothberg** [comment]
@lsm5 PTAL

**Comment by vrothberg** [comment]
The Ubuntu packages will be updated soon, thanks for pointing it out!

**Comment by mheon** [comment]
I'll dogpile on and say that I definitely recall backporting the fix for this at some point, so it should be resolved on 3.4.4 at latest.

**Comment by nils-ballmann** [comment]
@vrothberg still not updated by now :smile_cat: but that's on a private server... so :shrug: 

```shell-session
$ apt-cache policy podman
podman:
  Installiert:           100:3.4.2-5
  Installationskandidat: 100:3.4.2-5
  Versionstabelle:
 *** 100:3.4.2-5 500
        500 https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/xUbuntu_20.04  Packages
        100 /var/lib/dpkg/status
```

**Comment by vrothberg** [comment]
I think the 20.04 packages will be stuck on this version. Too old golang etc.

**Comment by nils-ballmann** [comment]
Ah okay, we'll it's time to update that server anyway. :smile_cat:
