### ISSUE TITLE
Huston, we got a problem , but do not know how to report it.

### ISSUE THREAD

**Issue by cnmade** [containers/podman#12977]
podman won't working corrent on debian/ubuntu for windows WSL2.

https://github.com/microsoft/WSL/issues/7948

I am confused about the problem, 

Is it a linux kernel problem ?

Or is it a debian problem ,  because ubuntu is base on debian, both them not working. who should respect it ?

Or is it a podman problem?

The error lot said nf_tables no such file  ...

make it looks like a linux kernel problem 

but i have no idea,  what is the real problem cause.

**Comment by cnmade** [comment]
see:
https://github.com/microsoft/WSL/issues/7948

**Comment by mheon** [comment]
Looks specifically to be a problem with that one specific Ubuntu version. This should be fixed upstream by newer versions of Podman and CNI, I believe?

Is there any chance you can update to a newer Ubuntu, which gets its Podman packages from Debian mainline?

**Comment by cnmade** [comment]
I also tried debian with the latest testing debian (Bookworm), problem still exists.
Especially for WSL2 on windows, I am not sure what's wrong. 
The current OpenSuse Tumbleweed not have problem.

**Comment by Luap99** [comment]
I think wsl cannot handle nf_tables properly and debian defaults to iptables-nft. Can you change to iptables-legacy as described here https://wiki.debian.org/nftables. I think this should work.

**Comment by 0x7d7b** [comment]
@Luap99 Thanks, this fixed it for me (using debian testing on wsl2).

**Comment by cnmade** [comment]
I am not need podman for WSL anymore ,  I  run a real podman on linux server, and using podman remote connect to the linux server. it's ok for me
