### ISSUE TITLE
Unable to load an image: "payload does not match any of the supported image formats (oci, oci-archive, dir, docker-archive)"

### ISSUE THREAD

**Issue by kaisataipale** [containers/podman#13139]
/kind bug

**Description**

When I save an image on my Mac with Docker, upload it to a linux machine and try to load the .tar file with podman,
I get 
`Error: payload does not match any of the supported image formats (oci, oci-archive, dir, docker-archive)`

This works fine in  Podman 3.0.2-dev but not in Podman 3.3.1.

I tried building with buildx and setting the type to oci but that didn't make a difference.
`docker buildx build -o type=oci,dest=<image-name>.tar -f Dockerfile .`

**Steps to reproduce the issue:**

In MacOS machine:
1. download a ready-made image or build your own, doesn't make a difference
2. `docker save -o postgres.tar postgres` 
3. upload `postgres.tar` to a linux machine

In Linux machine:
1. `podman load -i  postgres.tar`

**Describe the results you received:**
Error: payload does not match any of the supported image formats (oci, oci-archive, dir, docker-archive)

**Describe the results you expected:**
No errors and image to be listed with 
`podman images`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.3.1
API Version:  3.3.1
Go Version:   go1.16.7
Built:        Tue Nov  9 14:25:58 2021
OS/Arch:      linux/amd64

```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.22.3
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.29-1.module_el8.5.0+2586+018f24d7.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.29, commit: 605b895b7c7a95097901b9db7a9058f0f362d34c'
  cpus: 4
  distribution:
    distribution: '"almalinux"'
    version: "8.5"
  eventLogger: file
  hostname: pelsu2
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 100
      size: 1
    uidmap:
    - container_id: 0
      host_id: 10172
      size: 1
  kernel: 4.18.0-348.12.2.el8_5.x86_64
  linkmode: dynamic
  memFree: 47550947328
  memTotal: 52510380032
  ociRuntime:
    name: runc
    package: runc-1.0.2-1.module_el8.5.0+2586+018f24d7.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.2
      spec: 1.0.2-dev
      go: go1.16.7
      libseccomp: 2.5.1
  os: linux
  remoteSocket:
    path: /run/user/10172/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-1.module_el8.5.0+2586+018f24d7.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 4294963200
  swapTotal: 4294963200
  uptime: 76h 12m 53.74s (Approximately 3.17 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /home/kaisa.taipale/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/kaisa.taipale/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 3
  runRoot: /run/user/10172/containers
  volumePath: /home/kaisa.taipale/.local/share/containers/storage/volumes
version:
  APIVersion: 3.3.1
  Built: 1636460758
  BuiltTime: Tue Nov  9 14:25:58 2021
  GitCommit: ""
  GoVersion: go1.16.7
  OsArch: linux/amd64
  Version: 3.3.1

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.3.1-9.module_el8.5.0+2586+018f24d7.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Comment by nicoeinsidler** [comment]
Maybe this will help you: https://github.com/containers/podman/issues/13112

**Comment by rhatdan** [comment]
Looks like this is fixed in podman 4.0 so closing.

**Comment by kaisataipale** [comment]
> Maybe this will help you: #13112

Thanks for the pointer! Though in my case the disk space is not a problem. I tried this also another linux machine with following steps:

1. `podman --version`                        ->     3.0.2-dev
2. `podman load -i <image>.tar`       ->     success
3. ` sudo dnf update podman` 
4. `podman --version`                        ->   3.4.2
5. `podman load -i <image>.tar`       ->   Error: payload does not match any of the supported image formats (oci, oci-archive, dir, docker-archive)

**Comment by vrothberg** [comment]
Could you share the debug logs? `podman --log-level=debug load -i ....`

**Comment by kaisataipale** [comment]
Debug logs:

INFO[0000] podman filtering at log level debug
DEBU[0000] Called load.PersistentPreRunE(podman --log-level=debug load -i /var/tmp/alpine.tar)
DEBU[0000] overlay storage already configured with a mount-program
DEBU[0000] Merged system config "/usr/share/containers/containers.conf"
DEBU[0000] overlay storage already configured with a mount-program
DEBU[0000] Using conmon: "/usr/bin/conmon"
DEBU[0000] Initializing boltdb state at /home/kaisa.taipale/.local/share/containers/storage/libpod/bolt_state.db
DEBU[0000] Using graph driver overlay
DEBU[0000] Using graph root /home/kaisa.taipale/.local/share/containers/storage
DEBU[0000] Using run root /run/user/10172/containers
DEBU[0000] Using static dir /home/kaisa.taipale/.local/share/containers/storage/libpod
DEBU[0000] Using tmp dir /run/user/10172/libpod/tmp
DEBU[0000] Using volume path /home/kaisa.taipale/.local/share/containers/storage/volumes
DEBU[0000] overlay storage already configured with a mount-program
DEBU[0000] Set libpod namespace to ""
DEBU[0000] [graphdriver] trying provided driver "overlay"
DEBU[0000] overlay: mount_program=/usr/bin/fuse-overlayfs
DEBU[0000] backingFs=xfs, projectQuotaSupported=false, useNativeDiff=false, usingMetacopy=false
DEBU[0000] Initializing event backend file
DEBU[0000] configured OCI runtime kata initialization failed: no valid executable found for OCI runtime kata: invalid argument
DEBU[0000] configured OCI runtime runsc initialization failed: no valid executable found for OCI runtime runsc: invalid argument
DEBU[0000] Using OCI runtime "/usr/bin/runc"
INFO[0000] Found CNI network podman (type=bridge) at /home/kaisa.taipale/.config/cni/net.d/87-podman.conflist
DEBU[0000] Default CNI network name podman is unchangeable
INFO[0000] Setting parallel job count to 13
DEBU[0000] Loading image from "/var/tmp/alpine.tar"
DEBU[0000] -> Attempting to load "/var/tmp/alpine.tar" as an OCI directory
DEBU[0000] parsed reference into "[overlay@/home/kaisa.taipale/.local/share/containers/storage+/run/user/10172/containers:overlay.mount_program=/usr/bin/fuse-overlayfs]localhost/var/tmp/alpine.tar:latest"
DEBU[0000] Copying source image /var/tmp/alpine.tar: to destination image [overlay@/home/kaisa.taipale/.local/share/containers/storage+/run/user/10172/containers:overlay.mount_program=/usr/bin/fuse-overlayfs]localhost/var/tmp/alpine.tar:latest
DEBU[0000] Error loading /var/tmp/alpine.tar: initializing source oci:/var/tmp/alpine.tar:: open /var/tmp/alpine.tar/index.json: not a directory
DEBU[0000] -> Attempting to load "/var/tmp/alpine.tar" as an OCI archive
DEBU[0000] Error deleting temporary directory: <nil>
DEBU[0000] Error loading /var/tmp/alpine.tar: loading index: open /var/tmp/oci496075949/index.json: no such file or directory
DEBU[0000] -> Attempting to load "/var/tmp/alpine.tar" as a Docker dir
DEBU[0000] parsed reference into "[overlay@/home/kaisa.taipale/.local/share/containers/storage+/run/user/10172/containers:overlay.mount_program=/usr/bin/fuse-overlayfs]localhost/var/tmp/alpine.tar:latest"
DEBU[0000] Copying source image /var/tmp/alpine.tar to destination image [overlay@/home/kaisa.taipale/.local/share/containers/storage+/run/user/10172/containers:overlay.mount_program=/usr/bin/fuse-overlayfs]localhost/var/tmp/alpine.tar:latest
DEBU[0000] Using blob info cache at /home/kaisa.taipale/.local/share/containers/cache/blob-info-cache-v1.boltdb
DEBU[0000] Error loading /var/tmp/alpine.tar: determining manifest MIME type for dir:/var/tmp/alpine.tar: open /var/tmp/alpine.tar/manifest.json: not a directory
DEBU[0000] -> Attempting to load "/var/tmp/alpine.tar" as a Docker archive
DEBU[0000] No compression detected
DEBU[0000] parsed reference into "[overlay@/home/kaisa.taipale/.local/share/containers/storage+/run/user/10172/containers:overlay.mount_program=/usr/bin/fuse-overlayfs]localhost/alpine_nginx:latest"
DEBU[0000] Copying source image /var/tmp/alpine.tar:localhost/alpine_nginx:latest to destination image [overlay@/home/kaisa.taipale/.local/share/containers/storage+/run/user/10172/containers:overlay.mount_program=/usr/bin/fuse-overlayfs]localhost/alpine_nginx:latest
DEBU[0000] Using blob info cache at /home/kaisa.taipale/.local/share/containers/cache/blob-info-cache-v1.boltdb
DEBU[0000] No compression detected
DEBU[0000] No compression detected
DEBU[0000] No compression detected
DEBU[0000] IsRunningImageAllowed for image docker-archive:
DEBU[0000]  Using default policy section
DEBU[0000]  Requirement 0: allowed
DEBU[0000] Overall: allowed
Getting image source signatures
DEBU[0000] Manifest has MIME type application/vnd.docker.distribution.manifest.v2+json, ordered candidate list [application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.v1+prettyjws, application/vnd.oci.image.manifest.v1+json, application/vnd.docker.distribution.manifest.v1+json]
DEBU[0000] ... will first try using the original manifest unmodified
DEBU[0000] No compression detected
DEBU[0000] No compression detected
DEBU[0000] Using original blob without modification
DEBU[0000] No compression detected
Copying blob e3318934622a done
DEBU[0000] No compression detected
DEBU[0000] Using original blob without modification
DEBU[0000] No compression detected
DEBU[0000] No compression detected
DEBU[0000] Using original blob without modification
DEBU[0000] Applying tar in /home/kaisa.taipale/.local/share/containers/storage/overlay/8d3ac3489996423f53d6087c81180006263b79f206dCopying blob e3318934622a done
Copying blob 8d3ac3489996 done
Copying blob 8747f1056058 done
DEBU[0000] Error loading /var/tmp/alpine.tar: writing blob: adding layer with blob "sha256:8d3ac3489996423f53d6087c81180006263b79f206d3fdec9e66f0e27ceb8759": Error processing tar file(exit status 1): potentially insufficient UIDs or GIDs available in user namespace (requested 0:42 for /etc/shadow): Check /etc/subuid and /etc/subgid: lchown /etc/shadow: invalid argument
DEBU[0000] Error loading /var/tmp/alpine.tar: payload does not match any of the supported image formats (oci, oci-archive, dir, docker-archive)
Error: payload does not match any of the supported image formats (oci, oci-archive, dir, docker-archive)

**Comment by vrothberg** [comment]
Thank you, now we can see the error:
```
DEBU[0000] Error loading /var/tmp/alpine.tar: writing blob: adding layer with blob "sha256:8d3ac3489996423f53d6087c81180006263b79f206d3fdec9e66f0e27ceb8759": Error processing tar file(exit status 1): potentially insufficient UIDs or GIDs available in user namespace (requested 0:42 for /etc/shadow): Check /etc/subuid and /etc/subgid: lchown /etc/shadow: invalid argument
```

That is curious. It works with Podman v3.0 but not with v3.4? @giuseppe PTAL

**Comment by kaisataipale** [comment]
> Thank you, now we can see the error:
> 
> > DEBU[0000] Error loading /var/tmp/alpine.tar: writing blob: adding layer with blob "sha256:8d3ac3489996423f53d6087c81180006263b79f206d3fdec9e66f0e27ceb8759": Error processing tar file(exit status 1): potentially insufficient UIDs or GIDs available in user namespace (requested 0:42 for /etc/shadow): Check /etc/subuid and /etc/subgid: lchown /etc/shadow: invalid argument
> 
> That is curious. It works with Podman v3.0 but not with v3.4? @giuseppe PTAL

Yep, I did nothing else but changed from v3.0 to v3.4.

**Comment by giuseppe** [comment]
does the image need to be created on MacOS?  I've tried to save the image from Moby running on Linux and the issue doesn't reproduce here

**Comment by giuseppe** [comment]
could you please upload the alpine.tar file here?  I've tried from Ubuntu but I've not managed to create it

**Comment by kaisataipale** [comment]
> could you please upload the alpine.tar file here? I've tried from Ubuntu but I've not managed to create it, since it works well when I load it

Here you go:
[alpine.tar.zip](https://github.com/containers/podman/files/8017046/alpine.tar.zip)

**Comment by vrothberg** [comment]
I load it with Podman 3.4 and 4.0.0 without a problem.

**Comment by kaisataipale** [comment]
> I load it with Podman 3.4 and 4.0.0 without a problem.

Very strange! And I suppose in Linux?

**Comment by kaisataipale** [comment]
> > I load it with Podman 3.4 and 4.0.0 without a problem.

Could the Linux distribution make a difference? Did you load it with `podman load -i alpine.tar`

**Comment by rhatdan** [comment]
Are you sure the User Namespace is fine, have you tried to load the image as root?

**Comment by kaisataipale** [comment]
> Are you sure the User Namespace is fine, have you tried to load the image as root?

Bingo! Running as root indeed made the difference, thank you! Though I'm now puzzled why it worked with 3.0. Never crossed my mind that root privileges would be needed with the new version.

**Comment by giuseppe** [comment]
what is the output of `podman unshare cat /proc/self/uid_map /proc/self/gid_map`?

**Comment by kaisataipale** [comment]
> what is the output of `podman unshare cat /proc/self/uid_map /proc/self/gid_map`?

         0       1000          1
         1     100000      65536
         0       1000          1
         1     100000      65536

**Comment by giuseppe** [comment]
thanks!  That looks like the user namespace was created correctly.

Does it make any difference if you wrap `podman load` with `podman unshare` like:

`podman unshare podman load -i alpine.tar`?

**Comment by kaisataipale** [comment]
> podman unshare podman load -i alpine.tar

`Getting image source signatures
Copying blob e3318934622a done
Copying blob 8d3ac3489996 done
Copying blob 8747f1056058 done
Error: payload does not match any of the supported image formats (oci, oci-archive, dir, docker-archive)
Error: exit status 125
`

**Comment by giuseppe** [comment]
thanks, could you attach the output you get with: `podman --log-level debug load -i alpine.tar`?

I've tried locally, and this is what I got with the file you've provided:

``
$ podman --log-level debug load -i alpine.tar`
...
   
DEBU[0000] Loading image from "alpine.tar"              
DEBU[0000] -> Attempting to load "alpine.tar" as an OCI directory 
DEBU[0000] parsed reference into "[overlay@/home/gscrivano/.local/share/containers/storage+/run/user/1000/containers]localhost/alpine.tar:latest" 
DEBU[0000] Copying source image alpine.tar: to destination image [overlay@/home/gscrivano/.local/share/containers/storage+/run/user/1000/containers]localhost/alpine.tar:latest 
DEBU[0000] Error loading alpine.tar: initializing source oci:alpine.tar:: open alpine.tar/index.json: not a directory 
DEBU[0000] -> Attempting to load "alpine.tar" as an OCI archive 
DEBU[0000] Error deleting temporary directory: <nil>    
DEBU[0000] Error loading alpine.tar: loading index: open /var/tmp/oci096679137/index.json: no such file or directory 
DEBU[0000] -> Attempting to load "alpine.tar" as a Docker dir 
DEBU[0000] parsed reference into "[overlay@/home/gscrivano/.local/share/containers/storage+/run/user/1000/containers]localhost/alpine.tar:latest" 
DEBU[0000] Copying source image alpine.tar to destination image [overlay@/home/gscrivano/.local/share/containers/storage+/run/user/1000/containers]localhost/alpine.tar:latest 
DEBU[0000] Using blob info cache at /home/gscrivano/.local/share/containers/cache/blob-info-cache-v1.boltdb 
DEBU[0000] Error loading alpine.tar: determining manifest MIME type for dir:alpine.tar: open alpine.tar/manifest.json: not a directory 
DEBU[0000] -> Attempting to load "alpine.tar" as a Docker archive 
DEBU[0000] No compression detected                      
DEBU[0000] parsed reference into "[overlay@/home/gscrivano/.local/share/containers/storage+/run/user/1000/containers]docker.io/library/alpine:latest" 
DEBU[0000] Copying source image alpine.tar:docker.io/library/alpine:latest to destination image [overlay@/home/gscrivano/.local/share/containers/storage+/run/user/1000/containers]docker.io/library/alpine:latest 
DEBU[0000] Using blob info cache at /home/gscrivano/.local/share/containers/cache/blob-info-cache-v1.boltdb 
DEBU[0000] No compression detected                      
DEBU[0000] IsRunningImageAllowed for image docker-archive: 
DEBU[0000]  Using default policy section                
DEBU[0000]  Requirement 0: allowed                      
DEBU[0000] Overall: allowed                             
Getting image source signatures
DEBU[0000] Manifest has MIME type application/vnd.docker.distribution.manifest.v2+json, ordered candidate list [application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.v1+prettyjws, application/vnd.oci.image.manifest.v1+json, application/vnd.docker.distribution.manifest.v1+json] 
DEBU[0000] ... will first try using the original manifest unmodified 
DEBU[0000] No compression detected                      
DEBU[0000] No compression detected                      
DEBU[0000] Using original blob without modification     
Copying blob 8d3ac3489996 done  
DEBU[0000] Applying tar in /home/gscrivano/.local/share/containers/storage/overlay/8d3ac3489996423f53d6087c81180006263Copying blob 8d3ac3489996 done  
DEBU[0000] No compression detected                      
DEBU[0000] Using original blob without modification     
Copying config c059bfaa84 done  
Writing manifest to image destination
Storing signatures

...
```

**Comment by kaisataipale** [comment]
> podman --log-level debug load -i alpine.tar

INFO[0000] podman filtering at log level debug
DEBU[0000] Called load.PersistentPreRunE(podman --log-level debug load -i alpine.tar)
DEBU[0000] cached value indicated that overlay is supported
DEBU[0000] Merged system config "/usr/share/containers/containers.conf"
DEBU[0000] cached value indicated that overlay is supported
DEBU[0000] Using conmon: "/usr/bin/conmon"
DEBU[0000] Initializing boltdb state at /home/kaisa.taipale/.local/share/containers/storage/libpod/bolt_state.db
DEBU[0000] Using graph driver overlay
DEBU[0000] Using graph root /home/kaisa.taipale/.local/share/containers/storage
DEBU[0000] Using run root /run/user/10172/containers
DEBU[0000] Using static dir /home/kaisa.taipale/.local/share/containers/storage/libpod
DEBU[0000] Using tmp dir /run/user/10172/libpod/tmp
DEBU[0000] Using volume path /home/kaisa.taipale/.local/share/containers/storage/volumes
DEBU[0000] cached value indicated that overlay is supported
DEBU[0000] Set libpod namespace to ""
DEBU[0000] [graphdriver] trying provided driver "overlay"
DEBU[0000] cached value indicated that overlay is supported
DEBU[0000] cached value indicated that metacopy is not being used
DEBU[0000] cached value indicated that native-diff is usable
DEBU[0000] backingFs=xfs, projectQuotaSupported=false, useNativeDiff=true, usingMetacopy=false
DEBU[0000] Initializing event backend file
DEBU[0000] configured OCI runtime crun initialization failed: no valid executable found for OCI runtime crun: invalid argument
DEBU[0000] configured OCI runtime kata initialization failed: no valid executable found for OCI runtime kata: invalid argument
DEBU[0000] configured OCI runtime runsc initialization failed: no valid executable found for OCI runtime runsc: invalid argument
DEBU[0000] Using OCI runtime "/usr/bin/runc"
INFO[0000] Found CNI network podman (type=bridge) at /home/kaisa.taipale/.config/cni/net.d/87-podman.conflist
DEBU[0000] Default CNI network name podman is unchangeable
INFO[0000] Setting parallel job count to 13
DEBU[0000] Loading image from "alpine.tar"
DEBU[0000] -> Attempting to load "alpine.tar" as an OCI directory
DEBU[0000] parsed reference into "[overlay@/home/kaisa.taipale/.local/share/containers/storage+/run/user/10172/containers]localhost/alpine.tar:latest"
DEBU[0000] Copying source image alpine.tar: to destination image [overlay@/home/kaisa.taipale/.local/share/containers/storage+/run/user/10172/containers]localhost/alpine.tar:latest
DEBU[0000] Error loading alpine.tar: initializing source oci:alpine.tar:: open alpine.tar/index.json: not a directory
DEBU[0000] -> Attempting to load "alpine.tar" as an OCI archive
DEBU[0000] Error deleting temporary directory: <nil>
DEBU[0000] Error loading alpine.tar: loading index: open /var/tmp/oci982130750/index.json: no such file or directory
DEBU[0000] -> Attempting to load "alpine.tar" as a Docker dir
DEBU[0000] parsed reference into "[overlay@/home/kaisa.taipale/.local/share/containers/storage+/run/user/10172/containers]localhost/alpine.tar:latest"
DEBU[0000] Copying source image alpine.tar to destination image [overlay@/home/kaisa.taipale/.local/share/containers/storage+/run/user/10172/containers]localhost/alpine.tar:latest
DEBU[0000] Using blob info cache at /home/kaisa.taipale/.local/share/containers/cache/blob-info-cache-v1.boltdb
DEBU[0000] Error loading alpine.tar: determining manifest MIME type for dir:alpine.tar: open alpine.tar/manifest.json: not a directory
DEBU[0000] -> Attempting to load "alpine.tar" as a Docker archive
DEBU[0000] No compression detected
DEBU[0000] parsed reference into "[overlay@/home/kaisa.taipale/.local/share/containers/storage+/run/user/10172/containers]localhost/alpine_nginx:latest"
DEBU[0000] Copying source image alpine.tar:localhost/alpine_nginx:latest to destination image [overlay@/home/kaisa.taipale/.local/share/containers/storage+/run/user/10172/containers]localhost/alpine_nginx:latest
DEBU[0000] Using blob info cache at /home/kaisa.taipale/.local/share/containers/cache/blob-info-cache-v1.boltdb
DEBU[0000] No compression detected
DEBU[0000] No compression detected
DEBU[0000] No compression detected
DEBU[0000] IsRunningImageAllowed for image docker-archive:
DEBU[0000]  Using default policy section
DEBU[0000]  Requirement 0: allowed
DEBU[0000] Overall: allowed
Getting image source signatures
DEBU[0000] Manifest has MIME type application/vnd.docker.distribution.manifest.v2+json, ordered candidate list [application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.v1+prettyjws, application/vnd.oci.image.manifest.v1+json, application/vnd.docker.distribution.manifest.v1+json]
DEBU[0000] ... will first try using the original manifest unmodified
DEBU[0000] No compression detected
DEBU[0000] No compression detected
DEBU[0000] Using original blob without modification
DEBU[0000] No compression detected
Copying blob e3318934622a done
Copying blob e3318934622a done
DEBU[0000] No compression detected
DEBU[0000] Using original blob without modification
DEBU[0000] No compression detected
Copying blob e3318934622a done
Copying blob 8d3ac3489996 done
Copying blob e3318934622a done
Copying blob 8d3ac3489996 done
Copying blob 8747f1056058 done
DEBU[0000] Error loading alpine.tar: writing blob: adding layer with blob "sha256:8d3ac3489996423f53d6087c81180006263b79f206d3fdec9e66f0e27ceb8759": Error processing tar file(exit status 1): potentially insufficient UIDs or GIDs available in user namespace (requested 0:42 for /etc/shadow): Check /etc/subuid and /etc/subgid: lchown /etc/shadow: invalid argument
DEBU[0000] Error loading alpine.tar: payload does not match any of the supported image formats (oci, oci-archive, dir, docker-archive)
Error: payload does not match any of the supported image formats (oci, oci-archive, dir, docker-archive)

**Comment by giuseppe** [comment]
thanks again.  Are you always using the same user and host for running these commands?

Because from the log above it seems there are not enough IDs in the user namespace, as confirmed by your original report:
```
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 100
      size: 1
    uidmap:
    - container_id: 0
      host_id: 10172
      size: 1
```

but `podman unshare cat /proc/self/uid_map /proc/self/gid_map` showed different IDs available.

Does `podman system migrate` make any difference if you run it before you attempt to load the image?

**Comment by kaisataipale** [comment]
> thanks again. Are you always using the same user and host for running these commands?
> 
> Because from the log above it seems there are not enough IDs in the user namespace, as confirmed by your original report:
> 
> ```
>   idMappings:
>     gidmap:
>     - container_id: 0
>       host_id: 100
>       size: 1
>     uidmap:
>     - container_id: 0
>       host_id: 10172
>       size: 1
> ```
> 
> but `podman unshare cat /proc/self/uid_map /proc/self/gid_map` showed different IDs available.
> 
> Does `podman system migrate` make any difference if you run it before you attempt to load the image?

Sorry, my bad! I accidentally ran the unshare command with another user. I updated my above comment. (don't know if that's the best practice to afterwards modify these comments though).

**Comment by giuseppe** [comment]
no worries!

So it seems your user has access only to one ID.  Is your user listed in the `/etc/subuid` and `/etc/subgid` files?

If you make any change there, you need to run `podman system migrate` in order for Podman to reload this information and recreate the user namespace

**Comment by kaisataipale** [comment]
> podman system migrate

Yessss! By adding the problematic user into those files and running the `podman system migrate` loading works like a charm. Thank you for super quick responses and help! My problem is solved but of course the error message is still a bit misleading.

**Comment by giuseppe** [comment]
@vrothberg should we report back somehow the original error?

**Comment by vrothberg** [comment]
This has been fixed with Podman 4.0 where we'll report _all_ errors.  Users still have to parse all errors but they're all reported and not hidden in the debug logs.  I think we can close.

**Comment by bruteforks** [comment]
Yeah this is still happening, podman version 4.5.1, using fedora immutable distro.

**Comment by vrothberg** [comment]
@bruteforks, please open a new issue, ideally with a reproducer.
