### ISSUE TITLE
vfs-driver: mkdir requires -p

### ISSUE THREAD

**Issue by geoynomous** [containers/podman#14380]
/kind bug

**Description**

When using vfs-driver in rootful setup, the mkdir misses to first create some parent directory - a "-p" solves it

**Steps to reproduce the issue:**

1. Try a simple `pull`

```
bash-5.1# podman --root /installation/containers/ pull hello-world
Resolving "hello-world" using unqualified-search registries (/etc/containers/registries.conf)
Trying to pull docker.io/library/hello-world:latest...
Getting image source signatures
Copying blob 2db29710123e done  
ERRO[0004] While applying layer: ApplyLayer exit status 1 stdout:  stderr: Error setting up pivot dir: mkdir /installation/containers/vfs/dir/e07ee1baac5fae6a26f30cabfe54a36d3402f96afda318fe0a96cec4ca393359/.pivot_root4243434813: operation not permitted 
Error: writing blob: adding layer with blob "sha256:2db29710123e3e53a794f2694094b9b4338aa9ee5c40b930cb8063a1be392c54": ApplyLayer exit status 1 stdout:  stderr: Error setting up pivot dir: mkdir /installation/containers/vfs/dir/e07ee1baac5fae6a26f30cabfe54a36d3402f96afda318fe0a96cec4ca393359/.pivot_root4243434813: operation not permitted
```

Fails!

2. mkdir the directory manually

`bash-5.1# mkdir /installation/containers/vfs/dir/e07ee1baac5fae6a26f30cabfe54a36d3402f96afda318fe0a96cec4ca393359
`

3. Do the `pull` again

```
bash-5.1# podman --root /installation/containers/ pull hello-world
Resolving "hello-world" using unqualified-search registries (/etc/containers/registries.conf)
Trying to pull docker.io/library/hello-world:latest...
Getting image source signatures
Copying blob 2db29710123e done  
Copying config feb5d9fea6 done  
Writing manifest to image destination
Storing signatures
feb5d9fea6a5e9606aa995e879d862b825965ba48de054caab5ef356dc6b3412
```

Works!

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes, fails with 3.4.7 and 4.1.0

**Comment by mheon** [comment]
@nalind PTAL

**Comment by rhatdan** [comment]
I can not get this to fail on my system.

```
sh-5.1# rm -rf /installation/
sh-5.1# podman --storage-driver=vfs --root /installation/containers/ pull hello-world
Resolved "hello-world" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull quay.io/podman/hello:latest...
Getting image source signatures
Copying blob e49e28f7fd96 done  
Copying config e7e8058dd1 done  
Writing manifest to image destination
Storing signatures
e7e8058dd1467ba6b705341295ba45c3ce99527ea4a02277f50ac250316b2631
```

**Comment by nalind** [comment]
Can you tell us more about the environment in which this is running?  Is it in a container?
The `mkdir ...: operation not permitted` error is surprising, because a missing parent directory should have triggered a "no such file or directory" error.
The driver would also normally have been called to create the layer's directory right before the image-pulling logic attempted to extract the contents of a layer blob into that directory, so it's not clear to me why manually creating the directory changed things.

**Comment by geoynomous** [comment]
Yes - I digged into it - the /installation/containers is a mounted filesystem. To be precise - we are running podman inside a docker (currently, soon podman) - so build images in a shared (mounted) filesystem - such that later they are pre-cached on an AWS EFS in an AWS Fargate scenario.

**Comment by geoynomous** [comment]
@nalind I am not familiar with the driver internals too much - I only see that the `mkdir -p` works to create the "parent" inside the running container - while the `mkdir` during `pull` does not ...

**Comment by rhatdan** [comment]
Any chance you could give us a simple reproducer with either podman running in a docker or podman container?

**Comment by geoynomous** [comment]
Yes I can provide - but takes until Sunday

**Comment by geoynomous** [comment]
Here is a Dockerfile - the $ commands are on the host - the # commands are inside the running docker container

```
FROM node:16.15.0-alpine3.15 as outer

RUN true \
    && apk add --no-cache \
        bash \
        podman

# BUILD
# $ docker build --target outer -t outer:latest -f Dockerfile .

# RUN
# $ docker run --privileged -it --rm -v `pwd`:/installation/ outer:latest bash

# --privileged is important

# IN CONTAINER
# # podman info
# WARN[0000] "/" is not a shared mount, this could cause issues or missing mounts with rootless containers 
# cannot clone: Operation not permitted
# Error: cannot re-exec process

# Side-remark: This is an error tough to decode

# Now the actual problem

# # podman --storage-driver vfs --root /installation/containers pull hello-world

# Results in 

# Resolving "hello-world" using unqualified-search registries (/etc/containers/registries.conf)
# Trying to pull docker.io/library/hello-world:latest...
# Getting image source signatures
# Copying blob 2db29710123e done  
# ERRO[0004] While applying layer: ApplyLayer exit status 1 stdout:  stderr: Error setting up pivot dir: mkdir /installation/containers/vfs/dir/e07ee1baac5fae6a26f30cabfe54a36d3402f96afda318fe0a96cec4ca393359/.pivot_root2130493239: operation not permitted 
# Error: writing blob: adding layer with blob "sha256:2db29710123e3e53a794f2694094b9b4338aa9ee5c40b930cb8063a1be392c54": ApplyLayer exit status 1 stdout:  stderr: Error setting up pivot dir: mkdir /installation/containers/vfs/dir/e07ee1baac5fae6a26f30cabfe54a36d3402f96afda318fe0a96cec4ca393359/.pivot_root2130493239: operation not permitted

# Doing 

# # mkdir /installation/containers/vfs/dir/e07ee1baac5fae6a26f30cabfe54a36d3402f96afda318fe0a96cec4ca393359
# # podman --storage-driver vfs --root /installation/containers pull hello-world

# Works: 

# Resolving "hello-world" using unqualified-search registries (/etc/containers/registries.conf)
# Trying to pull docker.io/library/hello-world:latest...
# Getting image source signatures
# Copying blob 2db29710123e done  
# Copying config feb5d9fea6 done  
# Writing manifest to image destination
# Storing signatures
# feb5d9fea6a5e9606aa995e879d862b825965ba48de054caab5ef356dc6b3412
```

Feel free to reach out for more details ....

**Comment by rhatdan** [comment]
@flouthoc PTAL

**Comment by rhatdan** [comment]
@nalind PTAL

**Comment by rhatdan** [comment]
@geoynomous are you still able to hit this issue with podman 4.2?

**Comment by geoynomous** [comment]
I will check ...

**Comment by rhatdan** [comment]
Since we never heard back, I am going to assume this is fixed.

**Comment by geoynomous** [comment]
Hi .. sorry only was able now to get back to it ... it still happens on podman 4.3.1

More info - it happens when the "--root" (i.e., ``/installation``) is double mounted - once for the outer docker, but the outer docker host has this filesystem also mounted. Reproduced it with EFS and with docker desktop for mac

**Comment by geoynomous** [comment]
I've checked the code - in particular the file ``chroot_unix.go``

The respective line is ``os.MkdirTemp(path, ".pivot_root")`` in line 53 of https://github.com/containers/podman/blob/main/vendor/github.com/containers/storage/pkg/chrootarchive/chroot_linux.go

It returns with **permission denied**. I've checked: ``path`` has permission ``0555`` and I've also used ``user.Current()`` that writes me 
``current user  &{Uid:0 Gid:0 Username:root Name:root HomeDir:/root}``

So instead of ``podman pull`` with the my UID 1000, it is doing with with ``root``- probably in the chroot env - but should't it have then all relevant access rights.

Remember when I do the ``mkdir`` before ``podman pull`` - all is executed correctly and I can ``run`` the image
