### ISSUE TITLE
Podman Windows, Git Bash: connection actively refused

### ISSUE THREAD

**Issue by dougbreaux** [containers/podman#15975]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

From Git Bash, any podman command that needs to connect to the running machine fails

**Steps to reproduce the issue:**

1. `podman machine init`/`start`/`list` all work

2. `podman info` (or `images`, or `build`, or etc.) fails with the above error

**Describe the results you received:**

```
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman. failed to create sshClient: dial unix C:/Users/DOUGBR~1/AppData/Local/Temp/ssh-yZShGYtI48J8/agent.691: connect: No connection could be made because the target machine actively refused it.
```

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

Same commands from CMD.EXE work.

**Output of `podman version`:**

Same error as above from Git Bash attempt. But from CMD.EXE:

```
C:\Projects\saz\saz-checkfreepay-api>podman version
Client:       Podman Engine
Version:      4.2.1
API Version:  4.2.1
Go Version:   go1.16.15
Git Commit:   62b324ddf718411b1d4d0ba8117c632f7f984a38
Built:        Wed Sep  7 08:08:04 2022
OS/Arch:      windows/amd64

Server:       Podman Engine
Version:      4.2.0
API Version:  4.2.0
Go Version:   go1.16.15
Built:        Fri Aug 26 10:18:12 2022
OS/Arch:      linux/amd64
```

**Output of `podman info`:**

Same error as above from Git Bash attempt. But from CMD.EXE:

```yaml
host:
  arch: amd64
  buildahVersion: 1.27.0
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.3-1.fc35.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.3, commit: '
  cpuUtilization:
    idlePercent: 98.48
    systemPercent: 0.67
    userPercent: 0.85
  cpus: 8
  distribution:
    distribution: fedora
    variant: container
    version: "35"
  eventLogger: file
  hostname: BreauxP50
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.10.102.1-microsoft-standard-WSL2
  linkmode: dynamic
  logDriver: journald
  memFree: 24415428608
  memTotal: 26723000320
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.5-1.fc35.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.5
      commit: 54ebb8ca8bf7e6ddae2eb919f5b82d1d96863dea
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc35.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 7516192768
  swapTotal: 7516192768
  uptime: 1h 18m 55.00s (Approximately 0.04 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/user/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/user/.local/share/containers/storage
  graphRootAllocated: 269490393088
  graphRootUsed: 1555988480
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 12
  runRoot: /run/user/1000/containers
  volumePath: /home/user/.local/share/containers/storage/volumes
version:
  APIVersion: 4.2.0
  Built: 1661527092
  BuiltTime: Fri Aug 26 10:18:12 2022
  GitCommit: ""
  GoVersion: go1.16.15
  Os: linux
  OsArch: linux/amd64
  Version: 4.2.0
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

N/A

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Git Bash, current version
```console
$ git --version
git version 2.37.3.windows.1
```

**Comment by mheon** [comment]
@n1hility PTAL

**Comment by cdoern** [comment]
could be resolved with the current code in main

**Comment by rhatdan** [comment]
Since we believe this is fixed in main, I am going to close, reopen if I am mistaken.

**Comment by dougbreaux** [comment]
Yes, I confirm this issue is no longer occurring here, thanks.

**Comment by caneserr** [comment]
I still experience the problem. I have no 

![resim](https://user-images.githubusercontent.com/29177826/215285546-8b1c4b83-e619-4e9a-b038-0a1ce145ff8b.png)

**Comment by rhatdan** [comment]
Please open a new issue. And make sure the version of podman inside of the `podman machine` is the same version as that on the Windows or Mac box.

**Comment by mavaddat** [comment]
> Please open a new issue. And make sure the version of podman inside of the `podman machine` is the same version as that on the Windows or Mac box.

I did not realze that I needed to run `podman machine` after `podman machine init`, so this suggestion solved the issue for me. Maybe we could help future users (inlcuding future me who will immediately forget this solution) by suggesting they run `podman machine` after `podman machine init`?

**Comment by yosiasz** [comment]
`podman machine ssh`
then
`podman -v`

shows a different version of podman. let me revert my windows podman  -v and see what happens
