### ISSUE TITLE
[Bug]: ERRO[0000] Refreshing container 0a86ba260788ca0ba3f3a05f919ddb9e86822dc0c43c338e06cb15161a4e57d1: error acquiring lock 101 for container 0a86ba260788ca0ba3f3a05f919ddb9e86822dc0c43c338e06cb15161a4e57d1: file exists

### ISSUE THREAD

**Issue by nkartem** [containers/podman#17091]
### Issue Description

After some time of working containers, I have an error:

```
[user@hub7489 ~]$ podman ps

ERRO[0000] Refreshing container 0a86ba260788ca0ba3f3a05f919ddb9e86822dc0c43c338e06cb15161a4e57d1: error acquiring lock 101 for container 0a86ba260788ca0ba3f3a05f919ddb9e86822dc0c43c338e06cb15161a4e57d1: file exists

ERRO[0000] Refreshing container 36d420b665bee1a0114e0ecf422103a0c39e43bcdc83a146625dd82cf83c5ab3: error acquiring lock 85 for container 36d420b665bee1a0114e0ecf422103a0c39e43bcdc83a146625dd82cf83c5ab3: file exists

ERRO[0000] Refreshing container 391e2498e79e4a0d80b7beb8cdcfcebc673a896e82261995c964816e0584e83e: error acquiring lock 93 for container 391e2498e79e4a0d80b7beb8cdcfcebc673a896e82261995c964816e0584e83e: file exists

ERRO[0000] Refreshing container 64ae59a97e037447d6b9b2782b0027970becb4ce5e331ca5b35d9d25f5112e86: error acquiring lock 109 for container 64ae59a97e037447d6b9b2782b0027970becb4ce5e331ca5b35d9d25f5112e86: file exists

ERRO[0000] Refreshing container e5c2c3edd6f1f36ff2324f4da7a2c31dab41a3c86607ba8eeb902d8a9eec4ead: error acquiring lock 42 for container e5c2c3edd6f1f36ff2324f4da7a2c31dab41a3c86607ba8eeb902d8a9eec4ead: file exists

ERRO[0000] Refreshing volume 015f1db2859d7f8b58b83857d74922815d1b56ea58ba6f29b69abe2ec0615049: acquiring lock 44 for volume 015f1db2859d7f8b58b83857d74922815d1b56ea58ba6f29b69abe2ec0615049: file exists

ERRO[0000] Refreshing volume 0188c8bd2c4ba578542296c322e02fde9bb4266325e868a3b94b664861174706: acquiring lock 0 for volume 0188c8bd2c4ba578542296c322e02fde9bb4266325e868a3b94b664861174706: file exists

ERRO[0000] Refreshing volume 024bbd6faa8dac0cd4684bb1d5e310b465129ad94810c3391090912542e55e1b: acquiring lock 69 for volume 024bbd6faa8dac0cd4684bb1d5e310b465129ad94810c3391090912542e55e1b: file exists

ERRO[0000] Refreshing volume 0889a199e2a42fa106e3438063886ccb66e5ce0fdf1e73f4f9ccfa56690d861a: acquiring lock 80 for volume 0889a199e2a42fa106e3438063886ccb66e5ce0fdf1e73f4f9ccfa56690d861a: file exists

ERRO[0000] Refreshing volume 090d3983df9a8cff6b52f8ede3e4ad3d7fadad4da3008e516d157c1f77c69746: acquiring lock 91 for volume 090d3983df9a8cff6b52f8ede3e4ad3d7fadad4da3008e516d157c1f77c69746: file exists

ERRO[0000] Refreshing volume 099c72369ac4791e4d7f902c536856462f2941287fe35fc00c6c705403bf36f7: acquiring lock 1 for volume 099c72369ac4791e4d7f902c536856462f2941287fe35fc00c6c705403bf36f7: file exists
```
************

### Steps to reproduce the issue

Steps to reproduce the issue
1.  Start containers with `podman-compose up -d`
2.  After some time of working containers, I have an error

### Describe the results you received

Not stable work.
Errors.

### Describe the results you expected

Describe the results you expected

### podman info output

```shell
[user@hub7489 ~]$ podman version
Client:       Podman Engine
Version:      4.0.2
API Version:  4.0.2
Go Version:   go1.17.7

Built:      Tue Apr 19 12:16:32 2022
OS/Arch:    linux/amd64
```
***************
```
[user@hub7489 ~]$ podman info
host:
  arch: amd64
  buildahVersion: 1.24.1
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.0-1.module+el8.6.0+14877+f643d2d6.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: 87b7a9037cbd1d81288bdf2d6705dfda889f7cf9'
  cpus: 2
  distribution:
    distribution: '"rhel"'
    version: "8.6"
  eventLogger: file
  hostname: docker-hub
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 4.18.0-425.3.1.el8.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 120840192
  memTotal: 867504128
  networkBackend: netavark
  ociRuntime:
    name: runc
    package: runc-1.0.3-2.module+el8.6.0+14877+f643d2d6.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.3
      spec: 1.0.2-dev
      go: go1.17.7
      libseccomp: 2.5.2
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-2.module+el8.6.0+14877+f643d2d6.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 2004152320
  swapTotal: 2147479552
  uptime: 742h 11m 3.27s (Approximately 30.92 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /home/user/.config/containers/storage.conf
  containerStore:
    number: 5
    paused: 0
    running: 0
    stopped: 5
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/user/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 6
  runRoot: /run/user/1000/containers
  volumePath: /home/user/.local/share/containers/storage/volumes
version:
  APIVersion: 4.0.2
  Built: 1650363392
  BuiltTime: Tue Apr 19 12:16:32 2022
  GitCommit: ""
  GoVersion: go1.17.7
  OsArch: linux/amd64
  Version: 4.0.2
```
**************************
```
[user@hub7489 ~]$ rpm -q podman
podman-4.0.2-6.module+el8.6.0+14877+f643d2d6.x86_64
```

************************************
```
[user@hub7489  ~]$ podman-compose --v
['podman', '--version', '']
using podman version: 4.0.2
podman-composer version  1.0.3
podman --version
podman version 4.0.2
exit code: 0
```
```


### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by vrothberg** [comment]
Thanks for reaching out.  This version is not supported upstream anymore.  Please reach out through the Red Hat customer channels (e.g., Bugzilla).

The issue may have already been fixed in a newer version of Podman.

**Comment by NikitaKharkov** [comment]
@vrothberg I have version 4.2.0 and still have the same bug.
After some time containers are down. What's wrong?
