### ISSUE TITLE
push uploads already existing layers

### ISSUE THREAD

**Issue by universam1** [containers/podman#17892]
### Issue Description

As suggested by @vrothberg in https://github.com/containers/podman/issues/10247#issuecomment-1419024369 reopening the same issue as this becomes a daily business issue, we can reproduce it, and `skopeo` does not have this issue.

Our images have base layers of several GB size. The CI produces daily diffs as a new, tiny layer. However, Podman (and Buidah) are unable to detect the existance of the large base layers in the registry, and perform a re-upload again in every CI step. This produces a significant amount of traffic and delays of the pipeline.

This happens, because our CI jobs do not have a warm graphroot cache and will never since they are ephemeral pods.

**Skopeo** however does not have this bug - see the below.

### Steps to reproduce the issue

Steps to reproduce the issue

**Podman or Buildah**. 

```sh
for i in {1..2}; do 
podman run -it --rm --user podman podman:latest sh -c "\
  podman pull docker.io/library/mysql:5.7.41 && \
  podman tag docker.io/library/mysql:5.7.41 ttl.sh/testimg:1h && \
  time podman push ttl.sh/testimg:1h"
done
```

However run the same with **Skopeo**:

```sh
for i in {1..2}; do
  time podman run -it --rm --user skopeo skopeo:latest copy docker://docker.io/library/mysql:5.7.41 docker://ttl.sh/testimg:1h
done
```

### Describe the results you received

One would expect, that the second time Podman will discover the existance of the layers upstream, but it does not and uploads every layer again.

Podman or Buildah:
```
Copying blob 2ec521688c56 [===>----------------------------------] 4.7MiB / 48.1MiB
Copying blob 3e6a5b12e1de [================>---------------------] 11.0MiB / 24.4MiB
Copying blob c9bd281f4600 [=========>----------------------------] 12.0MiB / 46.2MiB
...
```

Skopeo:
```
Copying blob xxx skipped: **already exists**
Copying blob xxx skipped: **already exists**
...
```

### Describe the results you expected

Like Skopeo, Podman and Buildah should be able to detect the upstream layer exists and skip the upload

### podman info output

```yaml
arch: amd64
  buildahVersion: 1.29.0
  cgroupControllers:
  - memory
  - pids
  cgroupManager: cgroupfs
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.7-2.fc37.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: '
  cpuUtilization:
    idlePercent: 78.63
    systemPercent: 4.38
    userPercent: 16.99
  cpus: 6
  distribution:
    distribution: fedora
    variant: container
    version: "37"
  eventLogger: file
  hostname: 84f5bd04a698
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 0
      size: 1
    uidmap:
    - container_id: 0
      host_id: 0
      size: 1
  kernel: 5.19.0-35-generic
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 5614276608
  memTotal: 33232465920
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.8.1-1.fc37.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.1
      commit: f8a096be060b22ccd3d5f3ebe44108517fbf6c30
      rundir: /run/user/0/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  remoteSocket:
    path: /run/user/0/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-8.fc37.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 2147479552
  swapTotal: 2147479552
  uptime: 8h 18m 6.00s (Approximately 0.33 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /root/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.imagestore: /var/lib/shared
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.9-6.fc37.x86_64
      Version: |-
        fusermount3 version: 3.10.5
        fuse-overlayfs: version 1.9
        FUSE library version 3.10.5
        using FUSE kernel interface version 7.31
    overlay.mountopt: nodev,fsync=0
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 250905399296
  graphRootUsed: 24171679744
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /run/containers/storage
  transientStore: false
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.4.2
  Built: 1677669779
  BuiltTime: Wed Mar  1 11:22:59 2023
  GitCommit: ""
  GoVersion: go1.19.6
  Os: linux
  OsArch: linux/amd64
  Version: 4.4.2
```
```


### Podman in a container

Yes

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by flouthoc** [comment]
I think https://github.com/containers/image/pull/1645 should resolve this, but its on a low priority. I'll get back to it.

**Comment by BhawaniSingh** [comment]
@flouthoc https://github.com/containers/image/pull/1645 is merged and I'm still seeing this issue with podman 5

**Comment by flouthoc** [comment]
> [@flouthoc](https://github.com/flouthoc) [containers/image#1645](https://github.com/containers/image/pull/1645) is merged and I'm still seeing this issue with podman 5

Hi Could you please share a reproducer, as far as I remember we merged a test for this in CI. If you can share a small reproducer we can test if any bug went through.

**Comment by BhawaniSingh** [comment]
Sorry for the late reply

Let me explain what I'm doing. I'm using aws ecr and running rootful podman in CI
On first build podman builds the image using dockerfile, and pushes layers (amd image) to aws ecr, everything works as expected
If I re-ran the same build again on different CI agent, podman again pushes all layers to aws ecr.

This is problematic as image size is too big. In docker, I didn't face any problem, docker is able to detect the image is upload to aws. I thought it may be because podman compresses layers before pushing but I added `--disable-compression=false` to enable compression during build and got the same result


However, if I share the storage among builds (`/var/lib/containers/` folder), podman detects the layers are present in aws ecr and doesn't push any layer to ecr. (May be because of `blob-info-cache-v1.sqlite` is shared between builds)

I also use `--format=docker` while building the container image.
