### ISSUE TITLE
Broken SSL in the nested amd64 containers on Mac M1 inside arm64 container

### ISSUE THREAD

**Issue by sasha-alias** [containers/podman#18301]
### Issue Description

On the Mac with M1 chip a nested amd64 podman (or buildah) container inside the arm64 podman container has broken SSL. This makes it impossible to build amd64 images on the arm64 machines.

### Steps to reproduce the issue

Steps to reproduce the issue

1. On Mac with M1 chip run the command 
```bash
podman run --platform linux/arm64/v8 --privileged --rm quay.io/podman/stable podman run --platform linux/amd64 --privileged ubi8 yum update -y
```

### Describe the results you received

Output:
```bash
Resolved "ubi8" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull registry.access.redhat.com/ubi8:latest...
Getting image source signatures
Checking if image destination supports signatures
Copying blob sha256:6208c5a2e205726f3a2cd42a392c5e4f05256850d13197a711000c4021ede87b
Copying config sha256:768688a189716f9aef8d33a9eef4209f57dc2e66e9cb5fc3b8862940f314b9bc
Writing manifest to image destination
Storing signatures
Updating Subscription Management repositories.
Unable to read consumer identity

This system is not registered with an entitlement server. You can use subscription-manager to register.

Red Hat Universal Base Image 8 (RPMs) - BaseOS  0.0  B/s |   0  B     00:00
Errors during downloading metadata for repository 'ubi-8-baseos-rpms':
  - Curl error (35): SSL connect error for https://cdn-ubi.redhat.com/content/public/ubi/dist/ubi8/8/x86_64/baseos/os/repodata/repomd.xml [error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding]
Error: Failed to download metadata for repo 'ubi-8-baseos-rpms': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```

The `yum update` command inside the nested amd64 container is failed due to broken SSL.

### Describe the results you expected

If we run the same with the nested arm64 container it works fine:

```bash
podman run --platform linux/arm64/v8 --privileged --rm quay.io/podman/stable podman run --platform linux/arm64/v8 --privileged ubi8 yum update -y
Resolved "ubi8" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull registry.access.redhat.com/ubi8:latest...
Getting image source signatures
Checking if image destination supports signatures
Copying blob sha256:0abb68531ec6cd91f887b3384722ee0c64e3412cddfaa0e16f33bd4ec53cbd0f
Copying config sha256:f867900263f9f313ff5f796da097647e93c37adeba9833133ea0955e3edbf3e8
Writing manifest to image destination
Storing signatures
Updating Subscription Management repositories.
Unable to read consumer identity

This system is not registered with an entitlement server. You can use subscription-manager to register.

Red Hat Universal Base Image 8 (RPMs) - BaseOS  701 kB/s | 609 kB     00:00
Red Hat Universal Base Image 8 (RPMs) - AppStre  12 MB/s | 2.9 MB     00:00
Red Hat Universal Base Image 8 (RPMs) - CodeRea  33 kB/s |  24 kB     00:00
Dependencies resolved.
================================================================================
 Package          Architecture Version             Repository              Size
================================================================================
Upgrading:
 libsemanage      aarch64      2.9-9.el8_6         ubi-8-baseos-rpms      164 k
 tzdata           noarch       2023c-1.el8         ubi-8-baseos-rpms      477 k

Transaction Summary
================================================================================
Upgrade  2 Packages

Total download size: 640 k
Downloading Packages:
(1/2): libsemanage-2.9-9.el8_6.aarch64.rpm      3.2 MB/s | 164 kB     00:00
(2/2): tzdata-2023c-1.el8.noarch.rpm            6.6 MB/s | 477 kB     00:00
--------------------------------------------------------------------------------
Total                                           8.2 MB/s | 640 kB     00:00
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                        1/1
  Upgrading        : libsemanage-2.9-9.el8_6.aarch64                        1/4
  Upgrading        : tzdata-2023c-1.el8.noarch                              2/4
  Cleanup          : tzdata-2022g-1.el8.noarch                              3/4
  Cleanup          : libsemanage-2.9-9.el8.aarch64                          4/4
  Running scriptlet: libsemanage-2.9-9.el8.aarch64                          4/4
  Verifying        : tzdata-2023c-1.el8.noarch                              1/4
  Verifying        : tzdata-2022g-1.el8.noarch                              2/4
  Verifying        : libsemanage-2.9-9.el8_6.aarch64                        3/4
  Verifying        : libsemanage-2.9-9.el8.aarch64                          4/4
Installed products updated.

Upgraded:
  libsemanage-2.9-9.el8_6.aarch64           tzdata-2023c-1.el8.noarch

Complete!
```

### podman info output

```yaml
host:
  arch: arm64
  buildahVersion: 1.29.0
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.7-2.fc38.aarch64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: '
  cpuUtilization:
    idlePercent: 97.52
    systemPercent: 0.69
    userPercent: 1.79
  cpus: 2
  databaseBackend: ""
  distribution:
    distribution: fedora
    variant: coreos
    version: "38"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
    uidmap:
    - container_id: 0
      host_id: 502
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
  kernel: 6.2.9-300.fc38.aarch64
  linkmode: dynamic
  logDriver: journald
  memFree: 6419742720
  memTotal: 8300720128
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.8.3-2.fc38.aarch64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.3
      commit: 59f2beb7efb0d35611d5818fd0311883676f6f7e
      rundir: /run/user/502/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/502/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-12.fc38.aarch64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 0h 51m 24.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /var/home/core/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/core/.local/share/containers/storage
  graphRootAllocated: 106769133568
  graphRootUsed: 5096120320
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 7
  runRoot: /run/user/502/containers
  transientStore: false
  volumePath: /var/home/core/.local/share/containers/storage/volumes
version:
  APIVersion: 4.4.4
  Built: 1680521336
  BuiltTime: Mon Apr  3 13:28:56 2023
  GitCommit: ""
  GoVersion: go1.20.1
  Os: linux
  OsArch: linux/arm64
  Version: 4.4.4
```

### Podman in a container

Yes

### Privileged Or Rootless

Privileged

### Upstream Latest Release

Yes

**Comment by Luap99** [comment]
Yes this looks like a regression qemu-user-static, there isn't really anything we can do about it.
So far you can do `podman machine init --image stable` (#18280 and #18271) but the stable coreos stream will also receive the update at some point. I think it is usually two weeks behind.

cc @baude @ashley-cui

**Comment by ReToCode** [comment]
Thank you for the feedback. `podman machine init --image stable` does help for now 👍 
So let's hope this gets sorted out before the changes hit the stable channel then.

**Comment by sasha-alias** [comment]
I was able to init the machine from one of the previous images and install qemu-user-static on it:

```
pod machine init --image-path https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/37.20230122.3.0/aarch64/fedora-coreos-37.20230122.3.0-qemu.aarch64.qcow2.xz
podman machine start
podman machine ssh sudo rpm-ostree install qemu-user-static
podman machine stop
podman machine start
```
The working version there is: `qemu-user-static-7.0.0-15.fc37.aarch64`

**Comment by nastacio** [comment]
> So far you can do `podman machine init --image stable`

FWIW, on my local installation of podman 4.5.0 on macOS Ventura 13.3.1, the parameter was `--image-path` instead of `--image`

**Comment by zeha** [comment]
Given this is apparently fixed in qemu-stable 7.2.2, could we get that version or just the commit fixing this specific bug applied to qemu-user-static?
Thanks!

**Comment by ashley-cui** [comment]
Podman depends on the latest qemu, and the most recent qemu version is 8.0. If you go and grab the updated qemu, this should work correctly. Closing as completed.

**Comment by Nonary** [comment]
I installed latest podman (4.5.0), and even went through and removed all older versions of qemu and still have this issue. Not sure what else we are supposed to do to fix this issue, other than using the stable image like suggested earlier. I also uninstalled podman desktop just to make sure that wasn't potentially impacting anything.

Works fine when using the stable image workaround, at least for now.

**Comment by Luap99** [comment]
It all depends on the qemu-user-static version inside the VM image which is just a standard fedora coreos image. 

So far fedora 38 uses qemu v7.2.1 (https://src.fedoraproject.org/rpms/qemu), so someone would need to ask the fedora package maintainer to update that package to 7.2.2 assuming that the prior comment is correct that it was fixed there.

**Comment by bbbush** [comment]
it feels like the situation of OpenJDK in Docker Hub -- it takes a long time for a fix to be approved in the Debian distribution and then for the docker image to be pushed. The major version change (qemu 8.x) might be difficult to be approved for F38, while it is uncertain whether 7.2.x contains the fix. Is there a ticket in either RHBZ or CoreOS to follow? thanks!

**Comment by zeha** [comment]
What we still need is a Fedora 38 CoreOS update that includes qemu 7.2.1. Its already in F38, but apparently not in a stamped CoreOS ostree update.
