### ISSUE TITLE
Another permission problem for /dev/ttyACM0 device

### ISSUE THREAD

**Issue by aacebedo** [containers/podman#20281]
### Issue Description

I am unable to mount a USB device (Black Magic Probe) appearing as `/dev/ttyACM0` in a rootless podman container with correct permissions.
I already tried some options found in previous issues with no effect.
On the host the permissions are:
```
Permissions  Size User Group   Date Modified Name
crw-rw----  166,0 root dialout  5 Oct 21:25  /dev/ttyACM0
```
in a container started with:
```
podman run --rm -it --group-add=keep-groups --userns=keep-id --security-opt label=disable --device=/dev/ttyACM0  ubuntu:latest /bin/bash
```
the permissions are:
```
crw-rw---- 1 nobody nogroup 166, 0 Oct  5 19:25 /dev/ttyACM0
```
and then I cannot access the device.
I checked I was running `crun` (for the group-add argument) but did not find the reason it is not working.

### Steps to reproduce the issue

Steps to reproduce the issue
1. plug the device
2. check its permission on host with `ls -lag /dev/ttyACM0`, permission are correct
3. start a container with the following command `podman run --rm -it --group-add=keep-groups --userns=keep-id --security-opt label=disable --device=/dev/ttyACM0  ubuntu:latest /bin/bash`
4. check the permission again, permission are incorrect.

### Describe the results you received

Result of permissions in the container:
```
crw-rw---- 1 nobody nogroup 166, 0 Oct  5 19:25 /dev/ttyACM0
```

### Describe the results you expected

The group and id shall have been applied and the permissions should be:
```
crw-rw----  166,0 root dialout  5 Oct 21:25  /dev/ttyACM0
```

### podman info output

```yaml
❯ podman info
host:
  arch: amd64
  buildahVersion: 1.31.2
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: Unknown
    path: /nix/store/75mhm9hvpx3bp20wrglmp449qlx1bx10-conmon-2.1.8/bin/conmon
    version: 'conmon version 2.1.8, commit: '
  cpuUtilization:
    idlePercent: 90
    systemPercent: 1.65
    userPercent: 8.35
  cpus: 12
  databaseBackend: boltdb
  distribution:
    codename: tapir
    distribution: nixos
    version: "23.11"
  eventLogger: journald
  freeLocks: 2001
  hostname:
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 100
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 6.5.5-xanmod1
  linkmode: dynamic
  logDriver: journald
  memFree: 6394200064
  memTotal: 16399126528
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: Unknown
      path: /nix/store/jpp28b0bqsi00n0n0c1wm2856j34ijl3-podman-4.6.2/libexec/podman/aardvark-dns
      version: aardvark-dns 1.7.0
    package: Unknown
    path: /nix/store/jpp28b0bqsi00n0n0c1wm2856j34ijl3-podman-4.6.2/libexec/podman/netavark
    version: netavark 1.7.0
  ociRuntime:
    name: crun
    package: Unknown
    path: /nix/store/xsv2zk2c8zn5h8xla019fdbqmjp4dg16-crun-1.9.2/bin/crun
    version: |-
      crun version 1.9.2
      commit: 1.9.2
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  pasta:
    executable: ""
    package: ""
    version: ""
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: ""
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /nix/store/jpp28b0bqsi00n0n0c1wm2856j34ijl3-podman-4.6.2/libexec/podman/slirp4netns
    package: Unknown
    version: |-
      slirp4netns version 1.2.1
      commit: 09e31e92fa3d2a1d3ca261adaeb012c8d75a8194
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.4
  swapFree: 15999168512
  swapTotal: 15999168512
  uptime: 0h 25m 13.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/aacebedo/.config/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 1
    stopped: 1
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/aacebedo/.local/share/containers/storage
  graphRootAllocated: 486653558784
  graphRootUsed: 415883825152
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 108
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/aacebedo/.local/share/containers/storage/volumes
version:
  APIVersion: 4.6.2
  Built: 315532800
  BuiltTime: Tue Jan  1 01:00:00 1980
  GitCommit: ""
  GoVersion: go1.20.8
  Os: linux
  OsArch: linux/amd64
  Version: 4.6.2
```
```


### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by flouthoc** [comment]
This behaves same in `runc` so this is not a OCI runtime issue, afaics `mknod` is not allowed in rootless setups so `podman` mimics the device using a `bind-mount` and it does not sets the `group` and `user` correctly there.

I don't know if this can be solved for rootless setups or is this the expected behavior  @giuseppe any hints ?

**Comment by giuseppe** [comment]
This is expected and we can't do anything from a rootless environment. An unprivileged user cannot create a device node

**Comment by rhatdan** [comment]
The Device should be accessible via the dialout group, since you leaked this into the container, as long as the user running Podman is in the dialout group?

**Comment by aacebedo** [comment]
@rhatdan On the host the user is in the dialout group and the access to the device is possible.

**Comment by aacebedo** [comment]
I wonder how #16925 has been solved as the container seems to be started by a non-privileged user (no mention of sudo in the tickets).
This seems to prevent using development containers for targets that need to be flashed or debugged with a probe.

**Comment by aacebedo** [comment]
For the record, access to the device works even if the permissions are reported as no-group with the option `--group-add=keep-groups`

**Comment by rhatdan** [comment]
Yes the Group is not defined within the user namespace of the container, but the main processes of the container still have the correct GID leaked into the container.  So they will have access but if the ls or other processes examine the device they will say that the group owner of the device is not defined within the container.

**Comment by aacebedo** [comment]
Thanks, @rhatdan, for the precision.

I am now facing a follow-up of my problem, the tool I am using to connect to the development environment is [devpod](https://github.com/loft-sh/devpod/). It creates a container with any kind of ssh agent inside it and then connect to it through ssh.

When I run the container directly with the `--group-add keep-id` I can see that the groups of the user contains "nogroup". However when I connect to the container through ssh with the same user, the "nogroup" group is not in the list anymore, and I cannot use gdb to access to the probe (permission denied).

I reproduced this behavior using a simple container based on `ubuntu:latest` In which I installed `openssh-server`. If I use `podman exec -ti -u root` to access to the container I see root user belonging to `nogroup`. I can access the device. If I login on the sshd running inside the same containe, the same user (root) does not belong to the `nogroup` anymore, and I can't access to the device neither. 

Is there any way to have the same groups applied or does it gets its groups through the ssh daemon and so it does not see the groups leaking from the host?

**Comment by rhatdan** [comment]
sshd is not going to put the user account into a leaked group from the outside, If sshd sees the groupname inside of the container, it is going to be a different UID then the leaked one.  I don't see how you can make this work in rootless mode, without having access to the GID within the user namespace.

@giuseppe do  you agree?
