### ISSUE TITLE
podman system high CPU usage when using Docker CLI

### ISSUE THREAD

**Issue by piax93** [containers/podman#20681]
### Issue Description

Hi there. We have been observing high CPU usage (between 1 and 1.5 cores) from the `podman system service` process, even when running no particularly intensive workload.
We tried to debug whether we were using some anomalous options when running the containers, and finally I managed to figure out that the root cause seem to be the usage of the Docker CLI to interact with the containerizer socket. 

### Steps to reproduce the issue

Steps to reproduce the issue
1. Use Ubuntu 22.04, and install podman and the docker CLI from Canonical upstream (should be v3.4.4 and v20.10.12 respectively)
2. Start the podman system service.
3. Open a couple terminal windows, one with htop sorted by CPU usage
4. Run `DOCKER_HOST=unix://$XDG_RUNTIME_DIR/podman/podman.sock docker run --rm ubuntu:jammy sleep 10`, and observe high CPU usage from the podman system process
5. Run `podman run --remote --rm docker.io/ubuntu:jammy sleep 10`, and observe no CPU usage anomaly

### Describe the results you received

The APIs invoked by the Docker CLI cause higher CPU usage.

### Describe the results you expected

I would expect the Podman and the Docker CLI to have similar outcomes when interacting with the podman service socket.

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - cpuset
  - cpu
  - memory
  - hugetlb
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.25, commit: unknown'
  cpus: 16
  distribution:
    codename: jammy
    distribution: ubuntu
    version: "22.04"
  eventLogger: journald
  hostname: xxx
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 100
      size: 1
    - container_id: 1
      host_id: 27625120
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 3418
      size: 1
    - container_id: 1
      host_id: 27625120
      size: 65536
  kernel: 6.2.0-1014-aws
  linkmode: dynamic
  logDriver: journald
  memFree: 6138155008
  memTotal: 132932300800
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/3418/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.6.1
  swapFree: 54206345216
  swapTotal: 54219452416
  uptime: 224h 48m 39.22s (Approximately 9.33 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries: {}
store:
  configFile: /nail/home/mpiano/.config/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 1
    stopped: 1
  graphDriverName: overlay
  graphOptions:
    overlay.imagestore: /var/ucs/3418/b/
  graphRoot: /var/ucs/3418/p
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 580
  runRoot: /run/user/3418/containers
  volumePath: /var/ucs/3418/p/volumes
version:
  APIVersion: 3.4.4
  Built: 0
  BuiltTime: Wed Dec 31 16:00:00 1969
  GitCommit: ""
  GoVersion: go1.18.1
  OsArch: linux/amd64
  Version: 3.4.4
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional information

I dumped the API calls going through the socket for a `docker/podman run ...` to get an idea of the differences

```
# PODMAN CLI

> 2023/11/13 08:21:59.833114  length=78 from=0 to=77
GET /v3.4.4/libpod/_ping HTTP/1.1\r

> 2023/11/13 08:22:00.373817  length=5460 from=0 to=5459
POST /v3.4.4/libpod/images/pull?alltags=false&arch=&authfile=&os=&password=&policy=missing&quiet=false&reference=docker.io/ubuntu&username=&variant= HTTP/1.1\r

> 2023/11/13 08:22:00.426710  length=1026 from=0 to=1025
POST /v3.4.4/libpod/containers/create HTTP/1.1\r
{"command":["bash"],"httpproxy":true,"terminal":true,"stdin":true,"annotations":{"io.kubernetes.cri-o.TTY":"true"},"stop_timeout":10,"log_configuration":{},"raw_image_name":"docker.io/ubuntu:jammy","systemd":"true","sdnotifyMode":"container","pidns":{},"utsns":{},"remove":true,"containerCreateCommand":["podman","--remote","run","--rm","-it","docker.io/ubuntu:jammy","bash"],"init_container_type":"","image":"docker.io/ubuntu:jammy","image_volume_mode":"anonymous","ipcns":{},"volatile":true,"seccomp_policy":"default","userns":{},"idmappings":{"HostUIDMapping":true,"HostGIDMapping":true,"UIDMap":null,"GIDMap":null,"AutoUserNs":false,"AutoUserNsOpts":{"Size":0,"InitialSize":0,"PasswdFile":"","GroupFile":"","AdditionalUIDMappings":null,"AdditionalGIDMappings":null}},"umask":"0022","cgroupns":{},"aliases":null,"netns":{"nsmode":"slirp4netns"},"oom_score_adj":0}

> 2023/11/13 08:22:00.467104  length=164 from=1026 to=1189
GET /v3.4.4/libpod/containers/7df74c08a682129b58fdc835e700802aaa212bf6bd9a1015ec0a20917b5bd5e5/json?size=false HTTP/1.1\r

> 2023/11/13 08:22:00.476425  length=334 from=0 to=333
POST /v3.4.4/libpod/containers/7df74c08a682129b58fdc835e700802aaa212bf6bd9a1015ec0a20917b5bd5e5/attach?detachKeys=ctrl-p%2Cctrl-q&detachkeys=ctrl-p%2Cctrl-q&stderr=true&stdin=true&stdout=true&stream=true HTTP/1.1\r

> 2023/11/13 08:22:00.781571  length=222 from=0 to=221
POST /v3.4.4/libpod/containers/7df74c08a682129b58fdc835e700802aaa212bf6bd9a1015ec0a20917b5bd5e5/resize?h=37&running=true&w=181 HTTP/1.1\r

> 2023/11/13 08:22:00.782604  length=224 from=222 to=445
POST /v3.4.4/libpod/containers/7df74c08a682129b58fdc835e700802aaa212bf6bd9a1015ec0a20917b5bd5e5/start?detachkeys=ctrl-p%2Cctrl-q HTTP/1.1\r

> 2023/11/13 08:22:01.631690  length=196 from=446 to=641
POST /v3.4.4/libpod/containers/7df74c08a682129b58fdc835e700802aaa212bf6bd9a1015ec0a20917b5bd5e5/wait HTTP/1.1\r

> 2023/11/13 08:22:01.674825  length=205 from=642 to=846
POST /v3.4.4/libpod/containers/7df74c08a682129b58fdc835e700802aaa212bf6bd9a1015ec0a20917b5bd5e5/shouldrestart HTTP/1.1\r

> 2023/11/13 08:22:01.676121  length=199 from=0 to=198
DELETE /v3.4.4/libpod/containers/7df74c08a682129b58fdc835e700802aaa212bf6bd9a1015ec0a20917b5bd5e5?force=false&volumes=true HTTP/1.1\r


# DOCKER CLI

> 2023/11/13 08:22:08.336787  length=82 from=0 to=81
HEAD /_ping HTTP/1.1\r

> 2023/11/13 08:22:08.529380  length=1714 from=82 to=1795
POST /v1.40/containers/create HTTP/1.1\r
{"Hostname":"","Domainname":"","User":"","AttachStdin":true,"AttachStdout":true,"AttachStderr":true,"Tty":true,"OpenStdin":true,"StdinOnce":true,"Env":null,"Cmd":["bash"],"Image":"ubuntu:jammy","Volumes":{},"WorkingDir":"","Entrypoint":null,"OnBuild":null,"Labels":{},"HostConfig":{"Binds":null,"ContainerIDFile":"","LogConfig":{"Type":"","Config":{}},"NetworkMode":"default","PortBindings":{},"RestartPolicy":{"Name":"no","MaximumRetryCount":0},"AutoRemove":true,"VolumeDriver":"","VolumesFrom":null,"CapAdd":null,"CapDrop":null,"CgroupnsMode":"","Dns":[],"DnsOptions":[],"DnsSearch":[],"ExtraHosts":null,"GroupAdd":null,"IpcMode":"","Cgroup":"","Links":null,"OomScoreAdj":0,"PidMode":"","Privileged":false,"PublishAllPorts":false,"ReadonlyRootfs":false,"SecurityOpt":null,"UTSMode":"","UsernsMode":"","ShmSize":0,"ConsoleSize":[0,0],"Isolation":"","CpuShares":0,"Memory":0,"NanoCpus":0,"CgroupParent":"","BlkioWeight":0,"BlkioWeightDevice":[],"BlkioDeviceReadBps":null,"BlkioDeviceWriteBps":null,"BlkioDeviceReadIOps":null,"BlkioDeviceWriteIOps":null,"CpuPeriod":0,"CpuQuota":0,"CpuRealtimePeriod":0,"CpuRealtimeRuntime":0,"CpusetCpus":"","CpusetMems":"","Devices":[],"DeviceCgroupRules":null,"DeviceRequests":null,"KernelMemory":0,"KernelMemoryTCP":0,"MemoryReservation":0,"MemorySwap":0,"MemorySwappiness":-1,"OomKillDisable":false,"PidsLimit":0,"Ulimits":null,"CpuCount":0,"CpuPercent":0,"IOMaximumIOps":0,"IOMaximumBandwidth":0,"MaskedPaths":null,"ReadonlyPaths":null},"NetworkingConfig":{"EndpointsConfig":{}},"Platform":null}

> 2023/11/13 08:22:08.637392  length=274 from=0 to=273
POST /v1.40/containers/92f315bc6031b5884826be839af3ec54be1042c7da1fb5a2352bfdee9eb4555e/attach?stderr=1&stdin=1&stdout=1&stream=1 HTTP/1.1\r

> 2023/11/13 08:22:09.018767  length=226 from=1796 to=2021
POST /v1.40/containers/92f315bc6031b5884826be839af3ec54be1042c7da1fb5a2352bfdee9eb4555e/wait?condition=removed HTTP/1.1\r

> 2023/11/13 08:22:09.020459  length=209 from=0 to=208
POST /v1.40/containers/92f315bc6031b5884826be839af3ec54be1042c7da1fb5a2352bfdee9eb4555e/start HTTP/1.1\r

> 2023/11/13 08:22:09.030410  length=221 from=209 to=429
POST /v1.40/containers/92f315bc6031b5884826be839af3ec54be1042c7da1fb5a2352bfdee9eb4555e/resize?h=37&w=181 HTTP/1.1\r
```

**Comment by Luap99** [comment]
Please test this with the lastest podman version (4.7). We do not support older versions upstream and 3.4.4 is very old.
I also cannot reproduce this with your command against the latest version so I assume it was fixed already.

**Comment by piax93** [comment]
For anyone still encountering this issue on podman versions provided with the current Ubuntu releases, I did some more debugging myself, and this is the patch that solves it -> https://github.com/containers/podman/pull/18149
