### ISSUE TITLE
Table keyword not working in podman ps --format

### ISSUE THREAD

**Issue by ozoder** [containers/podman#2221]
**Is this a BUG REPORT or FEATURE REQUEST?**

/kind bug

**Description**

Since podman 0.11.1, "table" keyword cannot be specified in the --format flag when running `podman ps`. On the other hand, this keyword still works in `podman images`. Without it, there is no way to print the headers when using --format flag in `podman ps` the same way they are printed in `podman images`.

**Steps to reproduce the issue:**

1. `podman ps --all --format "table {{.ID}} {{.Created}}"`

2. `podman images --format "table {{.ID}} {{.Created}}"`

3. compare the output

**Describe the results you received:**

```
table f48c535ed0ba 12 minutes ago
```

vs.

```
IMAGE ID       CREATED
45575655f406   4 days ago
516c5114e6d5   4 months ago
```

**Describe the results you expected:**

```
CONTAINER ID   CREATED     
f48c535ed0ba   12 minutes ago
```

**Additional information you deem important (e.g. issue happens only occasionally):**

Additionally, there is an inconsistency between output of `podman images` and `podman ps` when there are no images/containers, as `podman ps` prints out the headers and `podman images` doesn't:

```
[localhost@localhost ~]$ podman ps
CONTAINER ID  IMAGE  COMMAND  CREATED  STATUS  PORTS  NAMES
```

```
[localhost@localhost ~]$ podman images
```

**Output of `podman version`:**

```
Version:       0.11.2-dev
Go Version:    go1.11.2
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
host:
  BuildahVersion: 1.5-dev
  Conmon:
    package: podman-0.11.2-11.dev.git6b8f89d.fc30.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 7bcc544681086afc5edc12a924db51dd909f0b7a'
  Distribution:
    distribution: fedora
    version: "30"
  MemFree: 2800603136
  MemTotal: 4107485184
  OCIRuntime:
    package: runc-1.0.0-61.dev.git4932620.fc30.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc6+dev
      commit: 39177935192ea027e5e232dff829cf015f9eb07c
      spec: 1.0.1-dev
  SwapFree: 2147479552
  SwapTotal: 2147479552
  arch: amd64
  cpus: 3
  hostname: localhost.localdomain
  kernel: 4.20.0-0.rc4.git2.1.fc30.x86_64
  os: linux
  rootless: true
  uptime: 39m 2.12s
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  GraphRoot: /var/home/redhat/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
  ImageStore:
    number: 2
  RunRoot: /run/user/1000
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Fedora Silverblue Rawhide running in Virtual Machine Manager

**Comment by mheon** [comment]
@baude PTAL - potentially related to the output rework on ps?

**Comment by mheon** [comment]
@baude This is fixed via #2232 right?

Closing, reopen if it's not

**Comment by orctom** [comment]
Still having the issue on mac
![image](https://user-images.githubusercontent.com/128631/133772063-2f6e18f6-0735-482f-8cc5-cb44ee8192c2.png)

```
▶ podman version
Client:
Version:      3.3.1
API Version:  3.3.1
Go Version:   go1.17
Built:        Tue Aug 31 03:15:26 2021
OS/Arch:      darwin/amd64

Server:
Version:      3.3.1
API Version:  3.3.1
Go Version:   go1.16.6
Built:        Tue Aug 31 04:46:36 2021
OS/Arch:      linux/amd64
```

**Comment by mheon** [comment]
This issue is two years old. Please open a new issue.
