### ISSUE TITLE
pasta system tests fail when I'm VPNed: Couldn't set IPv6 route(s) in guest: EINVAL

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#23549]
Been happening for as long as I can remember; it's only now that I tracked it down to being VPNed:
```console
$ ./bats --rootless 505:"default route assignment"
--------------------------------------------------
$ bats  --filter default route assignment test/system/505-networking-pasta.bats
505-networking-pasta.bats
 ✗ [505] IPv4 default route assignment
   tags: ci:parallel
   (from function `bail-now' in file test/system/helpers.bash, line 189,
    from function `die' in file test/system/helpers.bash, line 937,
    from function `run_podman' in file test/system/helpers.bash, line 539,
    in test file test/system/505-networking-pasta.bats, line 347)
     `run_podman run --rm --net=pasta:-a,192.0.2.2,-g,192.0.2.1 $IMAGE \' failed
   
   [06:09:23.178142254] $ bin/podman info --format {{.Host.Pasta.Executable}}
   [06:09:23.277041337] /usr/bin/pasta
   
   [06:09:23.289606709] $ bin/podman run --rm --net=pasta:-a,192.0.2.2,-g,192.0.2.1 quay.io/libpod/testimage:20240123 ip -j -4 route show
   [06:09:23.390616677] Error: pasta failed with exit code 1:
   Couldn't set IPv6 route(s) in guest: Invalid argument
   [06:09:23.393523945] [ rc=126 (** EXPECTED 0 **) ]
   #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
   #| FAIL: exit code is 126; expected 0
   #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   # [teardown]
 - [505] IPv6 default route assignment (skipped: IPv6 not routable on the host)

2 tests, 1 failure, 1 skipped
```
Also fails the `host.containers.internal` test. As soon as I disconnect, all 505 tests pass.

**Comment by Luap99** [comment]
@edsantiago Sorry I left you out of the loop there. I noticed this too locally when connected to the Red Hat VPN and reported this to @sbrivio-rh which was fixed in https://passt.top/passt/commit/?id=fbb0c9523e416a5c1ecf42287d867fc799fbf0f9

The fix will be in the next version

**Comment by edsantiago** [comment]
Followup: "next version" apparently means "`> 20240806`". (As in, 0806 does not fix it). Koji is down so I can't see if there are any new builds in the pipeline.

**Comment by sbrivio-rh** [comment]
> Followup: "next version" apparently means "`> 20240806`". (As in, 0806 does not fix it).

Right... it's exactly one commit later:
```
$ git describe --tags fbb0c9523e416a5c1ecf42287d867fc799fbf0f9
2024_08_06.ee36266-1-gfbb0c95
```

> Koji is down so I can't see if there are any new builds in the pipeline.

Not at the moment. In a couple of weeks perhaps? Unless you need it sooner?

**Comment by edsantiago** [comment]
I don't need it. It's just a minor hassle to hand-edit 505.bats and add the two `skips` when running tests. Knowing that it'll be a few weeks has given me the motivation to automate it.

**Comment by sbrivio-rh** [comment]
> > Koji is down so I can't see if there are any new builds in the pipeline.
> 
> Not at the moment. In a couple of weeks perhaps? Unless you need it sooner?

And instead I just made a new [release](https://archives.passt.top/passt-dev/20240814143016.1ced1eeb@elisabeth/) (oops) because of a nasty issue @dgibson just fixed.
