### ISSUE TITLE
quadlet podman-systemd.unit failing to recognize Network=$name.container format for .container

### ISSUE THREAD

**Issue by binarywaddle** [containers/podman#25174]
### Issue Description

Hello, I'm trying to run Immich with Tailscale via rootless podman quadlets in Fedora CoreOS Stable stream.
I'm having a weird issue and want to see if I am missing anything as I've been looking over the documentation. For some reason systemd is not recognizing the `.container` file when I set `Network=tailscale.container`. I'm following the documentation which states

> Another special case is that if the name ends with .container, the container will reuse the network stack of another container created by $name.container. The generated systemd service contains a dependency on $name.service.

Podman version
```core@immich03:~/quadlets/user$ podman -v
podman version 5.3.1
```

.container files.
```
[Unit]
Description=Immich Server
Requires=immich-redis.service immich-postgres.service
After=immich-redis.service immich-postgres.service

[Container]
ContainerName=immich_server
Image=ghcr.io/imagegenius/immich:noml
AutoUpdate=registry
EnvironmentFile=/home/core/data/conf/immich_server.env
Network=tailscale.container
NetworkAlias=immich_server
Volume=immich_server-config:/config
Volume=/var/mnt/immich/photos:/photos
Volume=/var/mnt/immich/libraries:/libraries

[Service]
Restart=always

[Install]
WantedBy=default.target
```

```
[Unit]
Description=Tailscale

[Container]
ContainerName=Tailscale
Image=docker.io/tailscale/tailscale:latest
AutoUpdate=registry
HostName=immich
Network=immich
NetworkAlias=tailscale
Volume=tailscale_data:/var/lib/tailscale
EnvironmentFile=/home/core/data/conf/tailscale.env
AddDevice=/dev/net/tun:/dev/net/tun
AddCapability=CAP_NET_ADMIN

[Service]
Restart=always
```

### Steps to reproduce the issue

Steps to reproduce the issue
1. Run CoreOS Stable in a VM
2. Try to run two containers via quadlets with one container reusing the network of another via specifying the `Network=$name.container` format
3. systemd fails to recognize the unit file.

### Describe the results you received

systemd is not recognizing the .container unit file to control services

Example showing 'Loaded: not-found' after running `systemctl --user daemon-reload`
```
core@immich03:~/quadlets/user$ systemctl --user status immich-server.service
× immich-server.service
     Loaded: not-found (Reason: Unit immich-server.service not found.)
     Active: failed (Result: exit-code) since Thu 2025-01-30 20:18:43 UTC; 22min ago
 Invocation: 7457bf4574184c92964b011cc8a4750f
   Main PID: 4681 (code=exited, status=125)
```

### Describe the results you expected

systemd recognizes the Network=tailscale.container options correctly and loads the unit

Example showing 'Loaded: loaded'

```
core@immich03:~/quadlets/user$ systemctl --user status immich-server.service
× immich-server.service - Immich Server
     Loaded: loaded (/var/home/core/.config/containers/systemd/immich-server.container; generated)
    Drop-In: /usr/lib/systemd/user/service.d
             └─10-timeout-abort.conf
     Active: failed (Result: exit-code) since Thu 2025-01-30 20:18:43 UTC; 20min ago
 Invocation: 7457bf4574184c92964b011cc8a4750f
   Main PID: 4681 (code=exited, status=125)
```

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.38.0
  cgroupControllers:
  - cpu
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.12-3.fc41.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.12, commit: '
  cpuUtilization:
    idlePercent: 99.77
    systemPercent: 0.13
    userPercent: 0.11
  cpus: 8
  databaseBackend: sqlite
  distribution:
    distribution: fedora
    variant: coreos
    version: "41"
  eventLogger: journald
  freeLocks: 2041
  hostname: immich03
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 524288
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 524288
      size: 65536
  kernel: 6.12.7-200.fc41.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 3307737088
  memTotal: 4085899264
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.13.1-1.fc41.x86_64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.13.1
    package: netavark-1.13.1-1.fc41.x86_64
    path: /usr/libexec/podman/netavark
    version: netavark 1.13.1
  ociRuntime:
    name: crun
    package: crun-1.19.1-1.fc41.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.19.1
      commit: 3e32a70c93f5aa5fea69b50256cca7fd4aa23c80
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20241211.g09478d5-1.fc41.x86_64
    version: |
      pasta 0^20241211.g09478d5-1.fc41.x86_64-pasta
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.3.1-1.fc41.x86_64
    version: |-
      slirp4netns version 1.3.1
      commit: e5e368c4f5db6ae75c2fce786e31eef9da6bf236
      libslirp: 4.8.0
      SLIRP_CONFIG_VERSION_MAX: 5
      libseccomp: 2.5.5
  swapFree: 2042621952
  swapTotal: 2042621952
  uptime: 1h 2m 43.00s (Approximately 0.04 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
store:
  configFile: /var/home/core/.config/containers/storage.conf
  containerStore:
    number: 3
    paused: 0
    running: 3
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/core/.local/share/containers/storage
  graphRootAllocated: 42881482752
  graphRootUsed: 4788629504
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 5
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /var/home/core/.local/share/containers/storage/volumes
version:
  APIVersion: 5.3.1
  Built: 1732147200
  BuiltTime: Thu Nov 21 00:00:00 2024
  GitCommit: ""
  GoVersion: go1.23.3
  Os: linux
  OsArch: linux/amd64
  Version: 5.3.1
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by ygalblum** [comment]
I've just tried the same with `5.3.1` and it seems to work for me:
```
○ immich-server.service - Immich Server
     Loaded: loaded (/home/yblum.linux/.config/containers/systemd/25174/immich-server.container; generated)
    Drop-In: /usr/lib/systemd/user/service.d
             └─10-timeout-abort.conf
     Active: inactive (dead)
```

A few question:
1. I assume the name of the first `.container` file is `immich-server.container` because you expect the service unit to be `immich-server.service`. Is that true?
2. What is the name of the second `.container`? In order for it to work, it must be the same name reference to. That it `tailscale.container` (or update the reference)
3. Can you please run `/home/yblum.linux/work/podman/bin/quadlet --user --dryrun` and check that there are no errors and that `immich-server.service` was in fact created?
4. If you have many Quadlet files you can also put the two in their own directory and set the environment variable `QUADLET_UNIT_DIRS` when running the `dryrun`

**Comment by binarywaddle** [comment]
Hello thanks for helping. Sorry I forgot to add that output but yes the container is called `tailscale.container`. 

```
core@immich03:~/quadlets/user$ ll
total 16
-rw-r--r--. 1 core core 727 Jan 30 03:39 immich-postgres.container
-rw-r--r--. 1 core core 305 Jan 30 03:35 immich-redis.container
-rw-r--r--. 1 core core 526 Jan 30 20:41 immich-server.container
-rw-r--r--. 1 core core 365 Jan 30 19:41 tailscale.container
```

```
core@immich03:~/quadlets/user$ systemctl --user status tailscale.service
● tailscale.service - Tailscale
     Loaded: loaded (/var/home/core/.config/containers/systemd/tailscale.container; generated)
    Drop-In: /usr/lib/systemd/user/service.d
             └─10-timeout-abort.conf
     Active: active (running) since Fri 2025-01-31 04:47:18 UTC; 4s ago
 Invocation: 6eb64550a542442190f9dca154acf789
   Main PID: 9706 (conmon)
      Tasks: 25 (limit: 4507)
     Memory: 25.4M (peak: 31.2M)
        CPU: 490ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/tailscale.service
             ├─libpod-payload-45f0fe7ef8327afa83421a05e3720aebf2d79f05da1778b6ffac45eb9e29bc9e
             │ ├─9708 /usr/local/bin/containerboot
             │ └─9716 tailscaled --socket=/tmp/tailscaled.sock --statedir=/var/lib/tailscale --tun=userspace-ne>
             └─runtime
               └─9706 /usr/bin/conmon --api-version 1 -c 45f0fe7ef8327afa83421a05e3720aebf2d79f05da1778b6ffac45>
```
---tailscale.service---
[Unit]
Wants=podman-user-wait-network-online.service
After=podman-user-wait-network-online.service
Description=Tailscale
SourcePath=/var/home/core/.config/containers/systemd/tailscale.container
RequiresMountsFor=%t/containers

[X-Container]
ContainerName=Tailscale
Image=docker.io/tailscale/tailscale:latest
AutoUpdate=registry
HostName=immich
Network=immich
NetworkAlias=tailscale
Volume=tailscale_data:/var/lib/tailscale
EnvironmentFile=/home/core/data/conf/tailscale.env
AddDevice=/dev/net/tun:/dev/net/tun
AddCapability=CAP_NET_ADMIN

[Service]
Restart=always
Environment=PODMAN_SYSTEMD_UNIT=%n
KillMode=mixed
ExecStop=/usr/bin/podman rm -v -f -i --cidfile=%t/%N.cid
ExecStopPost=-/usr/bin/podman rm -v -f -i --cidfile=%t/%N.cid
Delegate=yes
Type=notify
NotifyAccess=all
SyslogIdentifier=%N
ExecStart=/usr/bin/podman run --name Tailscale --cidfile=%t/%N.cid --replace --rm --cgroups=split --hostname immich --network-alias tailscale --network immich --sdnotify=conmon -d --device /dev/net/tun:/dev/net/tun --cap-add cap_net_admin -v tailscale_data:/var/lib/tailscale --label io.containers.autoupdate=registry --env-file /home/core/data/conf/tailscale.env docker.io/tailscale/tailscale:latest

[Install]
WantedBy=default.target

quadlet-generator[10021]: converting "immich-server.container": cannot get the resource name of tailscale.container
```

**Comment by ygalblum** [comment]
Hi,

I accidentally tested with the wrong version (my build off of `main`) and this is why it worked for me. While this feature does exist in `v5.3.1`, this version has an issue that was resolved here: https://github.com/containers/podman/pull/24794. 

The root cause of the issue was the processing order and  the fix will be part of `v5.4.X`.

In the meanwhile what you can do is rename `tailscale.container` to make sure that it is processed before `immich-server.container` (e.g. `01-tailscale.container`) and update the dependency accordingly.

**Comment by Keyruu** [comment]
I do have the same issue but prefixing the container with 01 does not fix it for me.

**Comment by ygalblum** [comment]
> I do have the same issue but prefixing the container with 01 does not fix it for me.

This workaround also depends on where the files are located. Are the two in the same directory? 

In any case, keep in mind that this is just a trial-and-error workaround for an issue that was already resolved and just waiting to get released

**Comment by Keyruu** [comment]
Hmm okay, do you have an ETA on when that release is coming out?

**Comment by ygalblum** [comment]
> Hmm okay, do you have an ETA on when that release is coming out?

I don't know for sure. But rc-2 was already tagged for 5.4.0. So, I assume in the next few weeks (but, again, not sure)
