### ISSUE TITLE
Using nftables on a Windows WSL machine doesn't work

### ISSUE THREAD

**Issue by l0rd** [containers/podman#25201]
### Issue Description

After updating to Fedora 41 and configuring the machine in rootful mode, running a container returns a netavark error:

```log
# podman run hello
WARN[0000] Using cgroups-v1 which is deprecated in favor of cgroups-v2 with Podman v5 and will be removed in a future version. Set environment variable `PODMAN_IGNORE_CGROUPSV1_WARNING` to hide this warning.
internal:0:0-0: Error: Could not process rule: No such file or directory

internal:0:0-0: Error: Could not process rule: No such file or directory

Error: netavark: nftables error: nft did not return successfully while applying ruleset
```

### Steps to reproduce the issue

Steps to reproduce the issue
1. Build [a WSL image based on Fedora 41](https://github.com/containers/podman-machine-wsl-os/pull/13) (for testing, I have built and pushed one to `quay.io/mloriedo/machine-os-wsl:5.5-next`)
2. Init/Run a rootful machine using the Fedora 41 based image: 
```
> podman machine init --image docker://quay.io/mloriedo/machine-os-wsl:5.5-next
> podman machine set --rootful
> podman machine start
> podman run hello
```

### podman info output

```yaml
Podman built from main branch running on Windows 11 with WSL v2.4.9.0 and Kernel v5.15.167.4-1
```

### Additional information

Using a more recent version of the Kernel (v6.6.36) doesn't help.

Configuring podman to use iptables fixes the problem: 
```
[network]
firewall_driver="iptables"
```

**Comment by l0rd** [comment]
Tested a rootful WSL machine with a simple nftables ruleset and got no error:

```
# cat << EOF > /tmp/simplerule
table inet filter {
       chain input {
           type filter hook input priority 0;
           policy drop;

           # Allow established/related connections
           ct state established,related accept

           # Allow HTTP
           tcp dport 80 accept

           # Allow HTTPS
           tcp dport 443 accept
       }
   }
EOF
# nft -f /tmp/simplerule
# nft list ruleset
table inet filter {
        chain input {
                type filter hook input priority filter; policy drop;
                ct state established,related accept
                tcp dport 80 accept
                tcp dport 443 accept
        }
}
```

Howeber netawark tests in [250-bridge-nftables.bats](https://github.com/containers/netavark/blob/main/test/250-bridge-nftables.bats) failed:

```
# dnf install -y make rust cargo protobuf-compiler bats jq
# cd /mnt/c/Users/<folder where netavark was cloned>
# make
# bats ./test/250-bridge-nftables.bats -f "check nftables driver is in use"
250-bridge-nftables.bats
 ✗ check nftables driver is in use
   (from function `die' in file test/helpers.bash, line 249,
    from function `run_helper' in file test/helpers.bash, line 233,
    from function `run_in_host_netns' in file test/helpers.bash, line 166,
    from function `run_netavark' in file test/helpers.bash, line 136,
    in test file test/250-bridge-nftables.bats, line 12)
     `RUST_LOG=netavark=info run_netavark --file ${TESTSDIR}/testfiles/simplebridge.json setup $(get_container_netns_path)' failed
    nsenter -n -m -w -t 14493 ip link set lo up
    nsenter -n -m -w -t 14493 ./bin/netavark --rootless false --config /tmp/netavark_bats.1qVMcE/config --file /mnt/c/Users/mario/Git/netavark/test/testfiles/simplebridge.json setup /proc/14495/ns/net
   [INFO  netavark::firewall] Using nftables firewall driver
   [INFO  netavark::network::netlink] Adding route (dest: 0.0.0.0/0 ,gw: 10.88.0.1, metric 100)
   [INFO  netavark::firewall::nft] Creating container chain nv_53ce4390_10_88_0_0_nm16
   internal:0:0-0: Error: Could not process rule: No such file or directory

   internal:0:0-0: Error: Could not process rule: No such file or directory

   {"error":"nftables error: nft did not return successfully while applying ruleset"}
   [ rc=1 (** EXPECTED 0 **) ]
   #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
   #| FAIL: exit code is 1; expected 0
   #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

1 test, 1 failure
```

**Comment by l0rd** [comment]
@Luap99 any idea why running `nft` manually works but netawark fails? Is there a `nft` ruleset I can test?

**Comment by Luap99** [comment]
```
table inet netavark {
	chain INPUT {
		type filter hook input priority filter; policy accept;
		ip saddr 10.88.0.0/16 meta l4proto { tcp, udp } th dport 53 accept
	}

	chain FORWARD {
		type filter hook forward priority filter; policy accept;
		ct state invalid drop
		jump NETAVARK-ISOLATION-1
		ip daddr 10.88.0.0/16 ct state established,related accept
		ip saddr 10.88.0.0/16 accept
	}

	chain POSTROUTING {
		type nat hook postrouting priority srcnat; policy accept;
		meta mark & 0x00002000 == 0x00002000 masquerade
		ip saddr 10.88.0.0/16 jump nv_2f259bab_10_88_0_0_nm16
	}

	chain PREROUTING {
		type nat hook prerouting priority dstnat; policy accept;
		fib daddr type local jump NETAVARK-HOSTPORT-DNAT
	}

	chain OUTPUT {
		type nat hook output priority dstnat; policy accept;
		fib daddr type local jump NETAVARK-HOSTPORT-DNAT
	}

	chain NETAVARK-HOSTPORT-DNAT {
		ip daddr 10.88.0.1 meta l4proto { tcp, udp } th dport 53 dnat ip to 10.88.0.1:54
		tcp dport 80 jump nv_2f259bab_10_88_0_0_nm16_dnat
	}

	chain NETAVARK-HOSTPORT-SETMARK {
		meta mark set meta mark | 0x00002000
	}

	chain NETAVARK-ISOLATION-1 {
	}

	chain NETAVARK-ISOLATION-2 {
	}

	chain NETAVARK-ISOLATION-3 {
		oifname "podman0" drop
		jump NETAVARK-ISOLATION-2
	}

	chain nv_2f259bab_10_88_0_0_nm16 {
		ip daddr 10.88.0.0/16 accept
		ip daddr != 224.0.0.0/4 masquerade
	}

	chain nv_2f259bab_10_88_0_0_nm16_dnat {
		ip saddr 10.88.0.0/16 tcp dport 80 jump NETAVARK-HOSTPORT-SETMARK
		ip saddr 127.0.0.1 tcp dport 80 jump NETAVARK-HOSTPORT-SETMARK
		tcp dport 80 dnat ip to 10.88.0.2:80
	}
}

```

That is from a simple `podman run -d -p 80:80  quay.io/libpod/testimage:20241011 sleep 10`

You can also `strace -f` the podman command, in the netlink messages there are some more nft error messages encoded that are not displayed otherwise. 

Looking at this again I think we are using `l4proto { tcp, udp }` which is a set which per issue https://github.com/microsoft/WSL/issues/6044 is not working

**Comment by elhananjair** [comment]
Hello @l0rd 
I am facing the same issue when executing `podman-compose --in-pod=1 --project-name myproject -f ./docker-compose.yml up -d`, Have you found a solution for that yet?

**Comment by elhananjair** [comment]
> You should not be facing the problem if you are using the default Podman machine. The problem is with nftables and the WSLv2 kernel but we are currently configuring the WSL machine to use iptables rather than the nftables.

Yeah, I am using WSL2 with the Fedora 42 beta WSL image and facing the issue. 

![Image](https://github.com/user-attachments/assets/3ad7574a-0303-4d1b-9cc1-24afbcfcce40)

**Comment by l0rd** [comment]
You can still manually configure podman to use iptables by adding the following lines to the `/etc/containers/containers.conf` (that's what [we currently do automatically when creating the WSL machine](https://github.com/l0rd/podman/blob/dae1541529cc2810fd603460f55f12291ac6ccbb/pkg/machine/wsl/declares.go#L11)):

```
[network]
firewall_driver="iptables"
```

**Comment by elhananjair** [comment]
> You can still manually configure podman to use iptables by adding the following lines to the `/etc/containers/containers.conf` (that's what [we currently do automatically when creating the WSL machine](https://github.com/l0rd/podman/blob/dae1541529cc2810fd603460f55f12291ac6ccbb/pkg/machine/wsl/declares.go#L11)):
> 
> ```
> [network]
> firewall_driver="iptables"
> ```

Thank you, it worked now

**Comment by kaikli** [comment]
Just because it may help somehow.

I get also with the docker deskop and the wsl integration a similar error besides podman inside the container.

**Comment by wmcdonald404** [comment]
> firewall_driver="iptables"

For others coming across this, you also need** to install either `iptables-nft` or `iptables-legacy`

 ** on the OOTB WSL2 Fedora, at least. CF: https://github.com/containers/podman/issues/16956#issuecomment-1368502060

**Comment by craigloewen-msft** [comment]
Could you try this on the latest version of WSL: 2.5.7 ? 

I tried it today and everything worked as expected for me, I think this might be fixed in latest.

```
PS C:\Users\crloewen> podman machine init --image docker://quay.io/mloriedo/machine-os-wsl:5.5-next
Looking up Podman Machine image at quay.io/mloriedo/machine-os-wsl:5.5-next to create VM
Getting image source signatures
Copying blob f1c476e3d441 done   |
Copying config 44136fa355 done   |
Writing manifest to image destination
f1c476e3d441f7ac1e3a963e590b8583a50529e25752204aab3ff431da50871f
Extracting compressed file: podman-machine-default-amd64: done
Importing operating system into WSL (this may take a few minutes on a new WSL install)...
The operation completed successfully.
Configuring system...
Machine init complete
To start your machine run:

        podman machine start

PS C:\Users\crloewen> podman machine set --rootful
PS C:\Users\crloewen> podman machine start
Starting machine "podman-machine-default"
API forwarding listening on: npipe:////./pipe/podman-machine-default

Another process was listening on the default Docker API pipe address.
You can still connect Docker API clients by setting DOCKER HOST using the
following powershell command in your terminal session:

        $Env:DOCKER_HOST = 'npipe:////./pipe/podman-machine-default'

Or in a classic CMD prompt:

        set DOCKER_HOST=npipe:////./pipe/podman-machine-default

Alternatively, terminate the other process and restart podman machine.
Machine "podman-machine-default" started successfully
PS C:\Users\crloewen> podman run hello
Resolved "hello" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull quay.io/podman/hello:latest...
Getting image source signatures
Copying blob sha256:81df7ff16254ed9756e27c8de9ceb02a9568228fccadbf080f41cc5eb5118a44
Copying config sha256:5dd467fce50b56951185da365b5feee75409968cbab5767b9b59e325fb2ecbc0
Writing manifest to image destination
!... Hello Podman World ...!

         .--"--.
       / -     - \
      / (O)   (O) \
   ~~~| -=(,Y,)=- |
    .---. /`  \   |~~
 ~/  o  o \~~~~.----. ~~
  | =(X)= |~  / (O (O) \
   ~~~~~~~  ~| =(Y_)=-  |
  ~~~~    ~~~|   U      |~~

Project:   https://github.com/containers/podman
Website:   https://podman.io
Desktop:   https://podman-desktop.io
Documents: https://docs.podman.io
YouTube:   https://youtube.com/@Podman
X/Twitter: @Podman_io
Mastodon:  @Podman_io@fosstodon.org
PS C:\Users\crloewen>
```

**Comment by Luap99** [comment]
@craigloewen-msft Note to force the use of nftables you must either have a rootful machine or use
```
podman run --network bridge hello
```

In any case we will test again. Though I don't see a 2.5.9 release here https://github.com/microsoft/WSL/releases?

**Comment by baude** [comment]
With WSL-2.5.7 this seems to work now and I believe we can close this.  I have verified with my windows box here. @l0rd given that you reported this, can you `wsl --update` and see if it now works for you?

**Comment by craigloewen-msft** [comment]
@Luap99 I meant to type in `2.5.7` but typed `2.5.9` instead!

**Comment by l0rd** [comment]
That's great! Unfortunately I am traveling and I don't have the Windows laptop with me. I will check in a couple of days.

**Comment by l0rd** [comment]
I am not able to reproduce the issue anymore. Thank you @craigloewen-msft for letting us know. I am closing this issue as completed. 

I have opened https://github.com/containers/podman/pull/26318 to revert the WSL specific config to use iptables.
We should revert https://github.com/containers/podman-machine-wsl-os/commit/cb199ac2e7a64013ecf3b46b77e567978290a8b5 too but considereda that @Luap99 is moving the WSL image to `containers/podman-machine-os` we should fix that there instead.

**Comment by J-PC** [comment]
I'm currently using WSL 2.5.7 on Windows 10.0.19045 Build 19045 and the problem still exists.
I removed iptables like in the PR https://github.com/containers/podman/pull/26318 from the 5.5 and 5.6 versions of the quay.io/podman/machine-os-wsl images and I still get the following errors:

```
internal:0:0-0: Error: Could not process rule: No such file or directory

internal:0:0-0: Error: Could not process rule: No such file or directory

Error: netavark: nftables error: "nft" did not return successfully while applying ruleset
```
The official FedoraLinux-42 WSL image is also impacted by the same error.

> > You can still manually configure podman to use iptables by adding the following lines to the `/etc/containers/containers.conf` (that's what [we currently do automatically when creating the WSL machine](https://github.com/l0rd/podman/blob/dae1541529cc2810fd603460f55f12291ac6ccbb/pkg/machine/wsl/declares.go#L11)):
> > ```
> > [network]
> > firewall_driver="iptables"
> > ```
> 
> Thank you, it worked now

This workaround works for the three images currently.

**Comment by l0rd** [comment]
@J-PC can you please provide detailed instructions on how to reproduce your problem? 

I am testing the command `podman run hello`:
- using the podman binary from PR #26318 
- with podman configured as rootful
- with the default image `quay.io/podman/machine-os-wsl:5.6`

The command fails with WSL v2.4.13.0 and succeeds with v2.5.7.0.

And when the command failed, I got a different message compared to what you shared:
```
Error: preparing container 852c8a664e89c58c68aa8dcd42d0e29654a79b13ebeb1ddb176a382a6f3e8ed7 for attach: netavark (exit code 1): nftables error: "nft" did not return successfully while applying ruleset` 
```

**Comment by l0rd** [comment]
I have tested the same scenario on an x64 laptop and I could reproduce the problem. Reopening this issue:

```
> wsl --version
WSL version: 2.5.7.0
Kernel version: 6.6.87.1-1
WSLg version: 1.0.66
MSRDC version: 1.2.6074
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.22631.5189
```

**Comment by craigloewen-msft** [comment]
@l0rd were you able to repro this with the exact same steps as above? I am on an x64 desktop and am unable to repro it with those steps. 

<details>
<summary>My logs</summary>

```
PS C:\Users\crloewen>  podman machine init --image docker://quay.io/mloriedo/machine-os-wsl:5.5-next
Looking up Podman Machine image at quay.io/mloriedo/machine-os-wsl:5.5-next to create VM
Getting image source signatures
Copying blob f1c476e3d441 done   |
Copying config 44136fa355 done   |
Writing manifest to image destination
f1c476e3d441f7ac1e3a963e590b8583a50529e25752204aab3ff431da50871f
Extracting compressed file: podman-machine-default-amd64: done
Importing operating system into WSL (this may take a few minutes on a new WSL install)...
The operation completed successfully.
Configuring system...
Machine init complete
To start your machine run:

        podman machine start

PS C:\Users\crloewen> podman machine set --rootful
PS C:\Users\crloewen> podman machine start
Starting machine "podman-machine-default"
API forwarding listening on: npipe:////./pipe/docker_engine

Docker API clients default to this address. You do not need to set DOCKER_HOST.
Machine "podman-machine-default" started successfully
PS C:\Users\crloewen> podman run hello
Resolved "hello" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull quay.io/podman/hello:latest...
Getting image source signatures
Copying blob sha256:81df7ff16254ed9756e27c8de9ceb02a9568228fccadbf080f41cc5eb5118a44
Copying config sha256:5dd467fce50b56951185da365b5feee75409968cbab5767b9b59e325fb2ecbc0
Writing manifest to image destination
!... Hello Podman World ...!

         .--"--.
       / -     - \
      / (O)   (O) \
   ~~~| -=(,Y,)=- |
    .---. /`  \   |~~
 ~/  o  o \~~~~.----. ~~
  | =(X)= |~  / (O (O) \
   ~~~~~~~  ~| =(Y_)=-  |
  ~~~~    ~~~|   U      |~~

Project:   https://github.com/containers/podman
Website:   https://podman.io
Desktop:   https://podman-desktop.io
Documents: https://docs.podman.io
YouTube:   https://youtube.com/@Podman
X/Twitter: @Podman_io
Mastodon:  @Podman_io@fosstodon.org
PS C:\Users\crloewen> wsl --version
WSL version: 2.5.7.0
Kernel version: 6.6.87.1-1
WSLg version: 1.0.66
MSRDC version: 1.2.6074
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.26120.4441
PS C:\Users\crloewen>
```

</details>

**Comment by l0rd** [comment]
Testing with the reproducer provided by @Luap99:

```bash
cat << EOF > /tmp/seriousrule
table inet netavark {
 chain INPUT {
  type filter hook input priority filter; policy accept;
  ip saddr 10.88.0.0/16 meta l4proto { tcp, udp } th dport 53 accept
 }

 chain FORWARD {
  type filter hook forward priority filter; policy accept;
  ct state invalid drop
  jump NETAVARK-ISOLATION-1
  ip daddr 10.88.0.0/16 ct state established,related accept
  ip saddr 10.88.0.0/16 accept
 }

 chain POSTROUTING {
  type nat hook postrouting priority srcnat; policy accept;
  meta mark & 0x00002000 == 0x00002000 masquerade
  ip saddr 10.88.0.0/16 jump nv_2f259bab_10_88_0_0_nm16
 }

 chain PREROUTING {
  type nat hook prerouting priority dstnat; policy accept;
  fib daddr type local jump NETAVARK-HOSTPORT-DNAT
 }

 chain OUTPUT {
  type nat hook output priority dstnat; policy accept;
  fib daddr type local jump NETAVARK-HOSTPORT-DNAT
 }

 chain NETAVARK-HOSTPORT-DNAT {
  ip daddr 10.88.0.1 meta l4proto { tcp, udp } th dport 53 dnat ip to 10.88.0.1:54
  tcp dport 80 jump nv_2f259bab_10_88_0_0_nm16_dnat
 }

 chain NETAVARK-HOSTPORT-SETMARK {
  meta mark set meta mark | 0x00002000
 }

 chain NETAVARK-ISOLATION-1 {
 }

 chain NETAVARK-ISOLATION-2 {
 }

 chain NETAVARK-ISOLATION-3 {
  oifname "podman0" drop
  jump NETAVARK-ISOLATION-2
 }

 chain nv_2f259bab_10_88_0_0_nm16 {
  ip daddr 10.88.0.0/16 accept
  ip daddr != 224.0.0.0/4 masquerade
 }

 chain nv_2f259bab_10_88_0_0_nm16_dnat {
  ip saddr 10.88.0.0/16 tcp dport 80 jump NETAVARK-HOSTPORT-SETMARK
  ip saddr 127.0.0.1 tcp dport 80 jump NETAVARK-HOSTPORT-SETMARK
  tcp dport 80 dnat ip to 10.88.0.2:80
 }
}
EOF
# sudo nft -f /tmp/seriousrule
/tmp/seriousrule:23:3-16: Error: Could not process rule: No such file or directory
  fib daddr type local jump NETAVARK-HOSTPORT-DNAT
  ^^^^^^^^^^^^^^
/tmp/seriousrule:28:3-16: Error: Could not process rule: No such file or directory
  fib daddr type local jump NETAVARK-HOSTPORT-DNAT
  ^^^^^^^^^^^^^^
```

Note that this works fine on a WSL instance created on an arm64 Windows.

**Comment by l0rd** [comment]
@craigloewen-msft no, those instructions were valid before we merged #25202. Currently, to reproduce the issue, you need to first checkout PR #26318 and build podman. I ~~will update~~ have updated the instructions in the description because it's confusing:

```pwsh
cd <podman git repo>
gh pr checkout 26318
.\winmake.ps1 podman
.\bin\windows\podman machine init --rootful --now
.\bin\windows\podman run hello
```

**Comment by Luap99** [comment]
Do you have a link to the kernel config used by WSL? I am not sure why it differs but AFAIK wsl doesn't use the dynamically loaded modules and nft complains about the NFT_FIB module missing from the error above. 

That is what I have on my fedora system.
```
$ grep FIB  /boot/config-6.14.9-200.fc41.x86_64
CONFIG_IP_FIB_TRIE_STATS=y
CONFIG_NFT_FIB=m
CONFIG_NFT_FIB_INET=m
CONFIG_NFT_FIB_NETDEV=m
CONFIG_NFT_FIB_IPV4=m
CONFIG_NFT_FIB_IPV6=m
CONFIG_FIB_RULES=y

```

**Comment by l0rd** [comment]
For the x86 `CONFIG_NFT_FIB_INET=m` and `CONFIG_NFT_FIB_NETDEV=m` aren't configured.

```bash
$ # ARM64
$ curl -sSL https://raw.githubusercontent.com/microsoft/WSL2-Linux-Kernel/refs/heads/linux-msft-wsl-6.6.y/arch/arm64/configs/config-wsl-arm64 | grep FIB
CONFIG_IP_FIB_TRIE_STATS=y
CONFIG_NFT_FIB=m
CONFIG_NFT_FIB_INET=m
CONFIG_NFT_FIB_NETDEV=m
CONFIG_NFT_FIB_IPV4=m
CONFIG_NFT_FIB_IPV6=m
CONFIG_FIB_RULES=y
$
$ # x86
$ curl -sSL https://raw.githubusercontent.com/microsoft/WSL2-Linux-Kernel/refs/heads/linux-msft-wsl-6.6.y/arch/x86/configs/config-wsl | grep FIB
CONFIG_IP_FIB_TRIE_STATS=y
CONFIG_NFT_FIB=m
CONFIG_NFT_FIB_IPV4=m
# CONFIG_NFT_FIB_IPV6 is not set
CONFIG_FIB_RULES=y
```

**Comment by Luap99** [comment]
m means it is compiled as module, AFAIK nftables will load it automatically. But how is module loading even supposed to work on WSL2? At least with regular linux distros the modules are provided under /usr where modprobe would find and load them. But I don't think that is a thing with WSL2 where everything must be compiled in?

**Comment by TobiX** [comment]
> But how is module loading even supposed to work on WSL2?

You need to provide modules in a vhdx, as described in https://github.com/microsoft/WSL2-Linux-Kernel?tab=readme-ov-file#build-instructions (and indeed, you can fix the issue by building your own kernel including the missing modules)

I requested the missing kernel modules in https://github.com/microsoft/WSL/issues/13479, maybe someone from this issue can prod the right people at Microsoft? 🥺

**Comment by Luap99** [comment]
Note we have strong plans to drop the iptables driver with podman 6 next year so this really should be fixed on WSL before then so it can work correctly with nftables.

**Comment by l0rd** [comment]
Latest version of WSL still doesn't work on x86 (`v2.6.1.0` with kernel ` 6.6.87.2-1`).

WSL Kernel recompiled with the config suggested [here](https://github.com/microsoft/WSL/issues/13479) by @TobiX works fine. ~~doesn't seem to work neither. But the error is different, compared to the default Kernel, when running `podman run hello`~~:

```diff
-- Error: preparing container <...> for attach: netavark (exit code 1): nftables error: "nft" did not return successfully while applying ruleset
++ Error: preparing container <...> for attach: netavark (exit code 1): create bridge: Netlink error: Operation not supported (os error 95)
```

~~@Luap99 any idea of other modules that may be missing?~~

**EDIT** After a second try I was able to use the Kernel config suggested by @TobiX to maek Podman work fine with nftables on WSL.

**Comment by Luap99** [comment]
@l0rd That is not a nftables error but an error that happens much earlier when creating a bridge device, any chance the kernel doesn't have the bridge module?
i.e. something like this must work `unshare -rn sh -c "ip link add test-br0 type bridge && ip link"` and be able to create the bridge

I think that would be CONFIG_BRIDGE and likely CONFIG_BRIDGE_NETFILTER? I have never really looked into what modules are needed exactly.

**Comment by Luap99** [comment]
And `CONFIG_VETH` as well so it can create the veth pair

**Comment by l0rd** [comment]
I gave it another try, and with the Kernel rebuilt with the config changes in https://github.com/microsoft/WSL/issues/13479, rootful podman works with nftables. (When I tried yesterday, I wasn't loading any module, which explained why it was failing earlier.) So, if https://github.com/microsoft/WSL/issues/13479 gets fixed, this problem will also be fixed. cc @craigloewen-msft

**Comment by Luap99** [comment]
I believe https://github.com/microsoft/WSL/issues/13479 is ultimately a duplicate of https://github.com/microsoft/WSL/issues/6044 which is open for a long time. I really hope the default wsl kernel can enable the missing nftables modules soon so we can fully transition of iptables

**Comment by hasan4791** [comment]
> I believe https://github.com/microsoft/WSL/issues/13479 is ultimately a duplicate of https://github.com/microsoft/WSL/issues/6044 which is open for a long time. I really hope the default wsl kernel can enable the missing nftables modules soon so we can fully transition of iptables

Itseems to only address the x86 hope aarch64 would also be taken care of!!!

**Comment by l0rd** [comment]
Fixed now. The fix should have been included in WSL version 2.7.5 (I don't have an x86 machine to confirm the exact version). [This should be the WSL kernel commit](https://github.com/microsoft/WSL2-Linux-Kernel/commit/87467666618572252a17d1cda8012d75ccce69c1), included in [linux-msft-wsl-6.18.20.1](https://github.com/microsoft/WSL2-Linux-Kernel/releases/tag/linux-msft-wsl-6.18.20.1) that is bundled with [WSL 2.7.5](https://github.com/microsoft/WSL/releases#release-2.7.5).
