### ISSUE TITLE
FROM fails to resolve local manifest with correct platform

### ISSUE THREAD

**Issue by emersion** [containers/podman#25913]
### Issue Description

`FROM` fails to reference a local manifest with the correct platform.

### Steps to reproduce the issue

Start with the following two files:

**`Dockerfile.base`**:

```dockerfile
FROM --platform=$BUILDPLATFORM docker.io/alpine AS base
ARG TARGETPLATFORM
RUN echo $TARGETPLATFORM >>/targetplatform
```

**`Dockerfile.final`**:

```dockerfile
FROM foobase AS final
```

Then execute the following commands:

```sh
podman build --platform linux/arm64 --manifest foobase -f Dockerfile.base
podman build --platform linux/arm64 --manifest foofinal -f Dockerfile.final
```

### Describe the results you received

The second command fails with:

```
STEP 1/1: FROM foobase AS final
Resolving "foobase" using unqualified-search registries (/etc/containers/registries.conf.d/10-unqualified-search-registries.conf)
Trying to pull docker.io/library/foobase:latest...
Error: creating build container: initializing source docker://foobase:latest: reading manifest latest in docker.io/library/foobase: requested access to the resource is denied
```

The manifest sounds correct:

```
> podman manifest inspect foobase
{
    "schemaVersion": 2,
    "mediaType": "application/vnd.oci.image.index.v1+json",
    "manifests": [
        {
            "mediaType": "application/vnd.oci.image.manifest.v1+json",
            "size": 1181,
            "digest": "sha256:691729362b6b9f94cf33982b29a4de0af672213d92e2a122767afeaeeb8629d7",
            "platform": {
                "architecture": "arm64",
                "os": "linux"
            }
        }
    ]
}
```

### Describe the results you expected

The second Dockerfile should be able to reference the image in the manifest with the correct platform.

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.38.0-dev
  cgroupControllers:
  - cpu
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-1:2.1.13-1
    path: /usr/bin/conmon
    version: 'conmon version 2.1.13, commit: 82de887596ed8ee6d9b2ee85e4f167f307bb569b'
  cpuUtilization:
    idlePercent: 85.72
    systemPercent: 3.3
    userPercent: 10.98
  cpus: 12
  databaseBackend: boltdb
  distribution:
    distribution: arch
    version: unknown
  eventLogger: journald
  freeLocks: 1754
  hostname: haruko
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 6.13.8-arch1-1
  linkmode: dynamic
  logDriver: journald
  memFree: 8249348096
  memTotal: 84276158464
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.14.0-1
      path: /usr/lib/podman/aardvark-dns
      version: aardvark-dns 1.14.0
    package: netavark-1.14.1-1
    path: /usr/lib/podman/netavark
    version: netavark 1.14.1
  ociRuntime:
    name: crun
    package: crun-1.21-1
    path: /usr/bin/crun
    version: |-
      crun version 1.21
      commit: 10269840aa07fb7e6b7e1acff6198692d8ff5c88
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-2025_03_20.32f6212-1
    version: ""
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /etc/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.3.2-1
    version: |-
      slirp4netns version 1.3.2
      commit: 0f13345bcef588d2bb70d662d41e92ee8a816d85
      libslirp: 4.9.0
      SLIRP_CONFIG_VERSION_MAX: 6
      libseccomp: 2.5.6
  swapFree: 10736689152
  swapTotal: 10737405952
  uptime: 341h 9m 11.00s (Approximately 14.21 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /home/simon/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/simon/.local/share/containers/storage
  graphRootAllocated: 1999844147200
  graphRootUsed: 1341655212032
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 893
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/simon/.local/share/containers/storage/volumes
version:
  APIVersion: 5.3.0-dev
  Built: 1729709946
  BuiltTime: Wed Oct 23 20:59:06 2024
  GitCommit: e2ebf81cb5dce0402439f962e5543ff5d85e0c73-dirty
  GoVersion: go1.23.2
  Os: linux
  OsArch: linux/amd64
  Version: 5.3.0-dev
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

**Comment by baude** [comment]
@nalind mind peeking at this ?

**Comment by flouthoc** [comment]
I think this is fixed in upstream.

**Comment by emersion** [comment]
Curious: it appears that something is wrong when committing the first image. With buildah 1.39.4:

- Using buildah for both images works
- Using podman for the first image and buildah for the second one doesn't work
- Using buildah for the first image and podman for the second one works

(Note, I need to `podman manifest rm foobase` between attempts, because images are appended to the manifest instead of replacing previous entries with the same platform.)

**Comment by emersion** [comment]
Ah, it seems like I can still reproduce with `buildah build --layers`. This flag is disabled by default with buildah, but enabled by default with podman.

Additionally, the bug cannot be reproduced with `podman build --layers=false`.

**Comment by flouthoc** [comment]
Could be that, I checked with `buildah` and by default `--layers` is `false` there.

**Comment by nalind** [comment]
Using `--platform` for a build quietly alters the pull policy to "newer" to try to make sure that we use a base image that matches the desired platform, and that would explain the `Trying to pull docker.io/library/foobase:latest...` message.

If that pull policy means we look at a registry and, not finding an image with the searched-for name there, fail, I think that's a bug.  Not noticing that we have a "locahost/foobase" locally and only prompting to expand "foobase" using the names of the configured registries before trying to pull the image is also a problem of some kind, but then I'm not sure I completely understand the details of the whole shortnames implementation.

**Comment by mattnathan** [comment]
I have also hit this issue. My initial situation was very similar to the OP, but after a bit of experimentation I managed to get it to fail sooner in the build using the `--all-platforms` flag for the final build.

```
podman build --platform linux/arm64 --manifest foobase -f Dockerfile.base
podman build --all-platforms --manifest foofinal -f Dockerfile.final
```

Now the second command fails almost immediately with

```
Error: base image name "localhost/foobase" didn't resolve to a manifest list
```

I believe this to be the same underlying error but without getting to the pull part of the process. I've also been testing the second command with `--pull=never` just to avoid the network trip for images I know aren't online.

I will start experimenting with `--layers false` to see how that affects my build.

**edit**

I forgot to mention that I'm using Podman 5.5.0 on Mac (arm64) and using `--platforms linux/arm64,linux/amd64` in the real build. Using `--platforms` instead of `--all-platforms` for the second build results in podman resolving the `arm64` image successfully but fails with errors like the OP for the `amd64` platform build job.

**edit2**

I tried all combinations of `--layers=false` on the base and final builds but still hit the issue each time.
