### ISSUE TITLE
pasta: HTTP downloads get truncated (UrBackup web UI). slirp4netns works fine.

### ISSUE THREAD

**Issue by hakong** [containers/podman#27179]
### Issue Description

HTTP responses get cut short from the urbackup http server container only when using pasta. Some of the urbackup web interface CSS/JS files get cut short (still have a valid Content-Length header). Chrome shows net::ERR_CONTENT_LENGTH_MISMATCH.

If I switch the exact same container to Network=slirp4netns, the problem disappears. Also, if I serve similarly sized files with nginx over pasta, I cannot reproduce the issue.

No reverse proxy involved. Browser and second host used to test are on the same LAN.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Run urbackup with pasta: `podman run --rm --name urbackup2   --network pasta:--map-gw   -p 8880:55414   docker.io/uroni/urbackup-server:latest
`
2. From another host, fetch a UI asset (might need to try a few times to hit the bug): `curl --http1.1 -v http://192.168.10.102:8880/css/bootstrap.chash-2f624089c65f12185e79925bc5a7fc42.min.css   -o /tmp/ur-pasta-keep.css   -w '\nsize_download=%`{size_download}\n\n'

### Describe the results you received

Sometimes content is received OK, sometimes truncated.

Examples (4x requests with bytes missing, 2x OK)
```
[root@manage ~]# curl --http1.1 -v http://192.168.10.102:8880/css/bootstrap.chash-2f624089c65f12185e79925bc5a7fc42.min.css   -o /tmp/ur-pasta-keep.css   -w '\nsize_download=%{size_download}\n\n'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 192.168.10.102:8880...
* Connected to 192.168.10.102 (192.168.10.102) port 8880
> GET /css/bootstrap.chash-2f624089c65f12185e79925bc5a7fc42.min.css HTTP/1.1
> Host: 192.168.10.102:8880
> User-Agent: curl/8.9.1
> Accept: */*
>
* Request completely sent off
< HTTP/1.1 200 ok
< Server: CS
< Content-Type: text/css
< Cache-Control: max-age=365000000, immutable
< Connection: Keep-Alive
< Keep-Alive: timeout=15, max=95
< Content-Length: 121260
<
{ [14300 bytes data]
* end of response with 11392 bytes missing
 90  118k   90  107k    0     0  9046k      0 --:--:-- --:--:-- --:--:-- 9753k
* closing connection #0
curl: (18) end of response with 11392 bytes missing

size_download=109868

[root@manage ~]# curl --http1.1 -v http://192.168.10.102:8880/css/bootstrap.chash-2f624089c65f12185e79925bc5a7fc42.min.css   -o /tmp/ur-pasta-keep.css   -w '\nsize_download=%{size_download}\n\n'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 192.168.10.102:8880...
* Connected to 192.168.10.102 (192.168.10.102) port 8880
> GET /css/bootstrap.chash-2f624089c65f12185e79925bc5a7fc42.min.css HTTP/1.1
> Host: 192.168.10.102:8880
> User-Agent: curl/8.9.1
> Accept: */*
>
* Request completely sent off
< HTTP/1.1 200 ok
< Server: CS
< Content-Type: text/css
< Cache-Control: max-age=365000000, immutable
< Connection: Keep-Alive
< Keep-Alive: timeout=15, max=95
< Content-Length: 121260
<
{ [14300 bytes data]
* end of response with 8496 bytes missing
 93  118k   93  110k    0     0  9229k      0 --:--:-- --:--:-- --:--:--  9.7M
* closing connection #0
curl: (18) end of response with 8496 bytes missing

size_download=112764

[root@manage ~]# curl --http1.1 -v http://192.168.10.102:8880/css/bootstrap.chash-2f624089c65f12185e79925bc5a7fc42.min.css   -o /tmp/ur-pasta-keep.css   -w '\nsize_download=%{size_download}\n\n'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 192.168.10.102:8880...
* Connected to 192.168.10.102 (192.168.10.102) port 8880
> GET /css/bootstrap.chash-2f624089c65f12185e79925bc5a7fc42.min.css HTTP/1.1
> Host: 192.168.10.102:8880
> User-Agent: curl/8.9.1
> Accept: */*
>
* Request completely sent off
< HTTP/1.1 200 ok
< Server: CS
< Content-Type: text/css
< Cache-Control: max-age=365000000, immutable
< Connection: Keep-Alive
< Keep-Alive: timeout=15, max=95
< Content-Length: 121260
<
{ [13984 bytes data]
100  118k  100  118k    0     0  48.6M      0 --:--:-- --:--:-- --:--:-- 57.8M
* Connection #0 to host 192.168.10.102 left intact

size_download=121260

[root@manage ~]#
[root@manage ~]# curl --http1.1 -v http://192.168.10.102:8880/css/bootstrap.chash-2f624089c65f12185e79925bc5a7fc42.min.css   -o /tmp/ur-pasta-keep.css   -w '\nsize_download=%{size_download}\n\n'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 192.168.10.102:8880...
* Connected to 192.168.10.102 (192.168.10.102) port 8880
> GET /css/bootstrap.chash-2f624089c65f12185e79925bc5a7fc42.min.css HTTP/1.1
> Host: 192.168.10.102:8880
> User-Agent: curl/8.9.1
> Accept: */*
>
* Request completely sent off
< HTTP/1.1 200 ok
< Server: CS
< Content-Type: text/css
< Cache-Control: max-age=365000000, immutable
< Connection: Keep-Alive
< Keep-Alive: timeout=15, max=95
< Content-Length: 121260
<
{ [14300 bytes data]
* end of response with 4152 bytes missing
 96  118k   96  114k    0     0  9638k      0 --:--:-- --:--:-- --:--:-- 10.1M
* closing connection #0
curl: (18) end of response with 4152 bytes missing

size_download=117108
[root@manage ~]# curl --http1.1 -v http://192.168.10.102:8880/css/bootstrap.chash-2f624089c65f12185e79925bc5a7fc42.min.css   -o /tmp/ur-pasta-keep.css   -w '\nsize_download=%{size_download}\n\n'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 192.168.10.102:8880...
* Connected to 192.168.10.102 (192.168.10.102) port 8880
> GET /css/bootstrap.chash-2f624089c65f12185e79925bc5a7fc42.min.css HTTP/1.1
> Host: 192.168.10.102:8880
> User-Agent: curl/8.9.1
> Accept: */*
>
* Request completely sent off
< HTTP/1.1 200 ok
< Server: CS
< Content-Type: text/css
< Cache-Control: max-age=365000000, immutable
< Connection: Keep-Alive
< Keep-Alive: timeout=15, max=95
< Content-Length: 121260
<
{ [14300 bytes data]
100  118k  100  118k    0     0  51.9M      0 --:--:-- --:--:-- --:--:-- 57.8M
* Connection #0 to host 192.168.10.102 left intact

size_download=121260
[root@manage ~]# curl --http1.1 -v http://192.168.10.102:8880/css/bootstrap.chash-2f624089c65f12185e79925bc5a7fc42.min.css   -o /tmp/ur-pasta-keep.css   -w '\nsize_download=%{size_download}\n\n'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 192.168.10.102:8880...
* Connected to 192.168.10.102 (192.168.10.102) port 8880
> GET /css/bootstrap.chash-2f624089c65f12185e79925bc5a7fc42.min.css HTTP/1.1
> Host: 192.168.10.102:8880
> User-Agent: curl/8.9.1
> Accept: */*
>
* Request completely sent off
< HTTP/1.1 200 ok
< Server: CS
< Content-Type: text/css
< Cache-Control: max-age=365000000, immutable
< Connection: Keep-Alive
< Keep-Alive: timeout=15, max=95
< Content-Length: 121260
<
{ [7060 bytes data]
* end of response with 11392 bytes missing
 90  118k   90  107k    0     0  8819k      0 --:--:-- --:--:-- --:--:-- 8941k
* closing connection #0
curl: (18) end of response with 11392 bytes missing

size_download=109868

[root@manage ~]#
```

### Describe the results you expected

Expected no content missing.

### podman info output

```yaml
[urbackup@c2 ~]$ podman info
host:
  arch: amd64
  buildahVersion: 1.39.4
  cgroupControllers:
  - cpu
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.12-4.el10.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.12, commit: '
  cpuUtilization:
    idlePercent: 98.06
    systemPercent: 0.6
    userPercent: 1.34
  cpus: 8
  databaseBackend: sqlite
  distribution:
    distribution: rhel
    version: "10.0"
  eventLogger: file
  freeLocks: 2046
  hostname: c2.xyz.ab
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1015
      size: 1
    - container_id: 1
      host_id: 493216
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1015
      size: 1
    - container_id: 1
      host_id: 493216
      size: 65536
  kernel: 6.12.0-55.34.1.el10_0.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 3536257024
  memTotal: 16493936640
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.14.0-1.el10.x86_64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.14.0
    package: netavark-1.14.1-1.el10_0.x86_64
    path: /usr/libexec/podman/netavark
    version: netavark 1.14.1
  ociRuntime:
    name: crun
    package: crun-1.21-1.el10_0.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.21
      commit: 10269840aa07fb7e6b7e1acff6198692d8ff5c88
      rundir: /run/user/1015/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20250217.ga1e48a0-5.el10_0.x86_64
    version: ""
  remoteSocket:
    exists: true
    path: /run/user/1015/podman/podman.sock
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.3.2-1.el10.x86_64
    version: |-
      slirp4netns version 1.3.2
      commit: 0f13345bcef588d2bb70d662d41e92ee8a816d85
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 2193616896
  swapTotal: 2193616896
  uptime: 112h 45m 4.00s (Approximately 4.67 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /home/urbackup/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/urbackup/.local/share/containers/storage
  graphRootAllocated: 39611006976
  graphRootUsed: 22029217792
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 1
  runRoot: /run/user/1015/containers
  transientStore: false
  volumePath: /home/urbackup/.local/share/containers/storage/volumes
version:
  APIVersion: 5.4.0
  BuildOrigin: Red Hat, Inc. <http://bugzilla.redhat.com/bugzilla>
  Built: 1757462400
  BuiltTime: Wed Sep 10 00:00:00 2025
  GitCommit: ""
  GoVersion: go1.24.6 (Red Hat 1.24.6-1.el10_0)
  Os: linux
  OsArch: linux/amd64
  Version: 5.4.0
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional environment details

```
[root@c2 ~]# virt-what
kvm
[root@c2 ~]#
```

### Additional information

581 request examples with slirp4netns, all OK, all identical:
```
[urbackup@c2 ~]$ podman run --rm --name urbackup2   --network slirp4netns   -p 8880:55414   docker.io/uroni/urbackup-server:latest
```
```
[root@manage ~]# while :; do curl --http1.1 -v http://192.168.10.102:8880/css/bootstrap.chash-2f624089c65f12185e79925bc5a7fc42.min.css   -o /tmp/ur-pasta-keep.css   -w '\nsize_download=%{size_download}\n\n'; done 2>&1| tee slirp4netns.log

[root@manage ~]#  grep size_download slirp4netns.log | sort | uniq -c
    581 size_download=121260
[root@manage ~]# grep GET slirp4netns.log -c
582
[root@manage ~]#
```

620 request examples with pasta, only 233 are OK:

```
[urbackup@c2 ~]$ podman run --rm --name urbackup2   --network pasta:--map-gw   -p 8880:55414   docker.io/uroni/urbackup-server:latest
```
```
[root@manage ~]# while :; do curl --http1.1 -v http://192.168.10.102:8880/css/bootstrap.chash-2f624089c65f12185e79925bc5a7fc42.min.css   -o /tmp/ur-pasta-keep.css   -w '\nsize_download=%{size_download}\n\n'; done 2>&1| tee pasta.log
[root@manage ~]# grep size_download pasta.log | sort | uniq -c
     15 size_download=108600
     45 size_download=109552
    218 size_download=109868
      1 size_download=111000
      2 size_download=111316
     10 size_download=111496
      1 size_download=112448
      1 size_download=112944
      1 size_download=114212
      1 size_download=114392
      1 size_download=115660
      7 size_download=115840
      4 size_download=116792
     10 size_download=117108
      2 size_download=117288
     20 size_download=118240
     18 size_download=118736
      2 size_download=119688
     25 size_download=120004
      2 size_download=120184
      1 size_download=121136
    233 size_download=121260
[root@manage ~]# grep GET pasta.log -c
620
[root@manage ~]#
```

Nginx with pasta, not able to reproduce:
```
[hakongi@c2 nginx-repro]$ pwd
/home/hakongi/nginx-repro
[hakongi@c2 nginx-repro]$ ll
total 120
-rw-r--r--. 1 hakongi hakongi 121260 Sep 27 23:12 bootstrap.chash-2f624089c65f12185e79925bc5a7fc42.min.css

[hakongi@c2 nginx-repro]$ podman run --rm --name pasta-nginx   --network pasta:--map-gw   -p 8880:80   -v "$PWD":/usr/share/nginx/html:z   nginx:alpine
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2025/09/27 23:13:36 [notice] 1#1: using the "epoll" event method
2025/09/27 23:13:36 [notice] 1#1: nginx/1.29.1
2025/09/27 23:13:36 [notice] 1#1: built by gcc 14.2.0 (Alpine 14.2.0)
2025/09/27 23:13:36 [notice] 1#1: OS: Linux 6.12.0-55.34.1.el10_0.x86_64
2025/09/27 23:13:36 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 524288:524288
2025/09/27 23:13:36 [notice] 1#1: start worker processes
2025/09/27 23:13:36 [notice] 1#1: start worker process 25
2025/09/27 23:13:36 [notice] 1#1: start worker process 26
2025/09/27 23:13:36 [notice] 1#1: start worker process 27
2025/09/27 23:13:36 [notice] 1#1: start worker process 28
2025/09/27 23:13:36 [notice] 1#1: start worker process 29
2025/09/27 23:13:36 [notice] 1#1: start worker process 30
2025/09/27 23:13:36 [notice] 1#1: start worker process 31
2025/09/27 23:13:36 [notice] 1#1: start worker process 32
```
```
[root@manage ~]# while :; do curl --http1.1 -v http://192.168.10.102:8880/bootstrap.chash-2f624089c65f12185e79925bc5a7fc42.min.css   -o /tmp/ur-pasta-keep.css   -w '\nsize_download=%{size_download}\n\n'; done 2>&1| tee pasta-nginx.log

[root@manage ~]# grep GET pasta-nginx.log -c
257

[root@manage ~]# grep size_download pasta-nginx.log | sort | uniq -c
    256 size_download=121260
[root@manage ~]#
```

**Comment by Luap99** [comment]
>     package: passt-0^20250217.ga1e48a0-5.el10_0.x86_64

Upstream only supports the latest versions so please test the lastest version of pasta as it might have been fixed already.

cc @sbrivio-rh

**Comment by hakong** [comment]
Same issue also on pasta 2025_09_19.623dbf6-4-gf4729be

```
[root@c2 ~]# yum localinstall passt-gf4729be-1.x86_64.rpm --allowerasing
Updating Subscription Management repositories.
Last metadata expiration check: 0:44:34 ago on Mon 29 Sep 2025 11:36:09 AM UTC.
Dependencies resolved.
===========================================================================================================================================================================================================
 Package                                  Architecture                      Version                                                    Repository                                                     Size
===========================================================================================================================================================================================================
Removing dependent packages:
 passt-selinux                            noarch                            0^20250217.ga1e48a0-5.el10_0                               @rhel-10-for-x86_64-appstream-rpms                            287 k
Downgrading:
 passt                                    x86_64                            gf4729be-1                                                 @commandline                                                  1.8 M

Transaction Summary
===========================================================================================================================================================================================================
Remove     1 Package
Downgrade  1 Package

Total size: 1.8 M
Is this ok [y/N]: y
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                                                   1/1
  Downgrading      : passt-gf4729be-1.x86_64                                                                                                                                                           1/3
  Cleanup          : passt-0^20250217.ga1e48a0-5.el10_0.x86_64                                                                                                                                         2/3
  Erasing          : passt-selinux-0^20250217.ga1e48a0-5.el10_0.noarch                                                                                                                                 3/3
  Running scriptlet: passt-selinux-0^20250217.ga1e48a0-5.el10_0.noarch                                                                                                                                 3/3
Installed products updated.

Downgraded:
  passt-gf4729be-1.x86_64
Removed:
  passt-selinux-0^20250217.ga1e48a0-5.el10_0.noarch

Complete!
[root@c2 ~]# rpm -qa|grep passt
passt-gf4729be-1.x86_64
[root@c2 ~]# dnf info passt
Updating Subscription Management repositories.
Last metadata expiration check: 0:45:18 ago on Mon 29 Sep 2025 11:36:09 AM UTC.
Installed Packages
Name         : passt
Version      : gf4729be
Release      : 1
Architecture : x86_64
Size         : 4.0 M
Source       : passt-gf4729be-1.src.rpm
Repository   : @System
From repo    : @commandline
Summary      : Converted tgz package
License      : unknown
Description  : User-mode networking for VMs and namespaces
             :
             : (Converted from a tgz package by alien version 8.95.6.)

Available Packages
Name         : passt
Version      : 0^20250217.ga1e48a0
Release      : 5.el10_0
Architecture : x86_64
Size         : 265 k
Source       : passt-0^20250217.ga1e48a0-5.el10_0.src.rpm
Repository   : rhel-10-for-x86_64-appstream-rpms
Summary      : User-mode networking daemons for virtual machines and namespaces
URL          : https://passt.top/
License      : GPL-2.0-or-later AND BSD-3-Clause
Description  : passt implements a translation layer between a Layer-2 network interface and
             : native Layer-4 sockets (TCP, UDP, ICMP/ICMPv6 echo) on a host. It doesn't
             : require any capabilities or privileges, and it can be used as a simple
             : replacement for Slirp.
             :
             : pasta (same binary as passt, different command) offers equivalent functionality,
             : for network namespaces: traffic is forwarded using a tap interface inside the
             : namespace, without the need to create further interfaces on the host, hence not
             : requiring any capabilities or privileges.

[root@c2 ~]# reboot

Broadcast message from root@c2.xyz.ab on pts/1 (Mon 2025-09-29 12:22:04 UTC):

The system will reboot now!

[root@c2 ~]# Read from remote host c2.xyz.ab: Connection reset by peer
Connection to c2.xyz.ab closed.
client_loop: send disconnect: Broken pipe
[root@manage ~]#
```
```
[urbackup@c2 ~]$ podman run --rm --name urbackup2   --network pasta:--map-gw   -p 8880:55414   docker.io/uroni/urbackup-server:latest
[...snip...]
[urbackup@c2 ~]$ podman ps
CONTAINER ID  IMAGE                                   COMMAND     CREATED             STATUS             PORTS                                                     NAMES
795d2a649801  docker.io/uroni/urbackup-server:latest  run         About a minute ago  Up About a minute  0.0.0.0:8880->55414/tcp, 55413/tcp, 55415/tcp, 35623/udp  urbackup2
[urbackup@c2 ~]$
[urbackup@c2 ~]$ podman info|egrep -i 'passt|pasta'
  pasta:
    executable: /usr/bin/pasta
    package: passt-gf4729be-1.x86_64
      pasta 2025_09_19.623dbf6-4-gf4729be
  rootlessNetworkCmd: pasta
  - passthrough
[urbackup@c2 ~]$
```

```
[root@manage ~]# while :; do curl --http1.1 -v http://192.168.10.102:8880/css/bootstrap.chash-2f624089c65f12185e79925bc5a7fc42.min.css   -o /tmp/ur-pasta-keep.css   -w '\nsize_download=%{size_download}\n\n'; done 2>&1| tee pasta-2025_09_19.log
[root@manage ~]# grep -c GET pasta-2025_09_19.log
767
[root@manage ~]# grep size_download pasta-2025_09_19.log | sort | uniq -c
     23 size_download=108600
     46 size_download=109552
    170 size_download=109868
      2 size_download=110048
      2 size_download=111000
      6 size_download=111496
      1 size_download=114392
     17 size_download=115840
     14 size_download=116792
      8 size_download=117108
      1 size_download=117288
      1 size_download=117912
     33 size_download=118240
     44 size_download=118736
      1 size_download=119360
      3 size_download=119688
     36 size_download=120004
      5 size_download=120184
      1 size_download=121136
    353 size_download=121260
[root@manage ~]#
```

**Comment by sbrivio-rh** [comment]
This should be easy enough to reproduce, so I can give it a try soon.

@hakong if you want to speed this up it would be great if you could run pasta with the `--pcap` and `--log-file` options, something like `podman run ... --net=pasta,-p,/tmp/pasta.pcap,-l,/tmp/pasta.log` and try to get one of those failures reported in capture and log file.

**Comment by hakong** [comment]
Note: this is the stock RHEL10 version of pasta again:
```
[urbackup@c2 ~]$ podman ps
CONTAINER ID  IMAGE                                   COMMAND     CREATED             STATUS             PORTS                                                     NAMES
ddba9610f021  docker.io/uroni/urbackup-server:latest  run         About a minute ago  Up About a minute  0.0.0.0:8880->55414/tcp, 55413/tcp, 55415/tcp, 35623/udp  urbackup2
[urbackup@c2 ~]$ podman inspect urbackup2 | egrep -i 'pasta|network|passt'
          "NetworkSettings": {
                    "--network",
                    "pasta:--map-gw,-p,/tmp/pasta.pcap,-l,/tmp/pasta.log",
               "NetworkMode": "pasta",
[urbackup@c2 ~]$
[urbackup@c2 ~]$ tail -f /tmp/pasta.log
pasta 0^20250217.ga1e48a0-5.el10_0.x86_64: /usr/bin/pasta.avx2 (18118)

^C
[urbackup@c2 ~]$ stat /tmp/pasta.pcap
  File: /tmp/pasta.pcap
  Size: 88244167        Blocks: 433408     IO Block: 4096   regular file
Device: 253,0   Inode: 18149488    Links: 1
Access: (0600/-rw-------)  Uid: ( 1015/urbackup)   Gid: ( 1015/urbackup)
Context: unconfined_u:object_r:container_var_run_t:s0
Access: 2025-09-29 12:56:43.971948163 +0000
Modify: 2025-09-29 13:00:08.146141985 +0000
Change: 2025-09-29 13:00:08.146141985 +0000
 Birth: 2025-09-29 12:56:43.971948163 +0000
[urbackup@c2 ~]$ podman stop urbackup2
urbackup2
[urbackup@c2 ~]$
```
Log file didnt show anything:
```
[urbackup@c2 ~]$ cat /tmp/pasta.log
pasta 0^20250217.ga1e48a0-5.el10_0.x86_64: /usr/bin/pasta.avx2 (18118)
[urbackup@c2 ~]$
```

[pasta-filtered.zip](https://github.com/user-attachments/files/22598956/pasta-filtered.zip)

**Comment by hakong** [comment]
pcap in zip file:
streams 0-2: download ok
stream 3: download failed, bytes missing

**Comment by sbrivio-rh** [comment]
> pcap in zip file: streams 0-2: download ok stream 3: download failed, bytes missing

Thanks a lot for the traffic capture and the analysis. Looking at stream 3, I would have said that that issue should be fixed by https://passt.top/passt/commit/?id=c62fb08002ad88079b84d1aa694492746f0d7f22, which is not included in 0^20250217.ga1e48a0-5.el10_0, but is included in the upstream version you were using.

Would you have a chance to take the same capture with the newer pasta version? I start thinking you might be hitting two different issues with the same symptom.

> Log file didnt show anything

Right, sorry, I should have mentioned that you need to add `--debug` or `--trace` to the options as well, to see anything meaningful there. But that might affect timing and hide the issue, so the most helpful thing you could do, I think, is to share a new capture taken with the upstream version, if possible.

**Comment by hakong** [comment]
pasta 2025_09_19.623dbf6-4-gf4729be:

```
[root@manage ~]# grep -c GET pasta-2025_09_19.log
686
[root@manage ~]# grep size_download pasta-2025_09_19.log | sort | uniq -c
      5 size_download=109868
      1 size_download=111316
      5 size_download=115660
     72 size_download=120004
    603 size_download=121260
[root@manage ~]#
```



Looks better, but still not right.
Attached second pcap. [pasta-filtered-2025_09_19.623dbf6-4-gf4729be.zip](https://github.com/user-attachments/files/22607442/pasta-filtered-2025_09_19.623dbf6-4-gf4729be.zip)
Stream 0: ok
Stream 1: not ok

**Comment by sbrivio-rh** [comment]
> Looks better, but still not right. Attached second pcap. [pasta-filtered-2025_09_19.623dbf6-4-gf4729be.zip](https://github.com/user-attachments/files/22607442/pasta-filtered-2025_09_19.623dbf6-4-gf4729be.zip) Stream 0: ok Stream 1: not ok

Uh oh, it looks like we're a bit overreacting with that re-transmission in a half-closed state.

Thanks, I'm not sure what the issue is yet, but it should be relatively easy to find out with this capture.

**Comment by sbrivio-rh** [comment]
I just sent a [patch](https://archives.passt.top/passt-dev/20250930205132.885225-1-sbrivio@redhat.com/) for this, and the commit message explains the problem in detail.

However, I couldn't reproduce the issue. I ran that `curl` loop for a couple of hours, and the client always gets 121260 bytes in my setup, matching the Content-Length header. I tried this on two fairly different kernel versions, a 6.1 and a 6.17, but it always works for me, so further testing would be greatly appreciated.

@hakong would you mind trying out that patch? You can apply it with `b4` directly from the mailing list (you might need to `dnf install b4`):

    git clone git://passt.top/passt
    cd passt
    b4 shazam https://archives.passt.top/passt-dev/20250930205132.885225-1-sbrivio@redhat.com/
    make
    sudo make install # and you can revert this cleanly with 'make uninstall'

**Comment by hakong** [comment]
>However, I couldn't reproduce the issue.

Did you do that from another host on the same network? I could only reproduce this from a different host. Doing this on the container host gives OK results all the time.

```
[root@c2 ~]# seq 0 100 | xargs -n1 sh -c "curl --http1.1 -v http://192.168.10.102:8880/css/bootstrap.chash-2f624089c65f12185e79925bc5a7fc42.min.css -o /tmp/ur-pasta-keep.css -w '\nsize_download=%{size_download}\n\n'" 2>&1 | grep size_download | sort | uniq -c
    101 size_download=121260
[root@c2 ~]#
```

Doing this on a second host on the network (different VM):

```
[root@manage ~]# seq 0 100 | xargs -n1 sh -c "curl --http1.1 -v http://192.168.10.102:8880/css/bootstrap.chash-2f624089c65f12185e79925bc5a7fc42.min.css -o /tmp/ur-pasta-keep.css -w '\nsize_download=%{size_download}\n\n'" 2>&1 | grep size_download | sort | uniq -c
      1 size_download=109224
      2 size_download=109552
      8 size_download=109868
      1 size_download=110960
      5 size_download=111496
      1 size_download=112944
      1 size_download=115344
      2 size_download=115660
      2 size_download=115840
      2 size_download=116792
      1 size_download=117108
     11 size_download=118240
      6 size_download=118736
      1 size_download=119648
      2 size_download=120004
      3 size_download=120184
     52 size_download=121260
[root@manage ~]#
```

**Comment by hakong** [comment]
```
[root@c2 passt]# b4 shazam https://archives.passt.top/passt-dev/20250930205132.885225-1-sbrivio@redhat.com/
Looking up https://archives.passt.top/passt-dev/20250930205132.885225-1-sbrivio@redhat.com
Grabbing thread from archives.passt.top/passt-dev/20250930205132.885225-1-sbrivio@redhat.com/t.mbox.gz
Checking for newer revisions
Grabbing search results from lore.kernel.org
Nothing matching that query.
Analyzing 2 messages in the thread
Looking for additional code-review trailers on lore.kernel.org
Nothing matching that query.
Checking attestation on all messages, may take a moment...
---
[PATCH] tcp: Fix ACK sequence on FIN to tap, handle retransmission in half-closed state
---
Total patches: 1
---
Applying: tcp: Fix ACK sequence on FIN to tap, handle retransmission in half-closed state
[root@c2 passt]# make
seccomp profile passt allows:  accept accept4 bind clock_gettime close connect epoll_ctl epoll_pwait epoll_wait exit_group fallocate fcntl fsync ftruncate getsockname getsockopt listen lseek read recvfrom recvmmsg recvmsg sendmmsg sendmsg sendto setsockopt shutdown
   socket timerfd_create timerfd_gettime timerfd_settime write writev
seccomp profile pasta allows:  accept accept4 bind clock_gettime clone close connect epoll_ctl epoll_pwait epoll_wait exit exit_group fallocate fcntl fsync ftruncate getsockname getsockopt ioctl listen lseek openat pipe2 read recvfrom recvmmsg recvmsg rt_sigprocmask
   rt_sigreturn sendmmsg sendmsg sendto setns setsockopt shutdown socket splice timerfd_create timerfd_gettime timerfd_settime waitid write writev
seccomp profile vu allows:  accept accept4 bind clock_gettime close connect epoll_ctl epoll_pwait epoll_wait exit_group fallocate fcntl fsync ftruncate getsockname getsockopt ioctl listen lseek mmap munmap read recvfrom recvmmsg recvmsg sendmmsg sendmsg sendto
   setsockopt shutdown socket timerfd_create timerfd_gettime timerfd_settime write writev
cc -Wall -Wextra -Wno-format-zero-length -Wformat-security -pedantic -std=c11 -D_XOPEN_SOURCE=700 -D_GNU_SOURCE -D_FORTIFY_SOURCE=2 -O2 -pie -fPIE -DPAGE_SIZE=4096 -DVERSION=\"2025_09_19.623dbf6-8-gc71313a\" -DDUAL_STACK_SOCKETS=1 -DHAS_GETRANDOM -fstack-protector-strong   arch.c arp.c checksum.c conf.c dhcp.c dhcpv6.c flow.c fwd.c icmp.c igmp.c inany.c iov.c ip.c isolation.c lineread.c log.c mld.c ndp.c netlink.c migrate.c packet.c passt.c pasta.c pcap.c pif.c repair.c tap.c tcp.c tcp_buf.c tcp_splice.c tcp_vu.c udp.c udp_flow.c udp_vu.c util.c vhost_user.c virtio.c vu_common.c -o passt
cc -Wall -Wextra -Wno-format-zero-length -Wformat-security -pedantic -std=c11 -D_XOPEN_SOURCE=700 -D_GNU_SOURCE -D_FORTIFY_SOURCE=2 -pie -fPIE -DPAGE_SIZE=4096 -DVERSION=\"2025_09_19.623dbf6-8-gc71313a\" -DDUAL_STACK_SOCKETS=1 -DHAS_GETRANDOM -fstack-protector-strong -Ofast -mavx2 -ftree-vectorize -funroll-loops   \                                                                                                                                                                                                                                                           arch.c arp.c checksum.c conf.c dhcp.c dhcpv6.c flow.c fwd.c icmp.c igmp.c inany.c iov.c ip.c isolation.c lineread.c log.c mld.c ndp.c netlink.c migrate.c packet.c passt.c pasta.c pcap.c pif.c repair.c tap.c tcp.c tcp_buf.c tcp_splice.c tcp_vu.c udp.c udp_flow.c udp_vu.c util.c vhost_user.c virtio.c vu_common.c -o passt.avx2
ln -sf passt pasta
ln -sf passt.avx2 pasta.avx2
cc -Wall -Wextra -Wno-format-zero-length -Wformat-security -pedantic -std=c11 -D_XOPEN_SOURCE=700 -D_GNU_SOURCE -D_FORTIFY_SOURCE=2 -O2 -pie -fPIE -DPAGE_SIZE=4096 -DVERSION=\"2025_09_19.623dbf6-8-gc71313a\" -DDUAL_STACK_SOCKETS=1 -DHAS_GETRANDOM -fstack-protector-strong   -DARCH=\"x86_64\" qrap.c -o qrap
seccomp profile repair allows:  close connect exit_group fstat inotify_add_watch inotify_init1 newfstatat recvfrom recvmsg sendmsg sendto setsockopt socket stat statx write
cc -Wall -Wextra -Wno-format-zero-length -Wformat-security -pedantic -std=c11 -D_XOPEN_SOURCE=700 -D_GNU_SOURCE -D_FORTIFY_SOURCE=2 -O2 -pie -fPIE -DPAGE_SIZE=4096 -DVERSION=\"2025_09_19.623dbf6-8-gc71313a\" -DDUAL_STACK_SOCKETS=1 -DHAS_GETRANDOM -fstack-protector-strong   passt-repair.c -o passt-repair
ln -sf passt.1 pasta.1
[root@c2 passt]# sudo make install
mkdir -p /usr/local/bin /usr/local/share/man/man1
cp -d passt passt.avx2 pasta pasta.avx2 qrap passt-repair /usr/local/bin
cp -d passt.1 pasta.1 qrap.1 passt-repair.1 /usr/local/share/man/man1
mkdir -p /usr/local/share/doc/passt
cp -d README.plain.md /usr/local/share/doc/passt/README.md
cp -d doc/demo.sh /usr/local/share/doc/passt
[root@c2 passt]#
[root@c2 passt]# /usr/local/bin/passt --version
passt 2025_09_19.623dbf6-8-gc71313a
Copyright Red Hat
GNU General Public License, version 2 or later
  <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
```
[urbackup@c2 ~]$ podman run --rm --replace -d --name urbackup2   --network pasta:--map-gw -p 8880:55414   docker.io/uroni/urbackup-server:latest
cbecf796e6b8e9cd5233b021f13300d8ae9f2a1d90859cdda73067e08292d452
[urbackup@c2 ~]$ podman info | egrep 'passt|pasta'
  pasta:
    executable: /usr/local/bin/pasta
      pasta 2025_09_19.623dbf6-8-gc71313a
  rootlessNetworkCmd: pasta
  - passthrough
[urbackup@c2 ~]$
```
Either this patch didn't fix it or the patch isn't properly applied/pasta didn't install correctly from the make install?
```
[root@manage ~]# seq 0 100 | xargs -n1 sh -c "curl --http1.1 -v http://192.168.10.102:8880/css/bootstrap.chash-2f624089c65f12185e79925bc5a7fc42.min.css -o /tmp/ur-pasta-keep.css -w '\nsize_download=%{size_download}\n\n'" 2>&1 | grep size_download | sort | uniq -c
      1 size_download=108600
      7 size_download=109552
     12 size_download=109868
      2 size_download=111496
      1 size_download=113856
      1 size_download=114212
      1 size_download=115840
      2 size_download=117108
      2 size_download=118240
      4 size_download=118736
      4 size_download=120004
      2 size_download=120184
     62 size_download=121260
[root@manage ~]#
```

Just to make sure I'm not crazy:
```
[urbackup@c2 ~]$ podman run --rm --replace -d --name urbackup2   --network slirp4netns -p 8880:55414   docker.io/uroni/urbackup-server:latest
08cdd69e3bb959e18c79894d6c6586decb50b7b7b1c00d8f4e8904a5a9a2facb
[urbackup@c2 ~]$
```

```
[root@manage ~]# seq 0 100 | xargs -n1 sh -c "curl --http1.1 -v http://192.168.10.102:8880/css/bootstrap.chash-2f624089c65f12185e79925bc5a7fc42.min.css -o /tmp/ur-pasta-keep.css -w '\nsize_download=%{size_download}\n\n'" 2>&1 | grep size_download | sort | uniq -c
    101 size_download=121260
[root@manage ~]#
```
Yep, switching to slirp4netns fixes it.

**Comment by sbrivio-rh** [comment]
> Did you do that from another host on the same network? I could only reproduce this from a different host.

Oops, I missed this detail. I used the same host. Indeed, I was wondering where that latency (no data acknowledged socket-side for ~9ms) came from. I can probably introduce some delay and check again, but in any case, the patch should fix the issue(s).

**Comment by sbrivio-rh** [comment]
> Either this patch didn't fix it or the patch isn't properly applied/pasta didn't install correctly from the make install?

Meh. No, it looks like it's installed correctly from your `podman info` excerpt. There must be some other issue then. I'll try to reproduce it by adding a bit of latency as I mentioned.

**Comment by hakong** [comment]
Ok, yeah. I just made sure:

```
[root@c2 passt]# rpm -q passt
passt-gf4729be-1.x86_64
[root@c2 passt]# rpm -e --nodeps passt
[root@c2 passt]# rpm -q passt
package passt is not installed
[root@c2 passt]# make uninstall
rm -f /usr/local/bin/passt /usr/local/bin/passt.avx2 /usr/local/bin/pasta /usr/local/bin/pasta.avx2 /usr/local/bin/qrap /usr/local/bin/passt-repair
rm -f /usr/local/share/man/man1/passt.1 /usr/local/share/man/man1/pasta.1 /usr/local/share/man/man1/qrap.1 /usr/local/share/man/man1/passt-repair.1
rm -f /usr/local/share/doc/passt/README.md
rm -f /usr/local/share/doc/passt/demo.sh
rmdir /usr/local/share/doc/passt
[root@c2 passt]# make install
mkdir -p /usr/local/bin /usr/local/share/man/man1
cp -d passt passt.avx2 pasta pasta.avx2 qrap passt-repair /usr/local/bin
cp -d passt.1 pasta.1 qrap.1 passt-repair.1 /usr/local/share/man/man1
mkdir -p /usr/local/share/doc/passt
cp -d README.plain.md /usr/local/share/doc/passt/README.md
cp -d doc/demo.sh /usr/local/share/doc/passt
[root@c2 passt]#
[root@c2 passt]#
[root@c2 passt]# reboot
```

```
[urbackup@c2 ~]$ podman run --rm --replace -d --name urbackup2   --network pasta:--map-gw -p 8880:55414   docker.io/uroni/urbackup-server:latest
0a9481f794cc3073d7b0a02c727726909505aff28abbb9ecfbe9de030efb278d
[urbackup@c2 ~]$ podman info | egrep 'passt|pasta'
  pasta:
    executable: /usr/local/bin/pasta
      pasta 2025_09_19.623dbf6-8-gc71313a
  rootlessNetworkCmd: pasta
  - passthrough
[urbackup@c2 ~]$ /usr/local/bin/pasta --version
pasta 2025_09_19.623dbf6-8-gc71313a
Copyright Red Hat
GNU General Public License, version 2 or later
  <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

```
[root@manage ~]# seq 0 100 | xargs -n1 sh -c "curl --http1.1 -v http://192.168.10.102:8880/css/bootstrap.chash-2f624089c65f12185e79925bc5a7fc42.min.css -o /tmp/ur-pasta-keep.css -w '\nsize_download=%{size_download}\n\n'" 2>&1 | grep size_download | sort | uniq -c
      3 size_download=108600
      2 size_download=109552
     12 size_download=109868
      1 size_download=111496
      1 size_download=113896
      1 size_download=116464
      1 size_download=116792
      2 size_download=117108
      4 size_download=118240
      3 size_download=118736
      1 size_download=119688
      4 size_download=120004
      1 size_download=120184
     65 size_download=121260
[root@manage ~]#
```

**Comment by cevich** [comment]
I believe I'm hitting this as well on an internal web-based service running on a RHEL 9 host.

podman-5.4.0-12.el9_6.x86_64
passt-0^20250217.ga1e48a0-10.el9_6.x86_64

Though our reproducer is quite a bit more complex, the symptoms appear the same.  Our Apache logs show XYZ bytes being sent for a client request.  Then on the client side, a python tool is throwing an `incompleteRead` exception.  Attempting the same client-side request using curl, shows fewer than XYZ bytes being delivered before connection close.

Similarly, switching back to `slirp4netns` seems to resolve the issue.

**Comment by sbrivio-rh** [comment]
> I believe I'm hitting this as well on an internal web-based service running on a RHEL 9 host.
> 
> podman-5.4.0-12.el9_6.x86_64 passt-0^20250217.ga1e48a0-10.el9_6.x86_64

On those versions, the issue might actually be different.

> Though our reproducer is quite a bit more complex, the symptoms appear the same. Our Apache logs show XYZ bytes being sent for a client request. Then on the client side, a python tool is throwing an `incompleteRead` exception. Attempting the same client-side request using curl, shows fewer than XYZ bytes being delivered before connection close.

Thanks for the report. Actually, I just managed to reproduce this with the original UrBackup container reproducer, so I'm finally debugging this further. I "just" had to pick two hosts with approximately 10ms round-trip time between them (1ms as I tried first won't quite do it).

**Comment by cevich** [comment]
> I "just" had to pick two hosts with approximately 10ms round-trip time between them (1ms as I tried first won't quite do it).

Fascinating!  In our case as well, the problem seemed to mostly be affecting remote clients accessing our app over a VPN.

**Comment by sbrivio-rh** [comment]
> I just sent a [patch](https://archives.passt.top/passt-dev/20250930205132.885225-1-sbrivio@redhat.com/) for this, and the commit message explains the problem in detail.

It looks like I completely misinterpreted the issue: I thought we'd be sending a FIN segment with an acknowledgement sequence less than the sequence we actually received and queued to the socket (here, to the client).

It turns out, instead, that we actually have a short write to the socket (sendmsg() returning less than what we wrote), as the socket buffer is full, so we didn't accept those missing bytes, and it's correct that we don't acknowledge them, of course.

However, as we don't acknowledge them, we should ignore the FIN segment and not switch to the CLOSE-WAIT state right away: we need the server to send us that data again, and then send it on.

I just posted a [series](https://archives.passt.top/passt-dev/20251002000646.2136202-1-sbrivio@redhat.com/) fixing that, and a few minor assorted issues I found while investigating.

@hakong, would you be so kind as to re-test with that series? `b4 shazam` applies series as well, just drop the previous patch:

    git reset HEAD~1

and apply the new series instead:

    b4 shazam https://archives.passt.top/passt-dev/20251002000646.2136202-1-sbrivio@redhat.com/

then build, install, etc. Thanks.

**Comment by hakong** [comment]
```
[root@c2 ~]# rm -rf passt
[root@c2 ~]# git clone git://passt.top/passt
Cloning into 'passt'...
remote: Enumerating objects: 10337, done.
remote: Counting objects: 100% (10337/10337), done.
remote: Compressing objects: 100% (7165/7165), done.
remote: Total 10337 (delta 7462), reused 4293 (delta 3080), pack-reused 0
Receiving objects: 100% (10337/10337), 2.96 MiB | 7.05 MiB/s, done.
Resolving deltas: 100% (7462/7462), done.
[root@c2 ~]# cd passt/
[root@c2 passt]# b4 shazam https://archives.passt.top/passt-dev/20251002000646.2136202-1-sbrivio@redhat.com/
Looking up https://archives.passt.top/passt-dev/20251002000646.2136202-1-sbrivio@redhat.com
Grabbing thread from archives.passt.top/passt-dev/20251002000646.2136202-1-sbrivio@redhat.com/t.mbox.gz
Checking for newer revisions
Grabbing search results from lore.kernel.org
Nothing matching that query.
Analyzing 14 messages in the thread
Looking for additional code-review trailers on lore.kernel.org
Nothing matching that query.
Checking attestation on all messages, may take a moment...
---
  [PATCH 1/4] tcp: Fix ACK sequence on FIN to tap
    + Reviewed-by: David Gibson <david@gibson.dropbear.id.au> (✓ DKIM/gibson.dropbear.id.au)
  [PATCH 2/4] tcp: Completely ignore data segment in CLOSE-WAIT state, log a message
    + Reviewed-by: David Gibson <david@gibson.dropbear.id.au> (✓ DKIM/gibson.dropbear.id.au)
  [PATCH 3/4] tcp: Don't consider FIN flags with mismatching sequence
  [PATCH 4/4] tcp: On partial send (incomplete sendmsg()), request a retransmission right away
    + Reviewed-by: David Gibson <david@gibson.dropbear.id.au> (✓ DKIM/gibson.dropbear.id.au)
---
Total patches: 4
---
Applying: tcp: Fix ACK sequence on FIN to tap
Applying: tcp: Completely ignore data segment in CLOSE-WAIT state, log a message
Applying: tcp: Don't consider FIN flags with mismatching sequence
Applying: tcp: On partial send (incomplete sendmsg()), request a retransmission right away
[root@c2 passt]# make
[ ... wall of text ... ]
[root@c2 passt]# make install
mkdir -p /usr/local/bin /usr/local/share/man/man1
cp -d passt passt.avx2 pasta pasta.avx2 qrap passt-repair /usr/local/bin
cp -d passt.1 pasta.1 qrap.1 passt-repair.1 /usr/local/share/man/man1
mkdir -p /usr/local/share/doc/passt
cp -d README.plain.md /usr/local/share/doc/passt/README.md
cp -d doc/demo.sh /usr/local/share/doc/passt
[root@c2 passt]#
```

```
[root@c2 passt]# rpm -qa|grep passt
[root@c2 passt]# rpm -qa|grep pasta
[root@c2 passt]# machinectl shell urbackup@
Connected to the local host. Press ^] three times within 1s to exit session.
[urbackup@c2 ~]$ podman run --rm --replace -d --name urbackup2   --network pasta:--map-gw -p 8880:55414   docker.io/uroni/urbackup-server:latest
b5c764cea706396b6024f29116f1ebb2b1daee8eb9311c393e278b0eb25d5476
[urbackup@c2 ~]$ podman ps
CONTAINER ID  IMAGE                                   COMMAND     CREATED        STATUS        PORTS                                                                      NAMES
8a133e595585  docker.io/uroni/urbackup-server:latest  run         2 days ago     Up 2 days     0.0.0.0:35623->35623/tcp, 0.0.0.0:55413-55415->55413-55415/tcp, 35623/udp  urbackup
b5c764cea706  docker.io/uroni/urbackup-server:latest  run         4 seconds ago  Up 4 seconds  0.0.0.0:8880->55414/tcp, 55413/tcp, 55415/tcp, 35623/udp                   urbackup2
[urbackup@c2 ~]$ podman info | egrep 'passt|pasta'
  pasta:
    executable: /usr/local/bin/pasta
      pasta 2025_09_19.623dbf6-11-g75ff050
  rootlessNetworkCmd: pasta
  - passthrough
[urbackup@c2 ~]$
```

```
[root@manage ~]# seq 0 100 | xargs -n1 sh -c "curl --http1.1 -v http://192.168.10.102:8880/css/bootstrap.chash-2f624089c65f12185e79925bc5a7fc42.min.css -o /
tmp/ur-pasta-keep.css -w '\nsize_download=%{size_download}\n\n'" 2>&1 | grep size_download | sort | uniq -c
    101 size_download=121260
[root@manage ~]#
```

Looks fixed in this patch! Thanks.

**Comment by sbrivio-rh** [comment]
> Looks fixed in this patch! Thanks.

Thanks for testing! I'll report back here once we release the fix.

**Comment by sbrivio-rh** [comment]
This is now fixed in passt [2025_12_09.c3f1ba7](https://archives.passt.top/passt-user/20251209040527.1abdd27d@elisabeth), so I guess we can finally close this. Please reopen if needed.
