### ISSUE TITLE
Podman fails to run container with userns=keep-id

### ISSUE THREAD

**Issue by Erouan50** [containers/podman#27785]
### Issue Description

I'm trying to use the option `--userns=keep-id` to map my user with the container user, but the container fails to start with the following message:

```
Error: crun: readlink ``: No such file or directory: OCI runtime attempted to invoke a command that was not found
```

### Steps to reproduce the issue

Steps to reproduce the issue
1. Execute `podman run -d --userns=keep-id --rm ubi9 sleep 100`

### Describe the results you received

The command fails with the following message: 

```Error: crun: readlink ``: No such file or directory: OCI runtime attempted to invoke a command that was not found```

### Describe the results you expected

The container should starts without error and adds an entry for the user into the containers /etc/passwd file.

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.42.2
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.13-1.fc42.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.13, commit: '
  cpuUtilization:
    idlePercent: 92.34
    systemPercent: 1.72
    userPercent: 5.94
  cpus: 16
  databaseBackend: sqlite
  distribution:
    distribution: fedora
    variant: sway
    version: "42"
  emulatedArchitectures:
  - linux/arm
  - linux/arm64
  - linux/arm64be
  - linux/loong64
  - linux/mips
  - linux/mips64
  - linux/ppc
  - linux/ppc64
  - linux/ppc64le
  - linux/riscv32
  - linux/riscv64
  - linux/s390x
  eventLogger: journald
  freeLocks: 2038
  hostname: AROUAZE-LX
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 524288
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 524288
      size: 65536
  kernel: 6.17.11-200.fc42.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 1078149120
  memTotal: 33348968448
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.17.0-1.fc42.x86_64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.17.0
    package: netavark-1.17.0-1.fc42.x86_64
    path: /usr/libexec/podman/netavark
    version: netavark 1.17.0
  ociRuntime:
    name: crun
    package: crun-1.25.1-1.fc42.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.25.1
      commit: 156ae065d4a322d149c7307034f98d9637aa92a2
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20250919.g623dbf6-1.fc42.x86_64
    version: |
      pasta 0^20250919.g623dbf6-1.fc42.x86_64
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 2086604800
  swapTotal: 8589930496
  uptime: 27h 40m 10.00s (Approximately 1.12 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
store:
  configFile: /home/antoine.rouaze/.config/containers/storage.conf
  containerStore:
    number: 6
    paused: 0
    running: 0
    stopped: 6
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/antoine.rouaze/.local/share/containers/storage
  graphRootAllocated: 510389125120
  graphRootUsed: 456864014336
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 3
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/antoine.rouaze/.local/share/containers/storage/volumes
version:
  APIVersion: 5.7.1
  BuildOrigin: Fedora Project
  Built: 1765324800
  BuiltTime: Tue Dec  9 19:00:00 2025
  GitCommit: f845d14e941889ba4c071f35233d09b29d363c75
  GoVersion: go1.24.10
  Os: linux
  OsArch: linux/amd64
  Version: 5.7.1
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

**Comment by ninja-quokka** [comment]
Hey @Erouan50 

I can't seem to reproduce this on 5.6.2 or tip of main branch.
```shell
❯ podman run --userns=keep-id --rm ubi9 id
uid=1000(ldenny) gid=1000(ldenny) groups=1000(ldenny)

❯ podman run -d --userns=keep-id --rm ubi9 sleep 100
6ae8c9070eea2ef8a7d8836a25531ac2fe55419a79b688068b3685c67c8977ae
```

I'm not sure what the issue could be by maybe there is an issue with the container image cached on your machine? Can you reproduce with other containers? Can you reproduce if you delete the image and pull it again?

**Comment by Erouan50** [comment]
Hey @ninja-quokka,

I deleted the whole `~/.local/share/containers/` directory to be sure, and I still have the same issue with this image or any other one:

```
~> podman run --userns=keep-id --rm ubi9 id
Resolved "ubi9" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull registry.access.redhat.com/ubi9:latest...
Getting image source signatures
Checking if image destination supports signatures
Copying blob d9ce76bfbf66 done   |
Copying config d60669a3ae done   |
Writing manifest to image destination
Storing signatures
Error: crun: readlink ``: No such file or directory: OCI runtime attempted to invoke a command that was not found
```
Debian:
```
~> podman run --userns=keep-id --rm debian id
Resolved "debian" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull docker.io/library/debian:latest...
Getting image source signatures
Copying blob 2981f7e8980b done   |
Copying config 910a89191f done   |
Writing manifest to image destination
Error: crun: readlink ``: No such file or directory: OCI runtime attempted to invoke a command that was not found
```
**Edit:** I quickly created a virtual machine Fedora 42 and install podman on it, no issue... There is definitely something wrong on my laptop. I'm trying to run crun manually to check the problem, but I'm lost. Do you have a step by step procedure that I could try?

**Comment by ninja-quokka** [comment]
Hi @Erouan50 

You can try running with debug logging to see any any hints are printed: `--log-level=debug`

You can try using runc rather than crun to see if you can isolate the issue to crun: `--runtime runc`

If you can, you could try running [podman system reset](https://docs.podman.io/en/stable/markdown/podman-system-reset.1.html)  - note this will remove any Podman you have created.

If that doesn't help I would try reinstalling Podman and report back :)

**Comment by Erouan50** [comment]
Hi @ninja-quokka,

I'm am so sorry for the late answer.

> You can try running with debug logging to see any any hints are printed: --log-level=debug

Here are the debug logs:

```
INFO[0000] podman filtering at log level debug
DEBU[0000] Called run.PersistentPreRunE(podman --log-level=debug run --userns=keep-id --rm ubi9 id)
INFO[0000] Setting parallel job count to 49
DEBU[0000] Using conmon: "/usr/bin/conmon"
INFO[0000] Using sqlite as database backend
DEBU[0000] Using graph driver overlay
DEBU[0000] Using graph root /home/antoine.rouaze/.local/share/containers/storage
DEBU[0000] Using run root /run/user/1000/containers
DEBU[0000] Using static dir /home/antoine.rouaze/.local/share/containers/storage/libpod
DEBU[0000] Using tmp dir /run/user/1000/libpod/tmp
DEBU[0000] Using volume path /home/antoine.rouaze/.local/share/containers/storage/volumes
DEBU[0000] Using transient store: false
DEBU[0000] [graphdriver] trying provided driver "overlay"
DEBU[0000] Cached value indicated that overlay is supported
DEBU[0000] Cached value indicated that overlay is supported
DEBU[0000] Cached value indicated that metacopy is not being used
DEBU[0000] Cached value indicated that native-diff is usable
DEBU[0000] backingFs=btrfs, projectQuotaSupported=false, useNativeDiff=true, usingMetacopy=false
DEBU[0000] Initializing event backend journald
DEBU[0000] Configured OCI runtime crun-vm initialization failed: no valid executable found for OCI runtime crun-vm: invalid argument
DEBU[0000] Configured OCI runtime crun-wasm initialization failed: no valid executable found for OCI runtime crun-wasm: invalid argument
DEBU[0000] Configured OCI runtime runj initialization failed: no valid executable found for OCI runtime runj: invalid argument
DEBU[0000] Configured OCI runtime kata initialization failed: no valid executable found for OCI runtime kata: invalid argument
DEBU[0000] Configured OCI runtime runsc initialization failed: no valid executable found for OCI runtime runsc: invalid argument
DEBU[0000] Configured OCI runtime youki initialization failed: no valid executable found for OCI runtime youki: invalid argument
DEBU[0000] Configured OCI runtime krun initialization failed: no valid executable found for OCI runtime krun: invalid argument
DEBU[0000] Configured OCI runtime ocijail initialization failed: no valid executable found for OCI runtime ocijail: invalid argument
DEBU[0000] Using OCI runtime "/usr/bin/crun"
DEBU[0000] Pulling image ubi9 (policy: missing)
DEBU[0000] Looking up image "ubi9" in local containers storage
DEBU[0000] Normalized platform linux/amd64 to {amd64 linux  [] }
DEBU[0000] Loading registries configuration "/etc/containers/registries.conf"
DEBU[0000] Loading registries configuration "/etc/containers/registries.conf.d/000-shortnames.conf"
DEBU[0000] Trying "registry.access.redhat.com/ubi9:latest" ...
DEBU[0000] parsed reference into "[overlay@/home/antoine.rouaze/.local/share/containers/storage+/run/user/1000/containers]@d1a270d60e90c029c9a2576f61d3cf397e930c9c50d2d567cdbd4f2b732318a6"
DEBU[0000] Found image "ubi9" as "registry.access.redhat.com/ubi9:latest" in local containers storage
DEBU[0000] Found image "ubi9" as "registry.access.redhat.com/ubi9:latest" in local containers storage ([overlay@/home/antoine.rouaze/.local/share/containers/storage+/run/user/1000/containers]@d1a270d60e90c029c9a2576f61d3cf397e930c9c50d2d567cdbd4f2b732318a6)
DEBU[0000] exporting opaque data as blob "sha256:d1a270d60e90c029c9a2576f61d3cf397e930c9c50d2d567cdbd4f2b732318a6"
DEBU[0000] Looking up image "ubi9" in local containers storage
DEBU[0000] Normalized platform linux/amd64 to {amd64 linux  [] }
DEBU[0000] Trying "registry.access.redhat.com/ubi9:latest" ...
DEBU[0000] parsed reference into "[overlay@/home/antoine.rouaze/.local/share/containers/storage+/run/user/1000/containers]@d1a270d60e90c029c9a2576f61d3cf397e930c9c50d2d567cdbd4f2b732318a6"
DEBU[0000] Found image "ubi9" as "registry.access.redhat.com/ubi9:latest" in local containers storage
DEBU[0000] Found image "ubi9" as "registry.access.redhat.com/ubi9:latest" in local containers storage ([overlay@/home/antoine.rouaze/.local/share/containers/storage+/run/user/1000/containers]@d1a270d60e90c029c9a2576f61d3cf397e930c9c50d2d567cdbd4f2b732318a6)
DEBU[0000] exporting opaque data as blob "sha256:d1a270d60e90c029c9a2576f61d3cf397e930c9c50d2d567cdbd4f2b732318a6"
DEBU[0000] Inspecting image d1a270d60e90c029c9a2576f61d3cf397e930c9c50d2d567cdbd4f2b732318a6
DEBU[0000] exporting opaque data as blob "sha256:d1a270d60e90c029c9a2576f61d3cf397e930c9c50d2d567cdbd4f2b732318a6"
DEBU[0000] exporting opaque data as blob "sha256:d1a270d60e90c029c9a2576f61d3cf397e930c9c50d2d567cdbd4f2b732318a6"
DEBU[0000] Inspecting image d1a270d60e90c029c9a2576f61d3cf397e930c9c50d2d567cdbd4f2b732318a6
DEBU[0000] Inspecting image d1a270d60e90c029c9a2576f61d3cf397e930c9c50d2d567cdbd4f2b732318a6
DEBU[0000] Inspecting image d1a270d60e90c029c9a2576f61d3cf397e930c9c50d2d567cdbd4f2b732318a6
DEBU[0000] using systemd mode: false
DEBU[0000] No hostname set; container's hostname will default to runtime default
DEBU[0000] Loading seccomp profile from "/usr/share/containers/seccomp.json"
DEBU[0000] Allocated lock 0 for container 6086e9015ee05e448805324ef149ad25b39fb4c680336a001948cc9fe9a961a7
DEBU[0000] exporting opaque data as blob "sha256:d1a270d60e90c029c9a2576f61d3cf397e930c9c50d2d567cdbd4f2b732318a6"
DEBU[0000] Cached value indicated that idmapped mounts for overlay are not supported
DEBU[0000] Check for idmapped mounts support
DEBU[0000] Created container "6086e9015ee05e448805324ef149ad25b39fb4c680336a001948cc9fe9a961a7"
DEBU[0000] Container "6086e9015ee05e448805324ef149ad25b39fb4c680336a001948cc9fe9a961a7" has work directory "/home/antoine.rouaze/.local/share/containers/storage/overlay-containers/6086e9015ee05e448805324ef149ad25b39fb4c680336a001948cc9fe9a961a7/userdata"
DEBU[0000] Container "6086e9015ee05e448805324ef149ad25b39fb4c680336a001948cc9fe9a961a7" has run directory "/run/user/1000/containers/overlay-containers/6086e9015ee05e448805324ef149ad25b39fb4c680336a001948cc9fe9a961a7/userdata"
DEBU[0000] Not attaching to stdin
INFO[0000] Received shutdown.Stop(), terminating!        PID=76161
DEBU[0000] Enabling signal proxying
DEBU[0000] Cached value indicated that volatile is being used
DEBU[0000] overlay: mount_data=lowerdir=/home/antoine.rouaze/.local/share/containers/storage/overlay/l/DBVUHPRCWJM6FXXKIMGQDBUUYG:/home/antoine.rouaze/.local/share/containers/storage/overlay/l/DBVUHPRCWJM6FXXKIMGQDBUUYG/../diff1:/home/antoine.rouaze/.local/share/containers/storage/overlay/l/MJUCQYQ3WEGUXMF2B4QLRJ2RYF,upperdir=/home/antoine.rouaze/.local/share/containers/storage/overlay/d358661f16023724b4daa61ec930c462f5a0c2bc9ae5e6732313a18aa9873a6d/diff,workdir=/home/antoine.rouaze/.local/share/containers/storage/overlay/d358661f16023724b4daa61ec930c462f5a0c2bc9ae5e6732313a18aa9873a6d/work,userxattr,volatile,context="system_u:object_r:container_file_t:s0:c247,c583"
DEBU[0000] Mounted container "6086e9015ee05e448805324ef149ad25b39fb4c680336a001948cc9fe9a961a7" at "/home/antoine.rouaze/.local/share/containers/storage/overlay/d358661f16023724b4daa61ec930c462f5a0c2bc9ae5e6732313a18aa9873a6d/merged"
DEBU[0000] Created root filesystem for container 6086e9015ee05e448805324ef149ad25b39fb4c680336a001948cc9fe9a961a7 at /home/antoine.rouaze/.local/share/containers/storage/overlay/d358661f16023724b4daa61ec930c462f5a0c2bc9ae5e6732313a18aa9873a6d/merged
DEBU[0000] Modifying container 6086e9015ee05e448805324ef149ad25b39fb4c680336a001948cc9fe9a961a7 /etc/passwd
DEBU[0000] Modifying container 6086e9015ee05e448805324ef149ad25b39fb4c680336a001948cc9fe9a961a7 /etc/group
DEBU[0000] /proc/sys/crypto/fips_enabled does not contain '1', not adding FIPS mode bind mounts
DEBU[0000] Setting Cgroups for container 6086e9015ee05e448805324ef149ad25b39fb4c680336a001948cc9fe9a961a7 to user.slice:libpod:6086e9015ee05e448805324ef149ad25b39fb4c680336a001948cc9fe9a961a7
DEBU[0000] reading hooks from /usr/share/containers/oci/hooks.d
DEBU[0000] Workdir "/" resolved to host path "/home/antoine.rouaze/.local/share/containers/storage/overlay/d358661f16023724b4daa61ec930c462f5a0c2bc9ae5e6732313a18aa9873a6d/merged"
DEBU[0000] Created OCI spec for container 6086e9015ee05e448805324ef149ad25b39fb4c680336a001948cc9fe9a961a7 at /home/antoine.rouaze/.local/share/containers/storage/overlay-containers/6086e9015ee05e448805324ef149ad25b39fb4c680336a001948cc9fe9a961a7/userdata/config.json
DEBU[0000] /usr/bin/conmon messages will be logged to syslog
DEBU[0000] running conmon: /usr/bin/conmon               args="[--api-version 1 -c 6086e9015ee05e448805324ef149ad25b39fb4c680336a001948cc9fe9a961a7 -u 6086e9015ee05e448805324ef149ad25b39fb4c680336a001948cc9fe9a961a7 -r /usr/bin/crun -b /home/antoine.rouaze/.local/share/containers/storage/overlay-containers/6086e9015ee05e448805324ef149ad25b39fb4c680336a001948cc9fe9a961a7/userdata -p /run/user/1000/containers/overlay-containers/6086e9015ee05e448805324ef149ad25b39fb4c680336a001948cc9fe9a961a7/userdata/pidfile -n friendly_babbage --exit-dir /run/user/1000/libpod/tmp/exits --persist-dir /run/user/1000/libpod/tmp/persist/6086e9015ee05e448805324ef149ad25b39fb4c680336a001948cc9fe9a961a7 --full-attach -s -l journald --log-level debug --syslog --conmon-pidfile /run/user/1000/containers/overlay-containers/6086e9015ee05e448805324ef149ad25b39fb4c680336a001948cc9fe9a961a7/userdata/conmon.pid --exit-command /usr/bin/podman --exit-command-arg --root --exit-command-arg /home/antoine.rouaze/.local/share/containers/storage --exit-command-arg --runroot --exit-command-arg /run/user/1000/containers --exit-command-arg --log-level --exit-command-arg debug --exit-command-arg --cgroup-manager --exit-command-arg systemd --exit-command-arg --tmpdir --exit-command-arg /run/user/1000/libpod/tmp --exit-command-arg --network-config-dir --exit-command-arg  --exit-command-arg --network-backend --exit-command-arg netavark --exit-command-arg --volumepath --exit-command-arg /home/antoine.rouaze/.local/share/containers/storage/volumes --exit-command-arg --db-backend --exit-command-arg sqlite --exit-command-arg --transient-store=false --exit-command-arg --hooks-dir --exit-command-arg /usr/share/containers/oci/hooks.d --exit-command-arg --runtime --exit-command-arg crun --exit-command-arg --storage-driver --exit-command-arg overlay --exit-command-arg --events-backend --exit-command-arg journald --exit-command-arg --syslog --exit-command-arg container --exit-command-arg cleanup --exit-command-arg --stopped-only --exit-command-arg --rm --exit-command-arg 6086e9015ee05e448805324ef149ad25b39fb4c680336a001948cc9fe9a961a7]"
INFO[0000] Running conmon under slice user.slice and unitName libpod-conmon-6086e9015ee05e448805324ef149ad25b39fb4c680336a001948cc9fe9a961a7.scope
[conmon:d]: failed to write to /proc/self/oom_score_adj: Permission denied

DEBU[0000] Received: -1
DEBU[0000] Cleaning up container 6086e9015ee05e448805324ef149ad25b39fb4c680336a001948cc9fe9a961a7
DEBU[0000] Network is already cleaned up, skipping...
DEBU[0000] Unmounted container "6086e9015ee05e448805324ef149ad25b39fb4c680336a001948cc9fe9a961a7"
DEBU[0000] Removing container 6086e9015ee05e448805324ef149ad25b39fb4c680336a001948cc9fe9a961a7
DEBU[0000] Cleaning up container 6086e9015ee05e448805324ef149ad25b39fb4c680336a001948cc9fe9a961a7
DEBU[0000] Network is already cleaned up, skipping...
DEBU[0000] Container 6086e9015ee05e448805324ef149ad25b39fb4c680336a001948cc9fe9a961a7 storage is already unmounted, skipping...
DEBU[0000] Removing all exec sessions for container 6086e9015ee05e448805324ef149ad25b39fb4c680336a001948cc9fe9a961a7
DEBU[0000] Container 6086e9015ee05e448805324ef149ad25b39fb4c680336a001948cc9fe9a961a7 storage is already unmounted, skipping...
DEBU[0000] Temp dir already cleaned up
DEBU[0000] ExitCode msg: "crun: readlink ``: no such file or directory: oci runtime attempted to invoke a command that was not found"
Error: crun: readlink ``: No such file or directory: OCI runtime attempted to invoke a command that was not found
DEBU[0000] Shutting down engines
```

> You can try using runc rather than crun to see if you can isolate the issue to crun: --runtime runc

I tried (after exec `podman system reset`), but I get a permission denied:

```
~> podman --runtime runc run --userns=keep-id --rm ubi9  id
Resolved "ubi9" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull registry.access.redhat.com/ubi9:latest...
Getting image source signatures
Checking if image destination supports signatures
Copying blob 34b5c851d9cf done   |
Copying config d73ae4233d done   |
Writing manifest to image destination
Storing signatures
Error: runc: runc create failed: unable to start container process: error during container init: error preparing rootfs: remount-private dst=/home/antoine.rouaze/.local/share/containers/storage/overlay/bb0d46aa7970905a92d5fa33b869dca01fbd55bcf26066d1e351675a43ff320a/merged, flags=MS_PRIVATE: permission denied: OCI permission denied
```

> If you can, you could try running [podman system reset](https://docs.podman.io/en/stable/markdown/podman-system-reset.1.html) - note this will remove any Podman you have created.

Is still have the same issue.

> If that doesn't help I would try reinstalling Podman and report back :)

I uninstall podman with following command, and re-install it and I still have the same issue:

```
sudo dnf remove podman crun runc
```

Thank you for your help!

**Comment by thiago1255** [comment]
I had the same issue (the `Error: crun: readlink ``: No such file or directory: OCI runtime attempted to invoke a command that was not found` with keep-id) the problem seems to be the use of  `--root --runroot --tmpdir` tags...
Using podman 5.7.1 on archlinux.

**Comment by ninja-quokka** [comment]
@Erouan50 

Could you please try again with overriding the containers entrypoint?

```
podman run --log-level=debug --userns=keep-id --rm --entrypoint id ubi9
```

**Comment by bakrhaso** [comment]
@ninja-quokka I have the same problem, here's my output from that.
<details>
  <summary>Click to expand</summary>

```
[bkhs@fedora ~]$ podman run --log-level=debug --userns=keep-id --rm --entrypoint id ubi9
INFO[0000] podman filtering at log level debug
DEBU[0000] Called run.PersistentPreRunE(podman run --log-level=debug --userns=keep-id --rm --entrypoint id ubi9)
INFO[0000] Setting parallel job count to 49
DEBU[0000] Using conmon: "/usr/bin/conmon"
INFO[0000] Using sqlite as database backend
DEBU[0000] Using graph driver overlay
DEBU[0000] Using graph root /home/bkhs/.local/share/containers/storage
DEBU[0000] Using run root /run/user/1000/containers
DEBU[0000] Using static dir /home/bkhs/.local/share/containers/storage/libpod
DEBU[0000] Using tmp dir /run/user/1000/libpod/tmp
DEBU[0000] Using volume path /home/bkhs/.local/share/containers/storage/volumes
DEBU[0000] Using transient store: false
DEBU[0000] [graphdriver] trying provided driver "overlay"
DEBU[0000] Cached value indicated that overlay is supported
DEBU[0000] Cached value indicated that overlay is supported
DEBU[0000] Cached value indicated that metacopy is not being used
DEBU[0000] Cached value indicated that native-diff is usable
DEBU[0000] backingFs=btrfs, projectQuotaSupported=false, useNativeDiff=true, usingMetacopy=false
DEBU[0000] Initializing event backend journald
DEBU[0000] Configured OCI runtime runj initialization failed: no valid executable found for OCI runtime runj: invalid argument
DEBU[0000] Configured OCI runtime youki initialization failed: no valid executable found for OCI runtime youki: invalid argument
DEBU[0000] Configured OCI runtime ocijail initialization failed: no valid executable found for OCI runtime ocijail: invalid argument
DEBU[0000] Configured OCI runtime kata initialization failed: no valid executable found for OCI runtime kata: invalid argument
DEBU[0000] Configured OCI runtime runsc initialization failed: no valid executable found for OCI runtime runsc: invalid argument
DEBU[0000] Configured OCI runtime krun initialization failed: no valid executable found for OCI runtime krun: invalid argument
DEBU[0000] Configured OCI runtime crun-vm initialization failed: no valid executable found for OCI runtime crun-vm: invalid argument
DEBU[0000] Configured OCI runtime crun-wasm initialization failed: no valid executable found for OCI runtime crun-wasm: invalid argument
DEBU[0000] Configured OCI runtime runc initialization failed: no valid executable found for OCI runtime runc: invalid argument
DEBU[0000] Using OCI runtime "/usr/bin/crun"
DEBU[0000] Pulling image ubi9 (policy: missing)
DEBU[0000] Looking up image "ubi9" in local containers storage
DEBU[0000] Normalized platform linux/amd64 to {amd64 linux  [] }
DEBU[0000] Loading registries configuration "/etc/containers/registries.conf"
DEBU[0000] Loading registries configuration "/etc/containers/registries.conf.d/000-shortnames.conf"
DEBU[0000] Trying "registry.access.redhat.com/ubi9:latest" ...
DEBU[0000] parsed reference into "[overlay@/home/bkhs/.local/share/containers/storage+/run/user/1000/containers]@c5a69007e1324da5aa67f1ad06af11151eb3f8091f586b219cbcb7f4764db72f"
DEBU[0000] Found image "ubi9" as "registry.access.redhat.com/ubi9:latest" in local containers storage
DEBU[0000] Found image "ubi9" as "registry.access.redhat.com/ubi9:latest" in local containers storage ([overlay@/home/bkhs/.local/share/containers/storage+/run/user/1000/containers]@c5a69007e1324da5aa67f1ad06af11151eb3f8091f586b219cbcb7f4764db72f)
DEBU[0000] exporting opaque data as blob "sha256:c5a69007e1324da5aa67f1ad06af11151eb3f8091f586b219cbcb7f4764db72f"
DEBU[0000] Looking up image "ubi9" in local containers storage
DEBU[0000] Normalized platform linux/amd64 to {amd64 linux  [] }
DEBU[0000] Trying "registry.access.redhat.com/ubi9:latest" ...
DEBU[0000] parsed reference into "[overlay@/home/bkhs/.local/share/containers/storage+/run/user/1000/containers]@c5a69007e1324da5aa67f1ad06af11151eb3f8091f586b219cbcb7f4764db72f"
DEBU[0000] Found image "ubi9" as "registry.access.redhat.com/ubi9:latest" in local containers storage
DEBU[0000] Found image "ubi9" as "registry.access.redhat.com/ubi9:latest" in local containers storage ([overlay@/home/bkhs/.local/share/containers/storage+/run/user/1000/containers]@c5a69007e1324da5aa67f1ad06af11151eb3f8091f586b219cbcb7f4764db72f)
DEBU[0000] exporting opaque data as blob "sha256:c5a69007e1324da5aa67f1ad06af11151eb3f8091f586b219cbcb7f4764db72f"
DEBU[0000] Inspecting image c5a69007e1324da5aa67f1ad06af11151eb3f8091f586b219cbcb7f4764db72f
DEBU[0000] exporting opaque data as blob "sha256:c5a69007e1324da5aa67f1ad06af11151eb3f8091f586b219cbcb7f4764db72f"
DEBU[0000] exporting opaque data as blob "sha256:c5a69007e1324da5aa67f1ad06af11151eb3f8091f586b219cbcb7f4764db72f"
DEBU[0000] Inspecting image c5a69007e1324da5aa67f1ad06af11151eb3f8091f586b219cbcb7f4764db72f
DEBU[0000] Inspecting image c5a69007e1324da5aa67f1ad06af11151eb3f8091f586b219cbcb7f4764db72f
DEBU[0000] Inspecting image c5a69007e1324da5aa67f1ad06af11151eb3f8091f586b219cbcb7f4764db72f
DEBU[0000] using systemd mode: false
DEBU[0000] No hostname set; container's hostname will default to runtime default
DEBU[0000] Loading seccomp profile from "/usr/share/containers/seccomp.json"
DEBU[0000] Allocated lock 0 for container fb792a344e251cd0f95965fe6b47b4ff7b26a18b99345c93a17a4645c577ca9e
DEBU[0000] exporting opaque data as blob "sha256:c5a69007e1324da5aa67f1ad06af11151eb3f8091f586b219cbcb7f4764db72f"
DEBU[0000] Cached value indicated that idmapped mounts for overlay are not supported
DEBU[0000] Check for idmapped mounts support
DEBU[0000] Created container "fb792a344e251cd0f95965fe6b47b4ff7b26a18b99345c93a17a4645c577ca9e"
DEBU[0000] Container "fb792a344e251cd0f95965fe6b47b4ff7b26a18b99345c93a17a4645c577ca9e" has work directory "/home/bkhs/.local/share/containers/storage/overlay-containers/fb792a344e251cd0f95965fe6b47b4ff7b26a18b99345c93a17a4645c577ca9e/userdata"
DEBU[0000] Container "fb792a344e251cd0f95965fe6b47b4ff7b26a18b99345c93a17a4645c577ca9e" has run directory "/run/user/1000/containers/overlay-containers/fb792a344e251cd0f95965fe6b47b4ff7b26a18b99345c93a17a4645c577ca9e/userdata"
DEBU[0000] Not attaching to stdin
INFO[0000] Received shutdown.Stop(), terminating!        PID=822745
DEBU[0000] Enabling signal proxying
DEBU[0000] Cached value indicated that volatile is being used
DEBU[0000] overlay: mount_data=lowerdir=/home/bkhs/.local/share/containers/storage/overlay/l/AWT5E4LC6CEINZR5TNBLKMSCST:/home/bkhs/.local/share/containers/storage/overlay/l/AWT5E4LC6CEINZR5TNBLKMSCST/../diff1:/home/bkhs/.local/share/containers/storage/overlay/l/WM72DGRM5N5Q7WACJCUFZDOVKX,upperdir=/home/bkhs/.local/share/containers/storage/overlay/c74606300e57853d818fe0b3bb3d5ddb7d9f8824804e33d313bd34d9a82141ce/diff,workdir=/home/bkhs/.local/share/containers/storage/overlay/c74606300e57853d818fe0b3bb3d5ddb7d9f8824804e33d313bd34d9a82141ce/work,userxattr,volatile,context="system_u:object_r:container_file_t:s0:c339,c539"
DEBU[0000] Mounted container "fb792a344e251cd0f95965fe6b47b4ff7b26a18b99345c93a17a4645c577ca9e" at "/home/bkhs/.local/share/containers/storage/overlay/c74606300e57853d818fe0b3bb3d5ddb7d9f8824804e33d313bd34d9a82141ce/merged"
DEBU[0000] Created root filesystem for container fb792a344e251cd0f95965fe6b47b4ff7b26a18b99345c93a17a4645c577ca9e at /home/bkhs/.local/share/containers/storage/overlay/c74606300e57853d818fe0b3bb3d5ddb7d9f8824804e33d313bd34d9a82141ce/merged
DEBU[0000] Modifying container fb792a344e251cd0f95965fe6b47b4ff7b26a18b99345c93a17a4645c577ca9e /etc/passwd
DEBU[0000] Modifying container fb792a344e251cd0f95965fe6b47b4ff7b26a18b99345c93a17a4645c577ca9e /etc/group
DEBU[0000] /proc/sys/crypto/fips_enabled does not contain '1', not adding FIPS mode bind mounts
DEBU[0000] Setting Cgroups for container fb792a344e251cd0f95965fe6b47b4ff7b26a18b99345c93a17a4645c577ca9e to user.slice:libpod:fb792a344e251cd0f95965fe6b47b4ff7b26a18b99345c93a17a4645c577ca9e
DEBU[0000] reading hooks from /usr/share/containers/oci/hooks.d
DEBU[0000] Workdir "/" resolved to host path "/home/bkhs/.local/share/containers/storage/overlay/c74606300e57853d818fe0b3bb3d5ddb7d9f8824804e33d313bd34d9a82141ce/merged"
DEBU[0000] Created OCI spec for container fb792a344e251cd0f95965fe6b47b4ff7b26a18b99345c93a17a4645c577ca9e at /home/bkhs/.local/share/containers/storage/overlay-containers/fb792a344e251cd0f95965fe6b47b4ff7b26a18b99345c93a17a4645c577ca9e/userdata/config.json
DEBU[0000] /usr/bin/conmon messages will be logged to syslog
DEBU[0000] running conmon: /usr/bin/conmon               args="[--api-version 1 -c fb792a344e251cd0f95965fe6b47b4ff7b26a18b99345c93a17a4645c577ca9e -u fb792a344e251cd0f95965fe6b47b4ff7b26a18b99345c93a17a4645c577ca9e -r /usr/bin/crun -b /home/bkhs/.local/share/containers/storage/overlay-containers/fb792a344e251cd0f95965fe6b47b4ff7b26a18b99345c93a17a4645c577ca9e/userdata -p /run/user/1000/containers/overlay-containers/fb792a344e251cd0f95965fe6b47b4ff7b26a18b99345c93a17a4645c577ca9e/userdata/pidfile -n eloquent_ardinghelli --exit-dir /run/user/1000/libpod/tmp/exits --persist-dir /run/user/1000/libpod/tmp/persist/fb792a344e251cd0f95965fe6b47b4ff7b26a18b99345c93a17a4645c577ca9e --full-attach -s -l journald --log-level debug --syslog --conmon-pidfile /run/user/1000/containers/overlay-containers/fb792a344e251cd0f95965fe6b47b4ff7b26a18b99345c93a17a4645c577ca9e/userdata/conmon.pid --exit-command /usr/bin/podman --exit-command-arg --root --exit-command-arg /home/bkhs/.local/share/containers/storage --exit-command-arg --runroot --exit-command-arg /run/user/1000/containers --exit-command-arg --log-level --exit-command-arg debug --exit-command-arg --cgroup-manager --exit-command-arg systemd --exit-command-arg --tmpdir --exit-command-arg /run/user/1000/libpod/tmp --exit-command-arg --network-config-dir --exit-command-arg  --exit-command-arg --network-backend --exit-command-arg netavark --exit-command-arg --volumepath --exit-command-arg /home/bkhs/.local/share/containers/storage/volumes --exit-command-arg --db-backend --exit-command-arg sqlite --exit-command-arg --transient-store=false --exit-command-arg --hooks-dir --exit-command-arg /usr/share/containers/oci/hooks.d --exit-command-arg --runtime --exit-command-arg crun --exit-command-arg --storage-driver --exit-command-arg overlay --exit-command-arg --events-backend --exit-command-arg journald --exit-command-arg --syslog --exit-command-arg container --exit-command-arg cleanup --exit-command-arg --stopped-only --exit-command-arg --rm --exit-command-arg fb792a344e251cd0f95965fe6b47b4ff7b26a18b99345c93a17a4645c577ca9e]"
[conmon:d]: failed to write to /proc/self/oom_score_adj: Permission denied

DEBU[0000] Received: -1
DEBU[0000] Cleaning up container fb792a344e251cd0f95965fe6b47b4ff7b26a18b99345c93a17a4645c577ca9e
DEBU[0000] Network is already cleaned up, skipping...
DEBU[0000] Unmounted container "fb792a344e251cd0f95965fe6b47b4ff7b26a18b99345c93a17a4645c577ca9e"
DEBU[0000] Removing container fb792a344e251cd0f95965fe6b47b4ff7b26a18b99345c93a17a4645c577ca9e
DEBU[0000] Cleaning up container fb792a344e251cd0f95965fe6b47b4ff7b26a18b99345c93a17a4645c577ca9e
DEBU[0000] Network is already cleaned up, skipping...
DEBU[0000] Container fb792a344e251cd0f95965fe6b47b4ff7b26a18b99345c93a17a4645c577ca9e storage is already unmounted, skipping...
DEBU[0000] Removing all exec sessions for container fb792a344e251cd0f95965fe6b47b4ff7b26a18b99345c93a17a4645c577ca9e
DEBU[0000] Container fb792a344e251cd0f95965fe6b47b4ff7b26a18b99345c93a17a4645c577ca9e storage is already unmounted, skipping...
DEBU[0000] Temp dir already cleaned up
DEBU[0000] ExitCode msg: "crun: readlink ``: no such file or directory: oci runtime attempted to invoke a command that was not found"
Error: crun: readlink ``: No such file or directory: OCI runtime attempted to invoke a command that was not found
DEBU[0000] Shutting down engines
```  
</details>

**Comment by mstarongithub** [comment]
> Could you please try again with overriding the containers entrypoint?

Same result for me (on my desktop, Fedora atomic cosmic, podman v5.7.1).

Weirdly enough, my laptop (fedora kde), with almost the exact same podman config, runs podman without any issues. The only differences in the info are down to hardware and the laptop having been in use longer (thus also more containers and images). conmon, crun, etc versions are the exact same

(Anecdotally, running without `--userns=keep-id` gives a memory protection error instead while trying to load shared libraries, again the weird difference between my laptop and my desktop)

**Comment by thiago1255** [comment]
> I had the same issue (the `` Error: crun: readlink ``: No such file or directory: OCI runtime attempted to invoke a command that was not found `` with keep-id) the problem seems to be the use of `--root --runroot --tmpdir` tags... Using podman 5.7.1 on archlinux.

It is now working with all, podman itself still on 5.7.1, but maybe updating other system components solved the issue ?

**Comment by Erouan50** [comment]
@ninja-quokka I have the same output as @bakrhaso when I update the entrypoint.

And unlike @mstarongithub (which is also weird :p), I don't have the issue when running the same command on a fresh new Fedora 42 Sway Spin virtual machine. I could reformat my laptop to "fix the issue", but I'd rather pass :).

@thiago1255 that's good news! Maybe the fix will be patched later in Fedora! Who knows.

**Comment by mstarongithub** [comment]
I've just done a quick test to see if I could easily reproduce the issue, but failed to do so (New virtual machine with base Fedora Atomic Cosmic edition, current iso and fully updated, both worked as expected). I'll assume that there's something cursed about my desktop system then and will try to find whatever the cause may be

**Comment by mstarongithub** [comment]
Update: Some part of my home dir breaks it. A freshly created user on the same system works just fine. New user seems to be using cgroupfs as cgroup manager and storing things in /tmp, while my main user uses systemd and storing in /run/user/\<id\>. No idea if that's relevant

**Comment by X2E4VXpZKv** [comment]
hi!
I've had what seems (?) to be the same issue (using distrobox containers). What fixed it for me was setting my home dir permissions to be readable by other users (from `drwx------` to `drwxr-xr-x`).

**Comment by Erouan50** [comment]
Holly 🐮! @X2E4VXpZKv you're my hero! It fixed the issue!

I'm curious, How did you manage to find that?

**Comment by X2E4VXpZKv** [comment]
From @mstarongithub 's last comment and dumb luck after an hour of trying things 😑 It might be your cwd being unreachable and not specifically the homedir? That would maybe make more sense.

**Comment by mstarongithub** [comment]
for me it also was funky permissions on the home dir (how did the owner group get changed to libvirtd?) Unreachable cwd seems to be a different (and much clearer) error
Thanks @X2E4VXpZKv for the find

**Comment by edsantiago** [comment]
Same problem seen on my Gentoo laptop (but not my Gentoo desktop). Resolved via `chmod 755 ~/.local/share/containers` (thanks, @X2E4VXpZKv ). 

`strace` suggests that the error is stemming from `safe_readlinkat([/proc/self/cwd],"")`:
```
fsopen("proc", FSOPEN_CLOEXEC)          = 14
fsmount(14, FSMOUNT_CLOEXEC, 0)         = 15
close(14)                               = 0
...
readlink("/home/esm/.local/share/containers", 0x7fffeb50ca90, 1023) = -1 EINVAL (Invalid argument)
readlink("/home/esm/.local/share/containers/storage", 0x7fffeb50ca90, 1023) = -1 EACCES (Permission denied)
openat(15, "self/cwd", O_RDONLY|O_CLOEXEC) = 14
readlinkat(14, "", 0x5594676a2ca0, 512) = -1 ENOENT (No such file or directory)
```
My desktop system works fine with `700`. I'm giving up on trying to figure out why.

PS hi!

**Comment by imammedo** [comment]
Reproduced on Fedora 43 with both packaged and upstream builds.

**Root cause analysis:**

The problem is `0700` home directory permissions (Fedora default, set via `HOME_MODE 0700` in `/etc/login.defs`). With `--userns=keep-id`, container UID 0 maps to a subordinate host UID (e.g., 100001) that can't traverse the user's home directory to reach the container rootfs under `~/.local/share/containers/storage/`.

Strace of the crun process inside the user namespace shows the exact failure in `resolve_rootfs_path()`:
```
readlink("/home", ...)                  = -1 EINVAL (Invalid argument)
readlink("/home/test_user", ...)        = -1 EINVAL (Invalid argument)
readlink("/home/test_user/.local", ...) = -1 EACCES (Permission denied)
readlinkat(15, "", ...)                 = -1 ENOENT (No such file or directory)
```

1. `realpath(def->root->path)` walks the path components. The first two return EINVAL (not symlinks — normal). The third fails with EACCES because the mapped UID can't traverse the `0700` home directory.
2. The fallback calls `safe_readlinkat(fd, "", ...)` which also fails with ENOENT.
3. The error is reported as `readlink ''` — the empty string is the `name` parameter passed to the error formatter, not the actual path being readlinked.

The problematic code in crun `src/libcrun/container.c` `resolve_rootfs_path()`:
```c
  *rootfs = realpath (def->root->path, NULL);
  if (UNLIKELY (*rootfs == NULL))
    {
      /* If realpath failed for any reason, try the relative directory.  */
      if (def->root->path[0] == '/')
        {
          ...
          len = safe_readlinkat (ret, "", &cwd, 0, err);
```

**Reproduced with upstream builds:**
- podman 6.0.0-dev (`7534429`)
- crun main (`347750a`)
- Kernel 6.19.11-200.fc43.x86_64, btrfs

**Workaround:** `chmod 701 ~`

**Impact on toolbox:** Toolbox hardcodes `--userns=keep-id` for non-root users, so this completely breaks `toolbox enter` on default Fedora installs. The toolbox error is even less informative: `Error: failed to start container fedora-toolbox-43`.

Additionally, the current error message `crun: readlink '': No such file or directory` is practically useless for diagnosing this problem. It would help a lot if crun or podman could detect the permission issue on the rootfs path and report it clearly, e.g. mentioning that the home directory permissions prevent the mapped user namespace UIDs from accessing the container storage.

**Comment by wdanilo** [comment]
Still reproducible on newer versions than the OP — podman **5.8.2** + crun **1.27.1** (commit `3ec076b3b6714ec2f1a10533cf18d5605a6de637`) — so at least here it wasn't fixed by updates.

The trigger is the **keep-id target UID — not the image or the command**. Minimal repro on stock `alpine:latest`:

```console
$ podman run --rm --userns=keep-id docker.io/library/alpine:latest true
Error: crun: readlink ``: No such file or directory: OCI runtime attempted to invoke a command that was not found

$ podman run --rm --userns=keep-id:uid=0,gid=0 docker.io/library/alpine:latest true
$ echo $?
0
```

Same behavior on `ubuntu:latest` and `mcr.microsoft.com/devcontainers/base:ubuntu`:

| `--userns` | result |
| --- | --- |
| `keep-id` (host UID → same UID) | ✗ `readlink ''` |
| `keep-id:uid=1000,gid=1000` | ✗ `readlink ''` |
| `keep-id:uid=0,gid=0` | ✓ works |
| *(no keep-id)* | ✓ works |

crun only succeeds when the host user maps to container **UID 0**; any non-zero target UID fails. The executable is irrelevant (`true`, `/bin/true`, `/usr/bin/true` all fail identically), so it's during container init — not exec / PATH resolution.

Extra data points:
- **Appears crun-specific** — running the same containers with `--runtime runc` does not produce the `readlink` error.
- **Not ID-range exhaustion** — `/etc/subuid` is `165536:65536` (65536 IDs); exhaustion produces a different `not enough unused IDs` error.
- **Storage location isn't the factor** — `uid=0` works on the exact same store that fails with the default mapping.

**Comment by wdanilo** [comment]
**Correction to my earlier comment — I got two key things wrong, apologies.**

I previously reported this as crun-specific (runc unaffected) and said storage location wasn't a factor. After a much longer investigation both claims turned out to be wrong, and my case appears to be **environment-specific**, so it may not be the same root cause as the OP's. Setting the record straight:

**1. Not crun-specific.** runc fails on the exact same setup, just with a different surface error:
```
runc: ... error preparing rootfs: remount-private dst=.../overlay/<hash>/merged, flags=MS_PRIVATE: permission denied
```
crun says `readlink ''`, runc says `MS_PRIVATE` — but they fail and succeed *together*. So this isn't a crun bug.

**2. It was storage layout/permissions, not the runtime or the UID.** On my setup (NixOS, rootless, btrfs, with a *relocated* store because `$HOME` is `0700`), the keep-id RUN failed for both runtimes, and what actually determined success was *where the graph root lived*:
- a store under `/var/lib/containers/...` failed even with a world-writable parent;
- a store whose entire ancestry was `≤0755` failed;
- a store **off** `/var/lib/containers` under a **`1777`** (sticky, world-writable) parent — the `/tmp` model — worked, for **both** crun and runc.

The `--userns=keep-id:uid=0` "workaround" several of us noted only worked because of this — it's a symptom, not the cause.

I couldn't tie this to a specific podman/crun/kernel change, and since keep-id + the default store works fine for the vast majority, **my failure is almost certainly something environment-specific** (NixOS / btrfs / the `0700` home / my relocation) rather than the OP's default-store scenario. So please treat this as an extra data point + a heads-up, not a diagnosis of #27785.

Two things that might still help triage here:
- **Try the other runtime** before concluding "crun bug" — if runc also fails (`MS_PRIVATE`), the runtime isn't the cause.
- **The graph root's path/permissions matter** — relocating it (e.g. under a `1777` parent like `/tmp`) is worth trying as a diagnostic.

**Comment by ninja-quokka** [comment]
Thanks for taking a look at this @wdanilo 

I had another crack at reproducing this issue without success.

Until we have a solid reproducer this issue is blocked.

**Comment by grisu48** [comment]
I think I found a reproducer. I can trigger this issue, when `~/.local/share` is not owned by the user group (gid=1000) but by some other group.

## Reproducer

Assume the user `phoenix (uid=1000, gid=1000)` and the following `Containerfile`:

```
FROM registry.opensuse.org/opensuse/tumbleweed
USER 1000:1000
CMD /bin/bash
```

Building the container and running it with default configuration works fine:

```
$ podman build . -t hase-hopp
$ podman run --rm --userns=keep-id -ti hase-hopp id
uid=1000(phoenix) gid=1000(phoenix) groups=1000(phoenix)
```

Now, if I do a `podman system reset` and change the group of `~/.local.share` to e.g. the group `users (gid=100)` then I can reproduce the issue:

```
$ podman system reset
$ rm -rf .local/share/containers      # ensure there are no remnant directories
$ sudo chgrp -R users /home/phoenix/.local/share

$ podman build . -t hase-hopp
$ podman run --rm --userns=keep-id -ti hase-hopp id
Error: container create failed (no logs from conmon): conmon bytes "": readObjectStart: expect { or n, but found , error found in #0 byte of ...||..., bigger context ...||...
$ podman run --rm --runtime crun --userns=keep-id -ti hase-hopp id
Error: crun: readlink ``: No such file or directory: OCI runtime attempted to invoke a command that was not found
```

So it looks like the `userns=keep-id` stumbles, when the container directories are not owned by the same gid.

**Comment by derekschrock** [comment]
I believe I had a user run into this today on EL8 and I was able to reproduce it on fully updated EL8 and Fedora 43. 

My simple test case it just changing ~/ group ownership:

```
[testing@podman ~]$ id 
uid=1001(testing) gid=1002(other) groups=1002(other),1001(testing) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
[testing@podman ~]$ ls -ld ~testing
drwx------. 5 testing testing 105 Jul 13 21:26 /home/testing
[testing@podman ~]$ podman run --userns=keep-id --rm hello-world
Error: crun: readlink ``: No such file or directory: OCI runtime attempted to invoke a command that was not found
[testing@podman ~]$ chgrp other ~
[testing@podman ~]$ podman run --userns=keep-id --rm hello-world
!... Hello Podman World ...!
...
```
       
Is this the same scenario as the other cases from above changing `~/.local/` data?

The error was mildly different on EL8  `OCI permission denied` vs the above.  I think that's just crun vs non-crun on EL8.

**Comment by grisu48** [comment]
> My simple test case it just changing ~/ group ownership:
> ...
> Is this the same scenario as the other cases from above changing `~/.local/` data?

My take is that if you change the group ownership recursively for the user's home directory, then yes. Here you will hit the same issue, where the `user-ns=keep-id` stumbles on unexpected group ownership settings.

**Comment by giuseppe** [comment]
the ugly error from crun was fixed upstream, it is caused by not having access to the rootfs once in the nested user namespace.

If some other groups own the directory, then that group won't be mapped inside the rootless user namespace so access by group is lost.

`CAP_DAC_OVERRIDE` in the username space is limited to the IDs that are mapped in the user namespace:

```c
 * privileged_wrt_inode_uidgid - Do capabilities in the namespace work over the inode?
 * @ns: The user namespace in question
 * @idmap: idmap of the mount @inode was found from
 * @inode: The inode in question
 *
 * Return true if the inode uid and gid are within the namespace.
 */
bool privileged_wrt_inode_uidgid(struct user_namespace *ns,
                                 struct mnt_idmap *idmap,
                                 const struct inode *inode)
{
        return vfsuid_has_mapping(ns, i_uid_into_vfsuid(idmap, inode)) &&
               vfsgid_has_mapping(ns, i_gid_into_vfsgid(idmap, inode));
}
```

Differently, if you don't do any additional user namespace nesting (what `--userns=keep-id` does) the root user in the user namespace has UID access to the path since your rootless user is mapped to `0`.

In other words, you either change group ownership to a GID that is mapped inside the user namespace or set `+x` to any parent directory.

**Comment by jpeeler** [comment]
Slightly off topic, but as a result of a similar issue I found that udisks2 will not mount with exec permissions by default (I think it also wouldn't accept exec as an option).  I used systemd-mount to configure the mount which enabled permissions such that moved paths for graphroot and rootless_storage_path would work.

Hopefully the new error message makes it a lot more obvious what the problem is.
