### ISSUE TITLE
Docker API /containers/{id}/archive

### ISSUE THREAD

**Issue by abitrolly** [containers/podman#6050]
/kind bug

Accessing `/containers/{id}/archive` on 1.9.1 gives 404. I guess it is not implemented yet.

https://docs.docker.com/engine/api/v1.38/#operation/ContainerArchive

**Comment by mheon** [comment]
Yep, a few remote endpoints (those for copy, exec, and I believe the network commands) are still being worked on.

**Comment by abitrolly** [comment]
@mheon can't wait for it to use https://github.com/buildpacks/pack/issues/564

**Comment by baude** [comment]
@abitrolly https://docs.docker.com/engine/api/v1.40/#operation/ContainerArchiveInfo is this what you are after?  if so, you are correct, this is a bug.  would you be willing to contribute?

**Comment by abitrolly** [comment]
I am not sure. While it seems pretty interesting, my motivation is still pretty low as I am not backed by any big company and on the personal scale I also won't be able to use it, because `podman` 2.0 is not ready, and API fixes are not backported to 1.9.x

**Comment by rhatdan** [comment]
@abitrolly Does the master branch work for you now?

**Comment by mheon** [comment]
This is not implemented yet. We added the endpoints, but they just throw "not implemented" errors for now.

Definitely on our radar, though, but will probably be combined with a rewrite of CLI `podman cp`

**Comment by mheon** [comment]
Changing to kind/feature as this is a new feature

**Comment by vrothberg** [comment]
@lsm5 are you interested in looking into it? I think we can start with adding a docker/compat endpoint first.

AFAIUI we have to mount the container and the archive the specified path inside the container and throw it back over the wire.

**Comment by mheon** [comment]
@vrothberg This is part of the copy work, so I'll be on this one once we're off bug week.

**Comment by vrothberg** [comment]
@mheon, sorry, I didn't notice you just self-assigned yesterday.

**Comment by yan12125** [comment]
I noticed that the API endpoint to upload an archive in Podman uses different HTTP method than the corresponding API in Docker. The former uses POST and the latter uses PUT. Is the difference intentional?

[1] https://docs.podman.io/en/latest/_static/api.html#operation/putArchive
[2] https://docs.docker.com/engine/api/v1.40/#operation/PutContainerArchive

**Comment by jwhonce** [comment]
@yan12125 That is a bug on podman's part.  /cc @mheon

**Comment by yan12125** [comment]
Thanks for the fix #7638. The HTTP methods are consistent with Docker now, but that endpoint still returns "501 Not Implemented" as of Podman 2.1.1.

**Comment by lcarva** [comment]
Is there a timeline for when this issue may be addressed? For context, this prevents [osbs](http://osbs.rtfd.org/) from switching away from docker to podman.

**Comment by rhatdan** [comment]
I take it that this is fixed in the main branch now, and you just are waiting for a release of podman 2.1.2 or 2.2 to get the fix?  If I am mistaken, please reopen this issue.

**Comment by lcarva** [comment]
> I take it that this is fixed in the main branch now, and you just are waiting for a release of podman 2.1.2 or 2.2 to get the fix? If I am mistaken, please reopen this issue.

@rhatdan, the previously mentioned fix was for changing the HTTP method to match what the docker API uses. IIUC, the API method is still returning 501 Not Implemented. Did I miss something?

**Comment by mheon** [comment]
This is not fixed, and will require significant effort to implement. There's a Jira card assigned to me for it, but I have other priorities at the moment.

**Comment by fatherlinux** [comment]
FYI, I just tried this with the pack cli and ran into the lack of the archive method. Specific log message here:
Oct 21 10:53:54 fedora podman[3101]: time="2020-10-21T10:53:54-04:00" level=debug msg="APIHandler -- Method: PUT URL: /v1.38/containers/416b79116c1e9b7e8409ef0bfc4224750143e35bf74b02c046627f045ecbfcb1/archive?noOverwriteDirNonDir=true&path=%2F"
Oct 21 10:53:54 fedora podman[3101]: time="2020-10-21T10:53:54-04:00" level=info msg="Request Failed(Not Implemented): not implemented"

Full log here:
https://pastebin.com/ft1YNwg8

**Comment by rhatdan** [comment]
@jwhonce Is this something you could look at?

**Comment by vrothberg** [comment]
Since https://github.com/containers/podman/pull/8126 has merged, we can close.  I am currently working on refactoring the backend so that `podman-{remote}-cp` and the docker and libpod endpoint share all code.

**Comment by abitrolly** [comment]
@vrothberg could that fix the issue https://github.com/buildpacks/pack/issues/966 with `pack`?

**Comment by vrothberg** [comment]
> @vrothberg could that fix the issue [buildpacks/pack#966](https://github.com/buildpacks/pack/issues/966) with `pack`?

@abitrolly, I do not see why the upper issue is failing. If it's only failing because the archive endpoint was missing, then it should be fixed.
