### ISSUE TITLE
Cannot access port from external IP when starting container using root access

### ISSUE THREAD

**Issue by Navdeepuniyal** [containers/podman#6139]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

Networking Bug: While starting a container using root access, the ports cannot be reached from an external IP.

**Description**

If we start a Podman container using root access, the exposed ports cannot be reached from an external IP address. On running the same container using non-root access, the ports are accessible.

**Steps to reproduce the issue:**

1. Login to non-root user: podman run -dit -p=8000:8000 --privileged --name coa apache:latest

2. Access <host_IP>:8000 from external IP (Reachable to host)

3. Remove the running container and login using the root user: podman run -dit -p=8000:8000 --privileged --name coa apache:latest

4. Try accessing <host_IP>:8000 

**Describe the results you received:**
Cannot reach the exposed port when container is running with root access
Can reach the exposed port when it is started with non root.

**Describe the results you expected:**
Same for both.

**Output of `podman version`:**
```
podman version 1.9.1
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  gitCommit: ""
  goVersion: go1.10.1
  podmanVersion: 1.9.1
host:
  arch: amd64
  buildahVersion: 1.14.8
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.15, commit: '
  cpus: 6
  distribution:
    distribution: ubuntu
    version: "18.04"
  eventLogger: file
  hostname: criu-dev-nav
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.15.0-99-generic
  memFree: 764792832
  memTotal: 6100402176
  ociRuntime:
    name: runc
    package: 'containerd.io: /usr/bin/runc'
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc10
      commit: dc9208a3303feef5b3839f4323d9beb36df0a9dd
      spec: 1.0.1-dev
  os: linux
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 0
  swapTotal: 0
  uptime: 99h 56m 17.7s (Approximately 4.12 days)
registries:
  search:
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 7
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/unknown,now 1.9.1~1 amd64 [installed]
```
**Additional details:**
IP Tables output: Command: iptables -t nat -nvL

With Root access: 

```
Chain PREROUTING (policy ACCEPT 1 packets, 129 bytes)
 pkts bytes target     prot opt in     out     source               destination
  457 23813 DOCKER     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL
  453 23560 CNI-HOSTPORT-DNAT  all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
    3   180 DOCKER     all  --  *      *       0.0.0.0/0           !127.0.0.0/8          ADDRTYPE match dst-type LOCAL
  603 39937 CNI-HOSTPORT-DNAT  all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL
Chain POSTROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
 1283 90471 CNI-HOSTPORT-MASQ  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* CNI portfwd requiring masquerade */
    0     0 MASQUERADE  all  --  *      !docker0  172.17.0.0/16        0.0.0.0/0
    0     0 CNI-7d7fcbae717e6c225dd40a5a  all  --  *      *       10.88.0.9            0.0.0.0/0            /* name: "podman" id: "e9113c7c2d8c7b970a0c7145f5de0e1d3af44c64d1b2d4f0dc130dc95743f7dc" */
Chain CNI-7d7fcbae717e6c225dd40a5a (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            10.88.0.0/16         /* name: "podman" id: "e9113c7c2d8c7b970a0c7145f5de0e1d3af44c64d1b2d4f0dc130dc95743f7dc" */
    0     0 MASQUERADE  all  --  *      *       0.0.0.0/0           !224.0.0.0/4          /* name: "podman" id: "e9113c7c2d8c7b970a0c7145f5de0e1d3af44c64d1b2d4f0dc130dc95743f7dc" */
Chain CNI-DN-7d7fcbae717e6c225dd40 (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 CNI-HOSTPORT-SETMARK  tcp  --  *      *       10.88.0.9            0.0.0.0/0            tcp dpt:8000
    0     0 CNI-HOSTPORT-SETMARK  tcp  --  *      *       127.0.0.1            0.0.0.0/0            tcp dpt:8000
    0     0 DNAT       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:8000 to:10.88.0.9:8000
Chain CNI-HOSTPORT-DNAT (2 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 CNI-DN-7d7fcbae717e6c225dd40  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* dnat name: "podman" id: "e9113c7c2d8c7b970a0c7145f5de0e1d3af44c64d1b2d4f0dc130dc95743f7dc" */ multiport dports 8000
Chain CNI-HOSTPORT-MASQ (1 references)
 pkts bytes target     prot opt in     out     source               destination
    3   180 MASQUERADE  all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x2000/0x2000
Chain CNI-HOSTPORT-SETMARK (2 references)
 pkts bytes target     prot opt in     out     source               destination
    3   180 MARK       all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* CNI portfwd masquerade mark */ MARK or 0x2000
Chain DOCKER (2 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 RETURN     all  --  docker0 *       0.0.0.0/0            0.0.0.0/0
```
Without root access:

```
Chain PREROUTING (policy ACCEPT 5 packets, 414 bytes)
 pkts bytes target     prot opt in     out     source               destination
  517 26933 DOCKER     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL
  513 26680 CNI-HOSTPORT-DNAT  all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL
Chain INPUT (policy ACCEPT 3 packets, 156 bytes)
 pkts bytes target     prot opt in     out     source               destination
Chain OUTPUT (policy ACCEPT 2 packets, 131 bytes)
 pkts bytes target     prot opt in     out     source               destination
    3   180 DOCKER     all  --  *      *       0.0.0.0/0           !127.0.0.0/8          ADDRTYPE match dst-type LOCAL
  605 40068 CNI-HOSTPORT-DNAT  all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL
Chain POSTROUTING (policy ACCEPT 2 packets, 131 bytes)
 pkts bytes target     prot opt in     out     source               destination
 1285 90602 CNI-HOSTPORT-MASQ  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* CNI portfwd requiring masquerade */
    0     0 MASQUERADE  all  --  *      !docker0  172.17.0.0/16        0.0.0.0/0
Chain CNI-HOSTPORT-DNAT (2 references)
 pkts bytes target     prot opt in     out     source               destination
Chain CNI-HOSTPORT-MASQ (1 references)
 pkts bytes target     prot opt in     out     source               destination
    3   180 MASQUERADE  all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x2000/0x2000
Chain CNI-HOSTPORT-SETMARK (0 references)
 pkts bytes target     prot opt in     out     source               destination
    3   180 MARK       all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* CNI portfwd masquerade mark */ MARK or 0x2000
Chain DOCKER (2 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 RETURN     all  --  docker0 *       0.0.0.0/0            0.0.0.0/0
```

**Comment by mheon** [comment]
I am seeing the firewall plugin working here. I've been told that the firewall is otherwise disabled, so theoretically iptables is not blocking access to the port itself...

@mccv1r0 PTAL

**Comment by mccv1r0** [comment]
Which is it?

> If we start a Podman container using root access

or

> 1. Login to non-root user: podman

CNI isn't involved at all with non-root networking at all.

Does `iptables -nvL FORWARD` allow packets to be forwarded?  Either with an explicit rule or using default policy of ACCEPT.

**Comment by Navdeepuniyal** [comment]
If we start the container using root access.
As shown in the IPTables output:

```
Chain CNI-DN-7d7fcbae717e6c225dd40 (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 CNI-HOSTPORT-SETMARK  tcp  --  *      *       10.88.0.9            0.0.0.0/0            tcp dpt:8000
    0     0 CNI-HOSTPORT-SETMARK  tcp  --  *      *       127.0.0.1            0.0.0.0/0            tcp dpt:8000
    0     0 DNAT       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:8000 to:10.88.0.9:8000
Chain CNI-HOSTPORT-DNAT (2 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 CNI-DN-7d7fcbae717e6c225dd40  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* dnat name: "podman" id: "e9113c7c2d8c7b970a0c7145f5de0e1d3af44c64d1b2d4f0dc130dc95743f7dc" */ multiport dports 8000

```
The one above is not present in the ones with non-root access. Potentially this is done by the CNI.

Moreover, I am not sure which firewall plugin is working here. Cannot find anything. 
```
$sudo ufw status verbose
>>Status: inactive
```

**Comment by mheon** [comment]
CNI is definitely adding NAT table rules, but we don't know if the system firewall is actually configured to accept connections. `iptables -nvL` with a root container running would help determine that.

**Comment by mccv1r0** [comment]
> iptables -nvL with a root container running would help determine that

`podman` needs to be started via root (e.g. `sudo podman run...`) otherwise  CNI doesn't get used.

On the host itself we need to see `sudo iptables -nvL` to determine if the FORWARD chain will let source IPv4 address that are not local to this system be forwarded to containers running on the bridge used by `podman`

**Comment by Navdeepuniyal** [comment]
Condition: No container running (using sudo)
iptables -nvL  :

```
Chain INPUT (policy ACCEPT 276 packets, 26210 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain FORWARD (policy DROP 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
    0     0 DOCKER-USER  all  --  *      *       0.0.0.0/0            0.0.0.0/0
    0     0 DOCKER-ISOLATION-STAGE-1  all  --  *      *       0.0.0.0/0            0.0.0.0/0
    0     0 ACCEPT     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
    0     0 DOCKER     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0
    0     0 ACCEPT     all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0
    0     0 ACCEPT     all  --  docker0 docker0  0.0.0.0/0            0.0.0.0/0

Chain OUTPUT (policy ACCEPT 179 packets, 20821 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain DOCKER (1 references)
 pkts bytes target     prot opt in     out     source               destination

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 DOCKER-ISOLATION-STAGE-2  all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0
    0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain DOCKER-ISOLATION-STAGE-2 (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 DROP       all  --  *      docker0  0.0.0.0/0            0.0.0.0/0
    0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain DOCKER-USER (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0
```
Condition: container running (using sudo)
iptables -nvL  :

```
Chain INPUT (policy ACCEPT 19 packets, 1564 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain FORWARD (policy DROP 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
    0     0 CNI-FORWARD  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* CNI firewall plugin rules */
    0     0 DOCKER-USER  all  --  *      *       0.0.0.0/0            0.0.0.0/0
    0     0 DOCKER-ISOLATION-STAGE-1  all  --  *      *       0.0.0.0/0            0.0.0.0/0
    0     0 ACCEPT     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
    0     0 DOCKER     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0
    0     0 ACCEPT     all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0
    0     0 ACCEPT     all  --  docker0 docker0  0.0.0.0/0            0.0.0.0/0

Chain OUTPUT (policy ACCEPT 15 packets, 1316 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain CNI-ADMIN (1 references)
 pkts bytes target     prot opt in     out     source               destination

Chain CNI-FORWARD (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 CNI-ADMIN  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* CNI firewall plugin rules */
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            10.88.0.12           ctstate RELATED,ESTABLISHED
    0     0 ACCEPT     all  --  *      *       10.88.0.12           0.0.0.0/0

Chain DOCKER (1 references)
 pkts bytes target     prot opt in     out     source               destination

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 DOCKER-ISOLATION-STAGE-2  all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0
    0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain DOCKER-ISOLATION-STAGE-2 (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 DROP       all  --  *      docker0  0.0.0.0/0            0.0.0.0/0
    0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain DOCKER-USER (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0
```

**Comment by mheon** [comment]
Default policy for FORWARD does seem to be drop, so I think you'll need to manually add a rule to allow inbound traffic on port 8000.

**Comment by Navdeepuniyal** [comment]
Done that. Didn't work !

**Comment by Navdeepuniyal** [comment]
Update:
I tried the scenario again with another machine. The only difference here is that no docker is running on this new VM. Following are the IP tables output:

```
sudo iptables -nvL
Chain INPUT (policy ACCEPT 73 packets, 5075 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain FORWARD (policy ACCEPT 2 packets, 104 bytes)
 pkts bytes target     prot opt in     out     source               destination
    8   793 CNI-FORWARD  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* CNI firewall plugin rules */

Chain OUTPUT (policy ACCEPT 40 packets, 3408 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain CNI-ADMIN (1 references)
 pkts bytes target     prot opt in     out     source               destination

Chain CNI-FORWARD (1 references)
 pkts bytes target     prot opt in     out     source               destination
    8   793 CNI-ADMIN  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* CNI firewall plugin rules */
    3   545 ACCEPT     all  --  *      *       0.0.0.0/0            10.88.0.2            ctstate RELATED,ESTABLISHED
    3   144 ACCEPT     all  --  *      *       10.88.0.2            0.0.0.0/0

```

This works fine and I am able to access port from external IP Address. 
Not sure but iptables rules by docker might be interferring with Podman.

**Comment by maxm123** [comment]
I guess it's still the same as [here](https://github.com/containers/libpod/issues/5316#issuecomment-592057783) and even [here](https://github.com/containers/libpod/issues/2886#issuecomment-488620599). Red Hat distros seem to have fixed that (at least Fedora did and [this thread](https://bugzilla.redhat.com/show_bug.cgi?id=1703261#c30) is about RHEL). In e.g. the Debian packages, this wasn't done yet. But as it is a package maintainer problem, there is no solution to include in libpod. Maybe someone could add this to the [troubleshooting file](https://github.com/containers/libpod/blob/master/troubleshooting.md).

**Comment by rhatdan** [comment]
@mheon @maxm123 @Navdeepuniyal Is this a documentation bug?  No Bug?  Can I close the issue?

**Comment by baude** [comment]
closing as distribution problem.  re-open with updates if not happy.
