### ISSUE TITLE
podman-remote exec -i, with stdin redirection, hangs

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#7360]
In window 1:
```console
$ ./bin/podman system service --timeout=0
```
In window 2:
```console
$ ./bin/podman-remote run -d --name foo alpine sleep 20
60a88de15c87d44872b20f2716cd529de4ca0471527151456049dbc3dfeaa927

$ ./bin/podman-remote exec -i foo cat <<<"hi there"
hi there
<<<--- hangs here (no prompt, no nothing) until container sleep finishes. ^D does nothing.
```
Without `-i` there is no hang, but there is no output either.

Regular (non-remote) podman works fine: output is as expected, and the `exec` returns immediately.

master @ 748e8829d, root & rootless

**Comment by vrothberg** [comment]
@mheon, do you have cycles to tackle it? My guts tell me you'll know where to punch :)

**Comment by mheon** [comment]
Maybe? I'll self-assign, and we'll see how much I can get done this week.

**Comment by rhatdan** [comment]
@mheon Any movement on this?

**Comment by mheon** [comment]
Not yet.

**Comment by edsantiago** [comment]
Still present in ab1d3a58d4b98bc948d7344fc27c680ca326086f; removing stale-issue label.

**Comment by rhatdan** [comment]
@mheon Reminder.

**Comment by mheon** [comment]
I will try and get to this in January.

**Comment by edsantiago** [comment]
Issue still present in master @ a47515008b3c0dde9f161faa0d9f455ca6772393

**Comment by mheon** [comment]
I wonder if Conmon 2.0.26 has resolved this - will re-test with it.

**Comment by rhatdan** [comment]
I am assuming this is fixed in Main, reopen if I am mistaken.

**Comment by edsantiago** [comment]
Unfortunately, this is not fixed. There is a very simple reproducer, it is still failing on master. There are two system tests being skipped right now with "FIXME: pending #7360", they hang too. Reopening.

**Comment by christian-korneck** [comment]
also seems to happen when using the `docker` cli over ssh to a podman server (3.0.1)

```
$ echo uname | docker -H ssh://<server> exec -i <container> sh
Linux
[hangs until aborted...]
```

docker cli: 20.10.5, build 55c4c88, macOS 11.2.3 x86_64
podman: 3.0.1, fedora 33 x86_64

**Comment by edsantiago** [comment]
Still present in master @ a67aec72eda161876b9ba6d4d31af0d7de8fc824, conmon-2.0.27-2.fc33

One more data point I hadn't noticed before: the `podman exec cat` process exits 137 (`kill -9`). This is quite unexpected.

**Comment by edsantiago** [comment]
Still present in 6df37abd502d53a695392723af0d4a4970be3e58

**Comment by rhatdan** [comment]
@mheon This is the great albatross around podman's neck. ...

**Comment by mheon** [comment]
The core problem: EOF on the client isn't being handled properly. We need to get an EOF to the server, *without* actually closing the connection - we're not done until the server finished streaming output.

**Comment by rhatdan** [comment]
Seeing this is blocking vscode, it becomes more important.

**Comment by mheon** [comment]
Alright, I know generally what needs to be done here. We need to do a one-sided close on the hijacked connection (client needs to close the write side of the conn, while the read side is left open). Unfortunately, that's not enough - the backend is still not terminating, so I need to get into the HTTP attach code and figure out why it's not terminating.

**Comment by mheon** [comment]
Apparently it was a very simple fix. PR in progress.

**Comment by baude** [comment]
@mheon beast!
