### ISSUE TITLE
CI: integration timing results are randomly incomplete

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#8358]
Compare two CI logs, one [ubuntu-19](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5322692788224000/html/int-podman-ubuntu-19-root-host.log.html) and one [20](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5885642741645312/html/int-podman-ubuntu-20-root-host.log.html). Search in-page for `test path`, or `reimport`, or `check dnsname`, or many many others (I'm just offering short easy-to-search-for strings). Note that those appear in the bottom `timing results` section only on one page, not the other, although the tests ran on both.

Something is gobbling up timing results; this seems like a good place to start looking: https://github.com/containers/podman/blob/9fa09a83b30c5d9300eb40b3d50b405153b37f7a/test/e2e/common_test.go#L346-L349 (maybe this isn't thread-safe?)

@baude weren't you looking into this some months ago?

**Comment by rhatdan** [comment]
@baude @edsantiago Still an issue?

**Comment by edsantiago** [comment]
Yes but I seem to be the only one who cares

**Comment by vrothberg** [comment]
I just hit performance variations in the remote system tests in https://github.com/containers/podman/pull/8747.

@edsantiago and I looked into a VM together and noticed performance variations on Ubuntu 20.04.  https://github.com/containers/podman/pull/8747 bumps the time out from 60 to 120 seconds.

**Comment by rhatdan** [comment]
@edsantiago @vrothberg Since we merged the bump can we close this issue?

**Comment by edsantiago** [comment]
The issue is not fixed. Example: [ubuntu 2010 log for PR 9082](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6211303586922496/html/int-podman-ubuntu-2010-root-host.log.html). Search in-page for "preserves container". The test is run, but there is no summary line. Compare to [ubuntu 2004 log for same PR](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4803928703369216/html/int-podman-ubuntu-2004-root-host.log.html). Here the test is run and also summarized at bottom.

This is a problem because we still don't understand why ubuntu 2010 runs slower than 2004, and without logged timing results there is no possible way to actually look into the difference.


I really feel like this must be a trivial one-line fix for someone who understands Go arrays and threads.
