### ISSUE TITLE
Can no longer install systemd into an ubuntu bionic container without --privileged 

### ISSUE THREAD

**Issue by towe75** [containers/podman#9421]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Some of our builds are broken after podman 3.0 update. We examined it and found that a simple "apt install init" failed.
Further debugging nailed it down to a simple test case and it seems to be related to changed default permissions.
Adding CAP_AUDIT_WRITE fixes the issue.

**Steps to reproduce the issue:**

## Negative rootful test: 
1. podman run -it --rm ubuntu:bionic /usr/bin/chfn -f "test" irc
2. non 0 exit, complains about "PAM: System error"

*same command works when running rootless*

## Postitive rootful test A:
1. podman run --privileged -it --rm ubuntu:bionic /usr/bin/chfn -f "test" irc
2. exit code 0, no output

## Positive rootful test B:
1.  podman run --cap-add=all -it --rm ubuntu:bionic /usr/bin/chfn -f "test" irc
2. exit code 0, no output

## Positive rootful test C:
1.  podman run --cap-add=CAP_AUDIT_WRITE -it --rm ubuntu:bionic /usr/bin/chfn -f "test" irc
2. exit code 0, no output

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.0.0
API Version:  3.0.0
Go Version:   go1.15.2
Built:        Thu Jan  1 00:00:00 1970
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
host:
  arch: amd64
  buildahVersion: 1.19.2
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.26, commit: '
  cpus: 2
  distribution:
    distribution: ubuntu
    version: "18.04"
  eventLogger: journald
  hostname: xxxxxxx
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.15.0-135-generic
  linkmode: dynamic
  memFree: 71000064
  memTotal: 2090299392
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.17.6-58ef-dirty
      commit: fd582c529489c0738e7039cbc036781d1d039014
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: true
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    selinuxEnabled: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 890216448
  swapTotal: 1045143552
  uptime: 3h 6m 56.83s (Approximately 0.12 days)
registries:
  search:
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /persistent/containers
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 1
  runRoot: /var/run/containers/storage
  volumePath: /persistent/containers/volumes
version:
  APIVersion: 3.0.0
  Built: 0
  BuiltTime: Thu Jan  1 00:00:00 1970
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/amd64
  Version: 3.0.0```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

It's a vSphere vm but we reproduced also on a local workstation.

**Comment by rhatdan** [comment]
Can you just add cap_audit_write and see if it works.  You can add CAP_AUDIT_WRITE by default using the /etc/containers/containers.conf

@giuseppe Do you know why the seccomp mapping for this is not working?

**Comment by towe75** [comment]
@rhatdan : did already, see my "Positive rootful test C:" result. 
I'm not sure if we can categorize this as bug but it's certainly a noteworthy change to the older version. 

Running systemd in a container was one of the major selling points for me to dig into podman, btw ;-)

**Comment by giuseppe** [comment]
it looks like an outdated `seccomp.json` profile.

For a test, could you grab the latest version from: https://raw.githubusercontent.com/containers/common/master/pkg/seccomp/seccomp.json

and then attempt something like?

```
# podman run --security-opt seccomp=/PATH/TO/THE/NEW/seccomp.json -it --rm ubuntu:bionic /usr/bin/chfn -f "test" irc
```

**Comment by towe75** [comment]
@giuseppe : you are right, it's related to seccomp.json. But it is not outdated, it's missing. It seems to be yet another packaging issue. 

Ubuntu 18.04 / podman 2.2.1 ships a seccomp.json in package containers-golang and stores it into the correct folder: /usr/share/containers/seccomp.json

Now with podman 3.x we get a containers-common instead of containers-golang but there is no seccomp.json included.

Am i missing something or could that be the culprit?

**Comment by rhatdan** [comment]
Yes sounds like the issue.  @lsm5 PTAL

**Comment by lsm5** [comment]
@towe75 hi, so there should currently be an `/etc/containers/seccomp.json` installed. Would you mind moving that to /usr/share/containers and retrying this please? If it works, I'll build a new containers-common with the filed installed to /usr/share/containers.

HTH.

**Comment by lsm5** [comment]
> @towe75 hi, so there should currently be an `/etc/containers/seccomp.json` installed. Would you mind moving that to /usr/share/containers and retrying this please? If it works, I'll build a new containers-common with the filed installed to /usr/share/containers.
> 
> HTH.

Scratch that (Monday morning), I do see it should be installed to /usr/share/containers. So I guess something went wrong in packaging. Let me get back on this.

**Comment by lsm5** [comment]
@towe75 containers-common 100:1-12 should fix it, looks like it should be available for the ubuntus: https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable/containers-common .. I've also pushed podman buildah and skopeo builds to handle the minimum dependency so this won't be an issue for fresh installs.

Please close if that resolves this issue.

**Comment by towe75** [comment]
Hey @lsm5, thank you! I can not test it right now but i'll give it a spin later.

**Comment by towe75** [comment]
I ran a clean install and tested in our lab env: it's not resolved yet. 

I've got indeed a containers-common 100:1-12 and there is now a seccomp.json included. It's, however, different to the one @giuseppe recommended and i still get the same error. Moving the other seccomp.json into the default folder fixes the problem - so rules files is maybe outdated?

Additionally i get now an additional warning:

```
podman run -it --rm ubuntu:bionic /usr/bin/chfn -f "test" irc 

WARN[0000] Path "/usr/share/rhel/secrets" from "/usr/share/containers/mounts.conf" doesn't exist, skipping                                                                           chfn: PAM: System error                         
```

**Comment by lsm5** [comment]
> I ran a clean install and tested in our lab env: it's not resolved yet.
> 
> I've got indeed a containers-common 100:1-12 and there is now a seccomp.json included. It's, however, different to the one @giuseppe recommended and i still get the same error. Moving the other seccomp.json into the default folder fixes the problem - so rules files is maybe outdated?
> 

So, the seccomp.json is installed to /usr/share/containers/seccomp.json, isn't it? What the default folder you mention here? 

> Additionally i get now an additional warning:
> 
> ```
> podman run -it --rm ubuntu:bionic /usr/bin/chfn -f "test" irc 
> 
> WARN[0000] Path "/usr/share/rhel/secrets" from "/usr/share/containers/mounts.conf" doesn't exist, skipping                                                                           chfn: PAM: System error                         
> ```

Ah, I shouldn't be installing that file. My bad, that came in from fedora land, sorry.

**Comment by towe75** [comment]
Yes, seccomp.json is in /usr/share/containers/seccomp.json and i called it "the default folder" because podman seems to pick it up from there...

```
dpkg -L containers-common

...
...
/usr/share/containers
/usr/share/containers/containers.conf
/usr/share/containers/mounts.conf
/usr/share/containers/seccomp.json
...
...
```

```
sha1sum  /usr/share/containers/seccomp.json

aedfdf046f5dad530cb9999d6cf1970dba7f41a3  /usr/share/containers/seccomp.json
```

**Comment by lsm5** [comment]
@towe75 ack, building a new one now, sorry about that.

**Comment by lsm5** [comment]
@towe75 there should now be a 100:1-13 available on kubic, https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable/containers-common . Let me know ..

**Comment by towe75** [comment]
Sure - but it has to wait for tomorrow morning. CET here. 🕙

**Comment by towe75** [comment]
Results:

- rhel/secrets message is gone
- pam error is not fixed
- i can still see a difference between the packages seccomp.json and the one from master (mentioned above). Although the diff is now only a single line:

```
sha1sum secc*
9c8f01df0db5ad29e77335ebc986417b0426806e  seccomp.json.dpkg
67ec77ab25d1a3f664b0ef7e39a3d5949dc79ec3  seccomp.json.master

diff -Naur seccomp.json.dpkg seccomp.json.master
--- seccomp.json.dpkg   2021-02-23 06:44:47.182295621 +0000
+++ seccomp.json.master 2021-02-23 06:44:59.506469522 +0000
@@ -340,7 +340,6 @@
                                "signalfd",
                                "signalfd4",
                                "sigreturn",
-                                "socket",
                                "socketcall",
                                "socketpair",
                                "splice",

```

**Comment by simonfxr** [comment]
@lsm5 @towe75 After updating and then using the seccomp.json from master, the problem seems to be fixed. However containers-common now installs strange files in /etc/containers:
`dpkg -L containers-common | grep '{'` gives:
```
/etc/containers/{certs.d,oci
/etc/containers/{certs.d,oci/hooks.d}
```
Looks like a bash brace expansion problem.

**Comment by lsm5** [comment]
> Results:
> 
>     * rhel/secrets message is gone

Great

> 
>     * pam error is not fixed


@rhatdan do you know whatsup with the PAM error?



> 
>     * i can still see a difference between the packages seccomp.json and the one from master (mentioned above). Although the diff is now only a single line:
> 
> 
> ```
> sha1sum secc*
> 9c8f01df0db5ad29e77335ebc986417b0426806e  seccomp.json.dpkg
> 67ec77ab25d1a3f664b0ef7e39a3d5949dc79ec3  seccomp.json.master
> 
> diff -Naur seccomp.json.dpkg seccomp.json.master
> --- seccomp.json.dpkg   2021-02-23 06:44:47.182295621 +0000
> +++ seccomp.json.master 2021-02-23 06:44:59.506469522 +0000
> @@ -340,7 +340,6 @@
>                                 "signalfd",
>                                 "signalfd4",
>                                 "sigreturn",
> -                                "socket",
>                                 "socketcall",
>                                 "socketpair",
>                                 "splice",
> ```

@rhatdan @giuseppe in fedora's containers-common we add `socket` if socketcall is found. Is this something ubuntu should not do ?

**Comment by lsm5** [comment]
> @lsm5 @towe75 After updating and then using the seccomp.json from master, the problem seems to be fixed. However containers-common now installs strange files in /etc/containers:
> `dpkg -L containers-common | grep '{'` gives:
> 
> ```
> /etc/containers/{certs.d,oci
> /etc/containers/{certs.d,oci/hooks.d}
> ```
> 
> Looks like a bash brace expansion problem.

ugh, fixing ..

**Comment by lsm5** [comment]
Sent a new containers-common 100:1-14 to OBS. Fixes the funny dir names issue and also installs an unchanged seccomp.json. Let me know how that goes.

**Comment by rhatdan** [comment]
pam_error might be being caused by us blocking audit_write.

**Comment by towe75** [comment]
@lsm5 the pam error is also gone now. I tried both the simple one-line test case from above and also a longer one including a "apt install init" command.

**Comment by rhatdan** [comment]
Ok I am going to close.
